// Code generated by ent, DO NOT EDIT.

package curatedregisteractivity

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the curatedregisteractivity type in the database.
	Label = "curated_register_activity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRegisterID holds the string denoting the register_id field in the database.
	FieldRegisterID = "register_id"
	// FieldAdminID holds the string denoting the admin_id field in the database.
	FieldAdminID = "admin_id"
	// FieldReplyToID holds the string denoting the reply_to_id field in the database.
	FieldReplyToID = "reply_to_id"
	// FieldSecretCode holds the string denoting the secret_code field in the database.
	FieldSecretCode = "secret_code"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldLink holds the string denoting the link field in the database.
	FieldLink = "link"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldFromAdmin holds the string denoting the from_admin field in the database.
	FieldFromAdmin = "from_admin"
	// FieldFromUser holds the string denoting the from_user field in the database.
	FieldFromUser = "from_user"
	// FieldAdminOnlyView holds the string denoting the admin_only_view field in the database.
	FieldAdminOnlyView = "admin_only_view"
	// FieldActionRequired holds the string denoting the action_required field in the database.
	FieldActionRequired = "action_required"
	// FieldAdminNotifiedAt holds the string denoting the admin_notified_at field in the database.
	FieldAdminNotifiedAt = "admin_notified_at"
	// FieldActionTakenAt holds the string denoting the action_taken_at field in the database.
	FieldActionTakenAt = "action_taken_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the curatedregisteractivity in the database.
	Table = "curated_register_activities"
)

// Columns holds all SQL columns for curatedregisteractivity fields.
var Columns = []string{
	FieldID,
	FieldRegisterID,
	FieldAdminID,
	FieldReplyToID,
	FieldSecretCode,
	FieldType,
	FieldTitle,
	FieldLink,
	FieldMessage,
	FieldMetadata,
	FieldFromAdmin,
	FieldFromUser,
	FieldAdminOnlyView,
	FieldActionRequired,
	FieldAdminNotifiedAt,
	FieldActionTakenAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultFromAdmin holds the default value on creation for the "from_admin" field.
	DefaultFromAdmin bool
	// DefaultFromUser holds the default value on creation for the "from_user" field.
	DefaultFromUser bool
	// DefaultAdminOnlyView holds the default value on creation for the "admin_only_view" field.
	DefaultAdminOnlyView bool
	// DefaultActionRequired holds the default value on creation for the "action_required" field.
	DefaultActionRequired bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CuratedRegisterActivity queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRegisterID orders the results by the register_id field.
func ByRegisterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegisterID, opts...).ToFunc()
}

// ByAdminID orders the results by the admin_id field.
func ByAdminID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminID, opts...).ToFunc()
}

// ByReplyToID orders the results by the reply_to_id field.
func ByReplyToID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplyToID, opts...).ToFunc()
}

// BySecretCode orders the results by the secret_code field.
func BySecretCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretCode, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByLink orders the results by the link field.
func ByLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLink, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByFromAdmin orders the results by the from_admin field.
func ByFromAdmin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromAdmin, opts...).ToFunc()
}

// ByFromUser orders the results by the from_user field.
func ByFromUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromUser, opts...).ToFunc()
}

// ByAdminOnlyView orders the results by the admin_only_view field.
func ByAdminOnlyView(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminOnlyView, opts...).ToFunc()
}

// ByActionRequired orders the results by the action_required field.
func ByActionRequired(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionRequired, opts...).ToFunc()
}

// ByAdminNotifiedAt orders the results by the admin_notified_at field.
func ByAdminNotifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminNotifiedAt, opts...).ToFunc()
}

// ByActionTakenAt orders the results by the action_taken_at field.
func ByActionTakenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionTakenAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
