// Code generated by ent, DO NOT EDIT.

package parentalcontrols

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"glintfed.org/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLTE(FieldID, id))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldParentID, v))
}

// ChildID applies equality check predicate on the "child_id" field. It's identical to ChildIDEQ.
func ChildID(v uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldChildID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldEmail, v))
}

// VerifyCode applies equality check predicate on the "verify_code" field. It's identical to VerifyCodeEQ.
func VerifyCode(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldVerifyCode, v))
}

// EmailSentAt applies equality check predicate on the "email_sent_at" field. It's identical to EmailSentAtEQ.
func EmailSentAt(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldEmailSentAt, v))
}

// EmailVerifiedAt applies equality check predicate on the "email_verified_at" field. It's identical to EmailVerifiedAtEQ.
func EmailVerifiedAt(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldEmailVerifiedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldUpdatedAt, v))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDGT applies the GT predicate on the "parent_id" field.
func ParentIDGT(v uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGT(FieldParentID, v))
}

// ParentIDGTE applies the GTE predicate on the "parent_id" field.
func ParentIDGTE(v uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGTE(FieldParentID, v))
}

// ParentIDLT applies the LT predicate on the "parent_id" field.
func ParentIDLT(v uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLT(FieldParentID, v))
}

// ParentIDLTE applies the LTE predicate on the "parent_id" field.
func ParentIDLTE(v uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLTE(FieldParentID, v))
}

// ChildIDEQ applies the EQ predicate on the "child_id" field.
func ChildIDEQ(v uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldChildID, v))
}

// ChildIDNEQ applies the NEQ predicate on the "child_id" field.
func ChildIDNEQ(v uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNEQ(FieldChildID, v))
}

// ChildIDIn applies the In predicate on the "child_id" field.
func ChildIDIn(vs ...uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIn(FieldChildID, vs...))
}

// ChildIDNotIn applies the NotIn predicate on the "child_id" field.
func ChildIDNotIn(vs ...uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotIn(FieldChildID, vs...))
}

// ChildIDGT applies the GT predicate on the "child_id" field.
func ChildIDGT(v uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGT(FieldChildID, v))
}

// ChildIDGTE applies the GTE predicate on the "child_id" field.
func ChildIDGTE(v uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGTE(FieldChildID, v))
}

// ChildIDLT applies the LT predicate on the "child_id" field.
func ChildIDLT(v uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLT(FieldChildID, v))
}

// ChildIDLTE applies the LTE predicate on the "child_id" field.
func ChildIDLTE(v uint32) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLTE(FieldChildID, v))
}

// ChildIDIsNil applies the IsNil predicate on the "child_id" field.
func ChildIDIsNil() predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIsNull(FieldChildID))
}

// ChildIDNotNil applies the NotNil predicate on the "child_id" field.
func ChildIDNotNil() predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotNull(FieldChildID))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldContainsFold(FieldEmail, v))
}

// VerifyCodeEQ applies the EQ predicate on the "verify_code" field.
func VerifyCodeEQ(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldVerifyCode, v))
}

// VerifyCodeNEQ applies the NEQ predicate on the "verify_code" field.
func VerifyCodeNEQ(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNEQ(FieldVerifyCode, v))
}

// VerifyCodeIn applies the In predicate on the "verify_code" field.
func VerifyCodeIn(vs ...string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIn(FieldVerifyCode, vs...))
}

// VerifyCodeNotIn applies the NotIn predicate on the "verify_code" field.
func VerifyCodeNotIn(vs ...string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotIn(FieldVerifyCode, vs...))
}

// VerifyCodeGT applies the GT predicate on the "verify_code" field.
func VerifyCodeGT(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGT(FieldVerifyCode, v))
}

// VerifyCodeGTE applies the GTE predicate on the "verify_code" field.
func VerifyCodeGTE(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGTE(FieldVerifyCode, v))
}

// VerifyCodeLT applies the LT predicate on the "verify_code" field.
func VerifyCodeLT(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLT(FieldVerifyCode, v))
}

// VerifyCodeLTE applies the LTE predicate on the "verify_code" field.
func VerifyCodeLTE(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLTE(FieldVerifyCode, v))
}

// VerifyCodeContains applies the Contains predicate on the "verify_code" field.
func VerifyCodeContains(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldContains(FieldVerifyCode, v))
}

// VerifyCodeHasPrefix applies the HasPrefix predicate on the "verify_code" field.
func VerifyCodeHasPrefix(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldHasPrefix(FieldVerifyCode, v))
}

// VerifyCodeHasSuffix applies the HasSuffix predicate on the "verify_code" field.
func VerifyCodeHasSuffix(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldHasSuffix(FieldVerifyCode, v))
}

// VerifyCodeIsNil applies the IsNil predicate on the "verify_code" field.
func VerifyCodeIsNil() predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIsNull(FieldVerifyCode))
}

// VerifyCodeNotNil applies the NotNil predicate on the "verify_code" field.
func VerifyCodeNotNil() predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotNull(FieldVerifyCode))
}

// VerifyCodeEqualFold applies the EqualFold predicate on the "verify_code" field.
func VerifyCodeEqualFold(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEqualFold(FieldVerifyCode, v))
}

// VerifyCodeContainsFold applies the ContainsFold predicate on the "verify_code" field.
func VerifyCodeContainsFold(v string) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldContainsFold(FieldVerifyCode, v))
}

// EmailSentAtEQ applies the EQ predicate on the "email_sent_at" field.
func EmailSentAtEQ(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldEmailSentAt, v))
}

// EmailSentAtNEQ applies the NEQ predicate on the "email_sent_at" field.
func EmailSentAtNEQ(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNEQ(FieldEmailSentAt, v))
}

// EmailSentAtIn applies the In predicate on the "email_sent_at" field.
func EmailSentAtIn(vs ...time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIn(FieldEmailSentAt, vs...))
}

// EmailSentAtNotIn applies the NotIn predicate on the "email_sent_at" field.
func EmailSentAtNotIn(vs ...time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotIn(FieldEmailSentAt, vs...))
}

// EmailSentAtGT applies the GT predicate on the "email_sent_at" field.
func EmailSentAtGT(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGT(FieldEmailSentAt, v))
}

// EmailSentAtGTE applies the GTE predicate on the "email_sent_at" field.
func EmailSentAtGTE(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGTE(FieldEmailSentAt, v))
}

// EmailSentAtLT applies the LT predicate on the "email_sent_at" field.
func EmailSentAtLT(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLT(FieldEmailSentAt, v))
}

// EmailSentAtLTE applies the LTE predicate on the "email_sent_at" field.
func EmailSentAtLTE(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLTE(FieldEmailSentAt, v))
}

// EmailSentAtIsNil applies the IsNil predicate on the "email_sent_at" field.
func EmailSentAtIsNil() predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIsNull(FieldEmailSentAt))
}

// EmailSentAtNotNil applies the NotNil predicate on the "email_sent_at" field.
func EmailSentAtNotNil() predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotNull(FieldEmailSentAt))
}

// EmailVerifiedAtEQ applies the EQ predicate on the "email_verified_at" field.
func EmailVerifiedAtEQ(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldEmailVerifiedAt, v))
}

// EmailVerifiedAtNEQ applies the NEQ predicate on the "email_verified_at" field.
func EmailVerifiedAtNEQ(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNEQ(FieldEmailVerifiedAt, v))
}

// EmailVerifiedAtIn applies the In predicate on the "email_verified_at" field.
func EmailVerifiedAtIn(vs ...time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIn(FieldEmailVerifiedAt, vs...))
}

// EmailVerifiedAtNotIn applies the NotIn predicate on the "email_verified_at" field.
func EmailVerifiedAtNotIn(vs ...time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotIn(FieldEmailVerifiedAt, vs...))
}

// EmailVerifiedAtGT applies the GT predicate on the "email_verified_at" field.
func EmailVerifiedAtGT(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGT(FieldEmailVerifiedAt, v))
}

// EmailVerifiedAtGTE applies the GTE predicate on the "email_verified_at" field.
func EmailVerifiedAtGTE(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGTE(FieldEmailVerifiedAt, v))
}

// EmailVerifiedAtLT applies the LT predicate on the "email_verified_at" field.
func EmailVerifiedAtLT(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLT(FieldEmailVerifiedAt, v))
}

// EmailVerifiedAtLTE applies the LTE predicate on the "email_verified_at" field.
func EmailVerifiedAtLTE(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLTE(FieldEmailVerifiedAt, v))
}

// EmailVerifiedAtIsNil applies the IsNil predicate on the "email_verified_at" field.
func EmailVerifiedAtIsNil() predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIsNull(FieldEmailVerifiedAt))
}

// EmailVerifiedAtNotNil applies the NotNil predicate on the "email_verified_at" field.
func EmailVerifiedAtNotNil() predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotNull(FieldEmailVerifiedAt))
}

// PermissionsIsNil applies the IsNil predicate on the "permissions" field.
func PermissionsIsNil() predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIsNull(FieldPermissions))
}

// PermissionsNotNil applies the NotNil predicate on the "permissions" field.
func PermissionsNotNil() predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotNull(FieldPermissions))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ParentalControls {
	return predicate.ParentalControls(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ParentalControls) predicate.ParentalControls {
	return predicate.ParentalControls(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ParentalControls) predicate.ParentalControls {
	return predicate.ParentalControls(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ParentalControls) predicate.ParentalControls {
	return predicate.ParentalControls(sql.NotPredicates(p))
}
