app:
  name: glintfed
  version: 0.0.0
  env: local
  url: http://localhost:8000

  auth:
    enable_registration: true

  federation:
    nodeinfo:
      enabled: true

server:
  api:
    bind: ":8000"

service:
  open_telemetry:
    tracing_enabled: false
    tracing_endpoint: localhost:4317