app:
  name: glintfed
  env: local
  url: http://localhost:8000
  federation:
    nodeinfo:
      enabled: true

server:
  api:
    bind: ":8000"

service:
  open_telemetry:
    tracing_enabled: false
    tracing_endpoint: localhost:4317