// Code generated by ent, DO NOT EDIT.

package userdomainblock

import (
	"entgo.io/ent/dialect/sql"
	"glintfed.org/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldLTE(FieldID, id))
}

// ProfileID applies equality check predicate on the "profile_id" field. It's identical to ProfileIDEQ.
func ProfileID(v uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldEQ(FieldProfileID, v))
}

// Domain applies equality check predicate on the "domain" field. It's identical to DomainEQ.
func Domain(v string) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldEQ(FieldDomain, v))
}

// ProfileIDEQ applies the EQ predicate on the "profile_id" field.
func ProfileIDEQ(v uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldEQ(FieldProfileID, v))
}

// ProfileIDNEQ applies the NEQ predicate on the "profile_id" field.
func ProfileIDNEQ(v uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldNEQ(FieldProfileID, v))
}

// ProfileIDIn applies the In predicate on the "profile_id" field.
func ProfileIDIn(vs ...uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldIn(FieldProfileID, vs...))
}

// ProfileIDNotIn applies the NotIn predicate on the "profile_id" field.
func ProfileIDNotIn(vs ...uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldNotIn(FieldProfileID, vs...))
}

// ProfileIDGT applies the GT predicate on the "profile_id" field.
func ProfileIDGT(v uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldGT(FieldProfileID, v))
}

// ProfileIDGTE applies the GTE predicate on the "profile_id" field.
func ProfileIDGTE(v uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldGTE(FieldProfileID, v))
}

// ProfileIDLT applies the LT predicate on the "profile_id" field.
func ProfileIDLT(v uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldLT(FieldProfileID, v))
}

// ProfileIDLTE applies the LTE predicate on the "profile_id" field.
func ProfileIDLTE(v uint64) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldLTE(FieldProfileID, v))
}

// DomainEQ applies the EQ predicate on the "domain" field.
func DomainEQ(v string) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldEQ(FieldDomain, v))
}

// DomainNEQ applies the NEQ predicate on the "domain" field.
func DomainNEQ(v string) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldNEQ(FieldDomain, v))
}

// DomainIn applies the In predicate on the "domain" field.
func DomainIn(vs ...string) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldIn(FieldDomain, vs...))
}

// DomainNotIn applies the NotIn predicate on the "domain" field.
func DomainNotIn(vs ...string) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldNotIn(FieldDomain, vs...))
}

// DomainGT applies the GT predicate on the "domain" field.
func DomainGT(v string) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldGT(FieldDomain, v))
}

// DomainGTE applies the GTE predicate on the "domain" field.
func DomainGTE(v string) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldGTE(FieldDomain, v))
}

// DomainLT applies the LT predicate on the "domain" field.
func DomainLT(v string) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldLT(FieldDomain, v))
}

// DomainLTE applies the LTE predicate on the "domain" field.
func DomainLTE(v string) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldLTE(FieldDomain, v))
}

// DomainContains applies the Contains predicate on the "domain" field.
func DomainContains(v string) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldContains(FieldDomain, v))
}

// DomainHasPrefix applies the HasPrefix predicate on the "domain" field.
func DomainHasPrefix(v string) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldHasPrefix(FieldDomain, v))
}

// DomainHasSuffix applies the HasSuffix predicate on the "domain" field.
func DomainHasSuffix(v string) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldHasSuffix(FieldDomain, v))
}

// DomainEqualFold applies the EqualFold predicate on the "domain" field.
func DomainEqualFold(v string) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldEqualFold(FieldDomain, v))
}

// DomainContainsFold applies the ContainsFold predicate on the "domain" field.
func DomainContainsFold(v string) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.FieldContainsFold(FieldDomain, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserDomainBlock) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserDomainBlock) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserDomainBlock) predicate.UserDomainBlock {
	return predicate.UserDomainBlock(sql.NotPredicates(p))
}
