// Code generated by ent, DO NOT EDIT.

package admininvite

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"glintfed.org/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldName, v))
}

// InviteCode applies equality check predicate on the "invite_code" field. It's identical to InviteCodeEQ.
func InviteCode(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldInviteCode, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldDescription, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldMessage, v))
}

// MaxUses applies equality check predicate on the "max_uses" field. It's identical to MaxUsesEQ.
func MaxUses(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldMaxUses, v))
}

// Uses applies equality check predicate on the "uses" field. It's identical to UsesEQ.
func Uses(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldUses, v))
}

// SkipEmailVerification applies equality check predicate on the "skip_email_verification" field. It's identical to SkipEmailVerificationEQ.
func SkipEmailVerification(v bool) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldSkipEmailVerification, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldExpiresAt, v))
}

// AdminUserID applies equality check predicate on the "admin_user_id" field. It's identical to AdminUserIDEQ.
func AdminUserID(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldAdminUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldContainsFold(FieldName, v))
}

// InviteCodeEQ applies the EQ predicate on the "invite_code" field.
func InviteCodeEQ(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldInviteCode, v))
}

// InviteCodeNEQ applies the NEQ predicate on the "invite_code" field.
func InviteCodeNEQ(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNEQ(FieldInviteCode, v))
}

// InviteCodeIn applies the In predicate on the "invite_code" field.
func InviteCodeIn(vs ...string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIn(FieldInviteCode, vs...))
}

// InviteCodeNotIn applies the NotIn predicate on the "invite_code" field.
func InviteCodeNotIn(vs ...string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotIn(FieldInviteCode, vs...))
}

// InviteCodeGT applies the GT predicate on the "invite_code" field.
func InviteCodeGT(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGT(FieldInviteCode, v))
}

// InviteCodeGTE applies the GTE predicate on the "invite_code" field.
func InviteCodeGTE(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGTE(FieldInviteCode, v))
}

// InviteCodeLT applies the LT predicate on the "invite_code" field.
func InviteCodeLT(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLT(FieldInviteCode, v))
}

// InviteCodeLTE applies the LTE predicate on the "invite_code" field.
func InviteCodeLTE(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLTE(FieldInviteCode, v))
}

// InviteCodeContains applies the Contains predicate on the "invite_code" field.
func InviteCodeContains(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldContains(FieldInviteCode, v))
}

// InviteCodeHasPrefix applies the HasPrefix predicate on the "invite_code" field.
func InviteCodeHasPrefix(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldHasPrefix(FieldInviteCode, v))
}

// InviteCodeHasSuffix applies the HasSuffix predicate on the "invite_code" field.
func InviteCodeHasSuffix(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldHasSuffix(FieldInviteCode, v))
}

// InviteCodeEqualFold applies the EqualFold predicate on the "invite_code" field.
func InviteCodeEqualFold(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEqualFold(FieldInviteCode, v))
}

// InviteCodeContainsFold applies the ContainsFold predicate on the "invite_code" field.
func InviteCodeContainsFold(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldContainsFold(FieldInviteCode, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldContainsFold(FieldDescription, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageIsNil applies the IsNil predicate on the "message" field.
func MessageIsNil() predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIsNull(FieldMessage))
}

// MessageNotNil applies the NotNil predicate on the "message" field.
func MessageNotNil() predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotNull(FieldMessage))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldContainsFold(FieldMessage, v))
}

// MaxUsesEQ applies the EQ predicate on the "max_uses" field.
func MaxUsesEQ(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldMaxUses, v))
}

// MaxUsesNEQ applies the NEQ predicate on the "max_uses" field.
func MaxUsesNEQ(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNEQ(FieldMaxUses, v))
}

// MaxUsesIn applies the In predicate on the "max_uses" field.
func MaxUsesIn(vs ...uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIn(FieldMaxUses, vs...))
}

// MaxUsesNotIn applies the NotIn predicate on the "max_uses" field.
func MaxUsesNotIn(vs ...uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotIn(FieldMaxUses, vs...))
}

// MaxUsesGT applies the GT predicate on the "max_uses" field.
func MaxUsesGT(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGT(FieldMaxUses, v))
}

// MaxUsesGTE applies the GTE predicate on the "max_uses" field.
func MaxUsesGTE(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGTE(FieldMaxUses, v))
}

// MaxUsesLT applies the LT predicate on the "max_uses" field.
func MaxUsesLT(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLT(FieldMaxUses, v))
}

// MaxUsesLTE applies the LTE predicate on the "max_uses" field.
func MaxUsesLTE(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLTE(FieldMaxUses, v))
}

// MaxUsesIsNil applies the IsNil predicate on the "max_uses" field.
func MaxUsesIsNil() predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIsNull(FieldMaxUses))
}

// MaxUsesNotNil applies the NotNil predicate on the "max_uses" field.
func MaxUsesNotNil() predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotNull(FieldMaxUses))
}

// UsesEQ applies the EQ predicate on the "uses" field.
func UsesEQ(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldUses, v))
}

// UsesNEQ applies the NEQ predicate on the "uses" field.
func UsesNEQ(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNEQ(FieldUses, v))
}

// UsesIn applies the In predicate on the "uses" field.
func UsesIn(vs ...uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIn(FieldUses, vs...))
}

// UsesNotIn applies the NotIn predicate on the "uses" field.
func UsesNotIn(vs ...uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotIn(FieldUses, vs...))
}

// UsesGT applies the GT predicate on the "uses" field.
func UsesGT(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGT(FieldUses, v))
}

// UsesGTE applies the GTE predicate on the "uses" field.
func UsesGTE(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGTE(FieldUses, v))
}

// UsesLT applies the LT predicate on the "uses" field.
func UsesLT(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLT(FieldUses, v))
}

// UsesLTE applies the LTE predicate on the "uses" field.
func UsesLTE(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLTE(FieldUses, v))
}

// SkipEmailVerificationEQ applies the EQ predicate on the "skip_email_verification" field.
func SkipEmailVerificationEQ(v bool) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldSkipEmailVerification, v))
}

// SkipEmailVerificationNEQ applies the NEQ predicate on the "skip_email_verification" field.
func SkipEmailVerificationNEQ(v bool) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNEQ(FieldSkipEmailVerification, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotNull(FieldExpiresAt))
}

// UsedByIsNil applies the IsNil predicate on the "used_by" field.
func UsedByIsNil() predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIsNull(FieldUsedBy))
}

// UsedByNotNil applies the NotNil predicate on the "used_by" field.
func UsedByNotNil() predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotNull(FieldUsedBy))
}

// AdminUserIDEQ applies the EQ predicate on the "admin_user_id" field.
func AdminUserIDEQ(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldAdminUserID, v))
}

// AdminUserIDNEQ applies the NEQ predicate on the "admin_user_id" field.
func AdminUserIDNEQ(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNEQ(FieldAdminUserID, v))
}

// AdminUserIDIn applies the In predicate on the "admin_user_id" field.
func AdminUserIDIn(vs ...uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIn(FieldAdminUserID, vs...))
}

// AdminUserIDNotIn applies the NotIn predicate on the "admin_user_id" field.
func AdminUserIDNotIn(vs ...uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotIn(FieldAdminUserID, vs...))
}

// AdminUserIDGT applies the GT predicate on the "admin_user_id" field.
func AdminUserIDGT(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGT(FieldAdminUserID, v))
}

// AdminUserIDGTE applies the GTE predicate on the "admin_user_id" field.
func AdminUserIDGTE(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGTE(FieldAdminUserID, v))
}

// AdminUserIDLT applies the LT predicate on the "admin_user_id" field.
func AdminUserIDLT(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLT(FieldAdminUserID, v))
}

// AdminUserIDLTE applies the LTE predicate on the "admin_user_id" field.
func AdminUserIDLTE(v uint32) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLTE(FieldAdminUserID, v))
}

// AdminUserIDIsNil applies the IsNil predicate on the "admin_user_id" field.
func AdminUserIDIsNil() predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIsNull(FieldAdminUserID))
}

// AdminUserIDNotNil applies the NotNil predicate on the "admin_user_id" field.
func AdminUserIDNotNil() predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotNull(FieldAdminUserID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AdminInvite {
	return predicate.AdminInvite(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminInvite) predicate.AdminInvite {
	return predicate.AdminInvite(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminInvite) predicate.AdminInvite {
	return predicate.AdminInvite(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminInvite) predicate.AdminInvite {
	return predicate.AdminInvite(sql.NotPredicates(p))
}
