// Code generated by ent, DO NOT EDIT.

package hashtag

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"glintfed.org/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldSlug, v))
}

// CanTrend applies equality check predicate on the "can_trend" field. It's identical to CanTrendEQ.
func CanTrend(v bool) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldCanTrend, v))
}

// CanSearch applies equality check predicate on the "can_search" field. It's identical to CanSearchEQ.
func CanSearch(v bool) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldCanSearch, v))
}

// IsNsfw applies equality check predicate on the "is_nsfw" field. It's identical to IsNsfwEQ.
func IsNsfw(v bool) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldIsNsfw, v))
}

// IsBanned applies equality check predicate on the "is_banned" field. It's identical to IsBannedEQ.
func IsBanned(v bool) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldIsBanned, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldUpdatedAt, v))
}

// CachedCount applies equality check predicate on the "cached_count" field. It's identical to CachedCountEQ.
func CachedCount(v uint32) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldCachedCount, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldContainsFold(FieldSlug, v))
}

// CanTrendEQ applies the EQ predicate on the "can_trend" field.
func CanTrendEQ(v bool) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldCanTrend, v))
}

// CanTrendNEQ applies the NEQ predicate on the "can_trend" field.
func CanTrendNEQ(v bool) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNEQ(FieldCanTrend, v))
}

// CanTrendIsNil applies the IsNil predicate on the "can_trend" field.
func CanTrendIsNil() predicate.Hashtag {
	return predicate.Hashtag(sql.FieldIsNull(FieldCanTrend))
}

// CanTrendNotNil applies the NotNil predicate on the "can_trend" field.
func CanTrendNotNil() predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNotNull(FieldCanTrend))
}

// CanSearchEQ applies the EQ predicate on the "can_search" field.
func CanSearchEQ(v bool) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldCanSearch, v))
}

// CanSearchNEQ applies the NEQ predicate on the "can_search" field.
func CanSearchNEQ(v bool) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNEQ(FieldCanSearch, v))
}

// CanSearchIsNil applies the IsNil predicate on the "can_search" field.
func CanSearchIsNil() predicate.Hashtag {
	return predicate.Hashtag(sql.FieldIsNull(FieldCanSearch))
}

// CanSearchNotNil applies the NotNil predicate on the "can_search" field.
func CanSearchNotNil() predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNotNull(FieldCanSearch))
}

// IsNsfwEQ applies the EQ predicate on the "is_nsfw" field.
func IsNsfwEQ(v bool) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldIsNsfw, v))
}

// IsNsfwNEQ applies the NEQ predicate on the "is_nsfw" field.
func IsNsfwNEQ(v bool) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNEQ(FieldIsNsfw, v))
}

// IsBannedEQ applies the EQ predicate on the "is_banned" field.
func IsBannedEQ(v bool) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldIsBanned, v))
}

// IsBannedNEQ applies the NEQ predicate on the "is_banned" field.
func IsBannedNEQ(v bool) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNEQ(FieldIsBanned, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldLTE(FieldUpdatedAt, v))
}

// CachedCountEQ applies the EQ predicate on the "cached_count" field.
func CachedCountEQ(v uint32) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldEQ(FieldCachedCount, v))
}

// CachedCountNEQ applies the NEQ predicate on the "cached_count" field.
func CachedCountNEQ(v uint32) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNEQ(FieldCachedCount, v))
}

// CachedCountIn applies the In predicate on the "cached_count" field.
func CachedCountIn(vs ...uint32) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldIn(FieldCachedCount, vs...))
}

// CachedCountNotIn applies the NotIn predicate on the "cached_count" field.
func CachedCountNotIn(vs ...uint32) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNotIn(FieldCachedCount, vs...))
}

// CachedCountGT applies the GT predicate on the "cached_count" field.
func CachedCountGT(v uint32) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldGT(FieldCachedCount, v))
}

// CachedCountGTE applies the GTE predicate on the "cached_count" field.
func CachedCountGTE(v uint32) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldGTE(FieldCachedCount, v))
}

// CachedCountLT applies the LT predicate on the "cached_count" field.
func CachedCountLT(v uint32) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldLT(FieldCachedCount, v))
}

// CachedCountLTE applies the LTE predicate on the "cached_count" field.
func CachedCountLTE(v uint32) predicate.Hashtag {
	return predicate.Hashtag(sql.FieldLTE(FieldCachedCount, v))
}

// CachedCountIsNil applies the IsNil predicate on the "cached_count" field.
func CachedCountIsNil() predicate.Hashtag {
	return predicate.Hashtag(sql.FieldIsNull(FieldCachedCount))
}

// CachedCountNotNil applies the NotNil predicate on the "cached_count" field.
func CachedCountNotNil() predicate.Hashtag {
	return predicate.Hashtag(sql.FieldNotNull(FieldCachedCount))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Hashtag) predicate.Hashtag {
	return predicate.Hashtag(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Hashtag) predicate.Hashtag {
	return predicate.Hashtag(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Hashtag) predicate.Hashtag {
	return predicate.Hashtag(sql.NotPredicates(p))
}
