// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package appregister

import (
	"context"
	"sync"
)

// Ensure, that AppRegisterModelMock does implement AppRegisterModel.
// If this is not the case, regenerate this file with moq.
var _ AppRegisterModel = &AppRegisterModelMock{}

// AppRegisterModelMock is a mock implementation of AppRegisterModel.
//
//	func TestSomethingThatUsesAppRegisterModel(t *testing.T) {
//
//		// make and configure a mocked AppRegisterModel
//		mockedAppRegisterModel := &AppRegisterModelMock{
//			DeleteByEmailFunc: func(ctx context.Context, email string) error {
//				panic("mock out the DeleteByEmail method")
//			},
//			VerifyCodeExistsFunc: func(ctx context.Context, email string, code string) (bool, error) {
//				panic("mock out the VerifyCodeExists method")
//			},
//		}
//
//		// use mockedAppRegisterModel in code that requires AppRegisterModel
//		// and then make assertions.
//
//	}
type AppRegisterModelMock struct {
	// DeleteByEmailFunc mocks the DeleteByEmail method.
	DeleteByEmailFunc func(ctx context.Context, email string) error

	// VerifyCodeExistsFunc mocks the VerifyCodeExists method.
	VerifyCodeExistsFunc func(ctx context.Context, email string, code string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteByEmail holds details about calls to the DeleteByEmail method.
		DeleteByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// VerifyCodeExists holds details about calls to the VerifyCodeExists method.
		VerifyCodeExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
			// Code is the code argument value.
			Code string
		}
	}
	lockDeleteByEmail    sync.RWMutex
	lockVerifyCodeExists sync.RWMutex
}

// DeleteByEmail calls DeleteByEmailFunc.
func (mock *AppRegisterModelMock) DeleteByEmail(ctx context.Context, email string) error {
	if mock.DeleteByEmailFunc == nil {
		panic("AppRegisterModelMock.DeleteByEmailFunc: method is nil but AppRegisterModel.DeleteByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockDeleteByEmail.Lock()
	mock.calls.DeleteByEmail = append(mock.calls.DeleteByEmail, callInfo)
	mock.lockDeleteByEmail.Unlock()
	return mock.DeleteByEmailFunc(ctx, email)
}

// DeleteByEmailCalls gets all the calls that were made to DeleteByEmail.
// Check the length with:
//
//	len(mockedAppRegisterModel.DeleteByEmailCalls())
func (mock *AppRegisterModelMock) DeleteByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockDeleteByEmail.RLock()
	calls = mock.calls.DeleteByEmail
	mock.lockDeleteByEmail.RUnlock()
	return calls
}

// VerifyCodeExists calls VerifyCodeExistsFunc.
func (mock *AppRegisterModelMock) VerifyCodeExists(ctx context.Context, email string, code string) (bool, error) {
	if mock.VerifyCodeExistsFunc == nil {
		panic("AppRegisterModelMock.VerifyCodeExistsFunc: method is nil but AppRegisterModel.VerifyCodeExists was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
		Code  string
	}{
		Ctx:   ctx,
		Email: email,
		Code:  code,
	}
	mock.lockVerifyCodeExists.Lock()
	mock.calls.VerifyCodeExists = append(mock.calls.VerifyCodeExists, callInfo)
	mock.lockVerifyCodeExists.Unlock()
	return mock.VerifyCodeExistsFunc(ctx, email, code)
}

// VerifyCodeExistsCalls gets all the calls that were made to VerifyCodeExists.
// Check the length with:
//
//	len(mockedAppRegisterModel.VerifyCodeExistsCalls())
func (mock *AppRegisterModelMock) VerifyCodeExistsCalls() []struct {
	Ctx   context.Context
	Email string
	Code  string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
		Code  string
	}
	mock.lockVerifyCodeExists.RLock()
	calls = mock.calls.VerifyCodeExists
	mock.lockVerifyCodeExists.RUnlock()
	return calls
}
