// Code generated by ent, DO NOT EDIT.

package place

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"glintfed.org/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.Place {
	return predicate.Place(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.Place {
	return predicate.Place(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.Place {
	return predicate.Place(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.Place {
	return predicate.Place(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.Place {
	return predicate.Place(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.Place {
	return predicate.Place(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.Place {
	return predicate.Place(sql.FieldLTE(FieldID, id))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldSlug, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldName, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldState, v))
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldCountry, v))
}

// Lat applies equality check predicate on the "lat" field. It's identical to LatEQ.
func Lat(v float64) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldLat, v))
}

// Long applies equality check predicate on the "long" field. It's identical to LongEQ.
func Long(v float64) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldLong, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v int8) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldScore, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldUpdatedAt, v))
}

// CachedPostCount applies equality check predicate on the "cached_post_count" field. It's identical to CachedPostCountEQ.
func CachedPostCount(v uint64) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldCachedPostCount, v))
}

// LastCheckedAt applies equality check predicate on the "last_checked_at" field. It's identical to LastCheckedAtEQ.
func LastCheckedAt(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldLastCheckedAt, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Place {
	return predicate.Place(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Place {
	return predicate.Place(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Place {
	return predicate.Place(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Place {
	return predicate.Place(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Place {
	return predicate.Place(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Place {
	return predicate.Place(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Place {
	return predicate.Place(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Place {
	return predicate.Place(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Place {
	return predicate.Place(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Place {
	return predicate.Place(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Place {
	return predicate.Place(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Place {
	return predicate.Place(sql.FieldContainsFold(FieldSlug, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Place {
	return predicate.Place(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Place {
	return predicate.Place(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Place {
	return predicate.Place(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Place {
	return predicate.Place(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Place {
	return predicate.Place(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Place {
	return predicate.Place(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Place {
	return predicate.Place(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Place {
	return predicate.Place(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Place {
	return predicate.Place(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Place {
	return predicate.Place(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Place {
	return predicate.Place(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Place {
	return predicate.Place(sql.FieldContainsFold(FieldName, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.Place {
	return predicate.Place(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.Place {
	return predicate.Place(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.Place {
	return predicate.Place(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.Place {
	return predicate.Place(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.Place {
	return predicate.Place(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.Place {
	return predicate.Place(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.Place {
	return predicate.Place(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.Place {
	return predicate.Place(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.Place {
	return predicate.Place(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.Place {
	return predicate.Place(sql.FieldHasSuffix(FieldState, v))
}

// StateIsNil applies the IsNil predicate on the "state" field.
func StateIsNil() predicate.Place {
	return predicate.Place(sql.FieldIsNull(FieldState))
}

// StateNotNil applies the NotNil predicate on the "state" field.
func StateNotNil() predicate.Place {
	return predicate.Place(sql.FieldNotNull(FieldState))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.Place {
	return predicate.Place(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.Place {
	return predicate.Place(sql.FieldContainsFold(FieldState, v))
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldCountry, v))
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.Place {
	return predicate.Place(sql.FieldNEQ(FieldCountry, v))
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.Place {
	return predicate.Place(sql.FieldIn(FieldCountry, vs...))
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.Place {
	return predicate.Place(sql.FieldNotIn(FieldCountry, vs...))
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.Place {
	return predicate.Place(sql.FieldGT(FieldCountry, v))
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.Place {
	return predicate.Place(sql.FieldGTE(FieldCountry, v))
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.Place {
	return predicate.Place(sql.FieldLT(FieldCountry, v))
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.Place {
	return predicate.Place(sql.FieldLTE(FieldCountry, v))
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.Place {
	return predicate.Place(sql.FieldContains(FieldCountry, v))
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.Place {
	return predicate.Place(sql.FieldHasPrefix(FieldCountry, v))
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.Place {
	return predicate.Place(sql.FieldHasSuffix(FieldCountry, v))
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.Place {
	return predicate.Place(sql.FieldEqualFold(FieldCountry, v))
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.Place {
	return predicate.Place(sql.FieldContainsFold(FieldCountry, v))
}

// AliasesIsNil applies the IsNil predicate on the "aliases" field.
func AliasesIsNil() predicate.Place {
	return predicate.Place(sql.FieldIsNull(FieldAliases))
}

// AliasesNotNil applies the NotNil predicate on the "aliases" field.
func AliasesNotNil() predicate.Place {
	return predicate.Place(sql.FieldNotNull(FieldAliases))
}

// LatEQ applies the EQ predicate on the "lat" field.
func LatEQ(v float64) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldLat, v))
}

// LatNEQ applies the NEQ predicate on the "lat" field.
func LatNEQ(v float64) predicate.Place {
	return predicate.Place(sql.FieldNEQ(FieldLat, v))
}

// LatIn applies the In predicate on the "lat" field.
func LatIn(vs ...float64) predicate.Place {
	return predicate.Place(sql.FieldIn(FieldLat, vs...))
}

// LatNotIn applies the NotIn predicate on the "lat" field.
func LatNotIn(vs ...float64) predicate.Place {
	return predicate.Place(sql.FieldNotIn(FieldLat, vs...))
}

// LatGT applies the GT predicate on the "lat" field.
func LatGT(v float64) predicate.Place {
	return predicate.Place(sql.FieldGT(FieldLat, v))
}

// LatGTE applies the GTE predicate on the "lat" field.
func LatGTE(v float64) predicate.Place {
	return predicate.Place(sql.FieldGTE(FieldLat, v))
}

// LatLT applies the LT predicate on the "lat" field.
func LatLT(v float64) predicate.Place {
	return predicate.Place(sql.FieldLT(FieldLat, v))
}

// LatLTE applies the LTE predicate on the "lat" field.
func LatLTE(v float64) predicate.Place {
	return predicate.Place(sql.FieldLTE(FieldLat, v))
}

// LatIsNil applies the IsNil predicate on the "lat" field.
func LatIsNil() predicate.Place {
	return predicate.Place(sql.FieldIsNull(FieldLat))
}

// LatNotNil applies the NotNil predicate on the "lat" field.
func LatNotNil() predicate.Place {
	return predicate.Place(sql.FieldNotNull(FieldLat))
}

// LongEQ applies the EQ predicate on the "long" field.
func LongEQ(v float64) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldLong, v))
}

// LongNEQ applies the NEQ predicate on the "long" field.
func LongNEQ(v float64) predicate.Place {
	return predicate.Place(sql.FieldNEQ(FieldLong, v))
}

// LongIn applies the In predicate on the "long" field.
func LongIn(vs ...float64) predicate.Place {
	return predicate.Place(sql.FieldIn(FieldLong, vs...))
}

// LongNotIn applies the NotIn predicate on the "long" field.
func LongNotIn(vs ...float64) predicate.Place {
	return predicate.Place(sql.FieldNotIn(FieldLong, vs...))
}

// LongGT applies the GT predicate on the "long" field.
func LongGT(v float64) predicate.Place {
	return predicate.Place(sql.FieldGT(FieldLong, v))
}

// LongGTE applies the GTE predicate on the "long" field.
func LongGTE(v float64) predicate.Place {
	return predicate.Place(sql.FieldGTE(FieldLong, v))
}

// LongLT applies the LT predicate on the "long" field.
func LongLT(v float64) predicate.Place {
	return predicate.Place(sql.FieldLT(FieldLong, v))
}

// LongLTE applies the LTE predicate on the "long" field.
func LongLTE(v float64) predicate.Place {
	return predicate.Place(sql.FieldLTE(FieldLong, v))
}

// LongIsNil applies the IsNil predicate on the "long" field.
func LongIsNil() predicate.Place {
	return predicate.Place(sql.FieldIsNull(FieldLong))
}

// LongNotNil applies the NotNil predicate on the "long" field.
func LongNotNil() predicate.Place {
	return predicate.Place(sql.FieldNotNull(FieldLong))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v int8) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v int8) predicate.Place {
	return predicate.Place(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...int8) predicate.Place {
	return predicate.Place(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...int8) predicate.Place {
	return predicate.Place(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v int8) predicate.Place {
	return predicate.Place(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v int8) predicate.Place {
	return predicate.Place(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v int8) predicate.Place {
	return predicate.Place(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v int8) predicate.Place {
	return predicate.Place(sql.FieldLTE(FieldScore, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Place {
	return predicate.Place(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Place {
	return predicate.Place(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Place {
	return predicate.Place(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Place {
	return predicate.Place(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldLTE(FieldUpdatedAt, v))
}

// CachedPostCountEQ applies the EQ predicate on the "cached_post_count" field.
func CachedPostCountEQ(v uint64) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldCachedPostCount, v))
}

// CachedPostCountNEQ applies the NEQ predicate on the "cached_post_count" field.
func CachedPostCountNEQ(v uint64) predicate.Place {
	return predicate.Place(sql.FieldNEQ(FieldCachedPostCount, v))
}

// CachedPostCountIn applies the In predicate on the "cached_post_count" field.
func CachedPostCountIn(vs ...uint64) predicate.Place {
	return predicate.Place(sql.FieldIn(FieldCachedPostCount, vs...))
}

// CachedPostCountNotIn applies the NotIn predicate on the "cached_post_count" field.
func CachedPostCountNotIn(vs ...uint64) predicate.Place {
	return predicate.Place(sql.FieldNotIn(FieldCachedPostCount, vs...))
}

// CachedPostCountGT applies the GT predicate on the "cached_post_count" field.
func CachedPostCountGT(v uint64) predicate.Place {
	return predicate.Place(sql.FieldGT(FieldCachedPostCount, v))
}

// CachedPostCountGTE applies the GTE predicate on the "cached_post_count" field.
func CachedPostCountGTE(v uint64) predicate.Place {
	return predicate.Place(sql.FieldGTE(FieldCachedPostCount, v))
}

// CachedPostCountLT applies the LT predicate on the "cached_post_count" field.
func CachedPostCountLT(v uint64) predicate.Place {
	return predicate.Place(sql.FieldLT(FieldCachedPostCount, v))
}

// CachedPostCountLTE applies the LTE predicate on the "cached_post_count" field.
func CachedPostCountLTE(v uint64) predicate.Place {
	return predicate.Place(sql.FieldLTE(FieldCachedPostCount, v))
}

// CachedPostCountIsNil applies the IsNil predicate on the "cached_post_count" field.
func CachedPostCountIsNil() predicate.Place {
	return predicate.Place(sql.FieldIsNull(FieldCachedPostCount))
}

// CachedPostCountNotNil applies the NotNil predicate on the "cached_post_count" field.
func CachedPostCountNotNil() predicate.Place {
	return predicate.Place(sql.FieldNotNull(FieldCachedPostCount))
}

// LastCheckedAtEQ applies the EQ predicate on the "last_checked_at" field.
func LastCheckedAtEQ(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtNEQ applies the NEQ predicate on the "last_checked_at" field.
func LastCheckedAtNEQ(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldNEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtIn applies the In predicate on the "last_checked_at" field.
func LastCheckedAtIn(vs ...time.Time) predicate.Place {
	return predicate.Place(sql.FieldIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtNotIn applies the NotIn predicate on the "last_checked_at" field.
func LastCheckedAtNotIn(vs ...time.Time) predicate.Place {
	return predicate.Place(sql.FieldNotIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtGT applies the GT predicate on the "last_checked_at" field.
func LastCheckedAtGT(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldGT(FieldLastCheckedAt, v))
}

// LastCheckedAtGTE applies the GTE predicate on the "last_checked_at" field.
func LastCheckedAtGTE(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldGTE(FieldLastCheckedAt, v))
}

// LastCheckedAtLT applies the LT predicate on the "last_checked_at" field.
func LastCheckedAtLT(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldLT(FieldLastCheckedAt, v))
}

// LastCheckedAtLTE applies the LTE predicate on the "last_checked_at" field.
func LastCheckedAtLTE(v time.Time) predicate.Place {
	return predicate.Place(sql.FieldLTE(FieldLastCheckedAt, v))
}

// LastCheckedAtIsNil applies the IsNil predicate on the "last_checked_at" field.
func LastCheckedAtIsNil() predicate.Place {
	return predicate.Place(sql.FieldIsNull(FieldLastCheckedAt))
}

// LastCheckedAtNotNil applies the NotNil predicate on the "last_checked_at" field.
func LastCheckedAtNotNil() predicate.Place {
	return predicate.Place(sql.FieldNotNull(FieldLastCheckedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Place) predicate.Place {
	return predicate.Place(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Place) predicate.Place {
	return predicate.Place(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Place) predicate.Place {
	return predicate.Place(sql.NotPredicates(p))
}
