// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/adminshadowfilter"
)

// AdminShadowFilterCreate is the builder for creating a AdminShadowFilter entity.
type AdminShadowFilterCreate struct {
	config
	mutation *AdminShadowFilterMutation
	hooks    []Hook
}

// SetAdminID sets the "admin_id" field.
func (_c *AdminShadowFilterCreate) SetAdminID(v uint64) *AdminShadowFilterCreate {
	_c.mutation.SetAdminID(v)
	return _c
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableAdminID(v *uint64) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetAdminID(*v)
	}
	return _c
}

// SetItemType sets the "item_type" field.
func (_c *AdminShadowFilterCreate) SetItemType(v string) *AdminShadowFilterCreate {
	_c.mutation.SetItemType(v)
	return _c
}

// SetItemID sets the "item_id" field.
func (_c *AdminShadowFilterCreate) SetItemID(v uint64) *AdminShadowFilterCreate {
	_c.mutation.SetItemID(v)
	return _c
}

// SetIsLocal sets the "is_local" field.
func (_c *AdminShadowFilterCreate) SetIsLocal(v bool) *AdminShadowFilterCreate {
	_c.mutation.SetIsLocal(v)
	return _c
}

// SetNillableIsLocal sets the "is_local" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableIsLocal(v *bool) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetIsLocal(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *AdminShadowFilterCreate) SetNote(v string) *AdminShadowFilterCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableNote(v *string) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *AdminShadowFilterCreate) SetActive(v bool) *AdminShadowFilterCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableActive(v *bool) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetHistory sets the "history" field.
func (_c *AdminShadowFilterCreate) SetHistory(v []interface{}) *AdminShadowFilterCreate {
	_c.mutation.SetHistory(v)
	return _c
}

// SetRuleset sets the "ruleset" field.
func (_c *AdminShadowFilterCreate) SetRuleset(v map[string]interface{}) *AdminShadowFilterCreate {
	_c.mutation.SetRuleset(v)
	return _c
}

// SetPreventApFanout sets the "prevent_ap_fanout" field.
func (_c *AdminShadowFilterCreate) SetPreventApFanout(v bool) *AdminShadowFilterCreate {
	_c.mutation.SetPreventApFanout(v)
	return _c
}

// SetNillablePreventApFanout sets the "prevent_ap_fanout" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillablePreventApFanout(v *bool) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetPreventApFanout(*v)
	}
	return _c
}

// SetPreventNewDms sets the "prevent_new_dms" field.
func (_c *AdminShadowFilterCreate) SetPreventNewDms(v bool) *AdminShadowFilterCreate {
	_c.mutation.SetPreventNewDms(v)
	return _c
}

// SetNillablePreventNewDms sets the "prevent_new_dms" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillablePreventNewDms(v *bool) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetPreventNewDms(*v)
	}
	return _c
}

// SetIgnoreReports sets the "ignore_reports" field.
func (_c *AdminShadowFilterCreate) SetIgnoreReports(v bool) *AdminShadowFilterCreate {
	_c.mutation.SetIgnoreReports(v)
	return _c
}

// SetNillableIgnoreReports sets the "ignore_reports" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableIgnoreReports(v *bool) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetIgnoreReports(*v)
	}
	return _c
}

// SetIgnoreMentions sets the "ignore_mentions" field.
func (_c *AdminShadowFilterCreate) SetIgnoreMentions(v bool) *AdminShadowFilterCreate {
	_c.mutation.SetIgnoreMentions(v)
	return _c
}

// SetNillableIgnoreMentions sets the "ignore_mentions" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableIgnoreMentions(v *bool) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetIgnoreMentions(*v)
	}
	return _c
}

// SetIgnoreLinks sets the "ignore_links" field.
func (_c *AdminShadowFilterCreate) SetIgnoreLinks(v bool) *AdminShadowFilterCreate {
	_c.mutation.SetIgnoreLinks(v)
	return _c
}

// SetNillableIgnoreLinks sets the "ignore_links" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableIgnoreLinks(v *bool) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetIgnoreLinks(*v)
	}
	return _c
}

// SetIgnoreHashtags sets the "ignore_hashtags" field.
func (_c *AdminShadowFilterCreate) SetIgnoreHashtags(v bool) *AdminShadowFilterCreate {
	_c.mutation.SetIgnoreHashtags(v)
	return _c
}

// SetNillableIgnoreHashtags sets the "ignore_hashtags" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableIgnoreHashtags(v *bool) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetIgnoreHashtags(*v)
	}
	return _c
}

// SetHideFromPublicFeeds sets the "hide_from_public_feeds" field.
func (_c *AdminShadowFilterCreate) SetHideFromPublicFeeds(v bool) *AdminShadowFilterCreate {
	_c.mutation.SetHideFromPublicFeeds(v)
	return _c
}

// SetNillableHideFromPublicFeeds sets the "hide_from_public_feeds" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableHideFromPublicFeeds(v *bool) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetHideFromPublicFeeds(*v)
	}
	return _c
}

// SetHideFromTagFeeds sets the "hide_from_tag_feeds" field.
func (_c *AdminShadowFilterCreate) SetHideFromTagFeeds(v bool) *AdminShadowFilterCreate {
	_c.mutation.SetHideFromTagFeeds(v)
	return _c
}

// SetNillableHideFromTagFeeds sets the "hide_from_tag_feeds" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableHideFromTagFeeds(v *bool) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetHideFromTagFeeds(*v)
	}
	return _c
}

// SetHideEmbeds sets the "hide_embeds" field.
func (_c *AdminShadowFilterCreate) SetHideEmbeds(v bool) *AdminShadowFilterCreate {
	_c.mutation.SetHideEmbeds(v)
	return _c
}

// SetNillableHideEmbeds sets the "hide_embeds" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableHideEmbeds(v *bool) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetHideEmbeds(*v)
	}
	return _c
}

// SetHideFromStoryCarousel sets the "hide_from_story_carousel" field.
func (_c *AdminShadowFilterCreate) SetHideFromStoryCarousel(v bool) *AdminShadowFilterCreate {
	_c.mutation.SetHideFromStoryCarousel(v)
	return _c
}

// SetNillableHideFromStoryCarousel sets the "hide_from_story_carousel" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableHideFromStoryCarousel(v *bool) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetHideFromStoryCarousel(*v)
	}
	return _c
}

// SetHideFromSearchAutocomplete sets the "hide_from_search_autocomplete" field.
func (_c *AdminShadowFilterCreate) SetHideFromSearchAutocomplete(v bool) *AdminShadowFilterCreate {
	_c.mutation.SetHideFromSearchAutocomplete(v)
	return _c
}

// SetNillableHideFromSearchAutocomplete sets the "hide_from_search_autocomplete" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableHideFromSearchAutocomplete(v *bool) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetHideFromSearchAutocomplete(*v)
	}
	return _c
}

// SetHideFromSearch sets the "hide_from_search" field.
func (_c *AdminShadowFilterCreate) SetHideFromSearch(v bool) *AdminShadowFilterCreate {
	_c.mutation.SetHideFromSearch(v)
	return _c
}

// SetNillableHideFromSearch sets the "hide_from_search" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableHideFromSearch(v *bool) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetHideFromSearch(*v)
	}
	return _c
}

// SetRequiresLogin sets the "requires_login" field.
func (_c *AdminShadowFilterCreate) SetRequiresLogin(v bool) *AdminShadowFilterCreate {
	_c.mutation.SetRequiresLogin(v)
	return _c
}

// SetNillableRequiresLogin sets the "requires_login" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableRequiresLogin(v *bool) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetRequiresLogin(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdminShadowFilterCreate) SetCreatedAt(v time.Time) *AdminShadowFilterCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableCreatedAt(v *time.Time) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AdminShadowFilterCreate) SetUpdatedAt(v time.Time) *AdminShadowFilterCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AdminShadowFilterCreate) SetNillableUpdatedAt(v *time.Time) *AdminShadowFilterCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AdminShadowFilterCreate) SetID(v uint64) *AdminShadowFilterCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AdminShadowFilterMutation object of the builder.
func (_c *AdminShadowFilterCreate) Mutation() *AdminShadowFilterMutation {
	return _c.mutation
}

// Save creates the AdminShadowFilter in the database.
func (_c *AdminShadowFilterCreate) Save(ctx context.Context) (*AdminShadowFilter, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdminShadowFilterCreate) SaveX(ctx context.Context) *AdminShadowFilter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminShadowFilterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminShadowFilterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdminShadowFilterCreate) defaults() {
	if _, ok := _c.mutation.IsLocal(); !ok {
		v := adminshadowfilter.DefaultIsLocal
		_c.mutation.SetIsLocal(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := adminshadowfilter.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.PreventApFanout(); !ok {
		v := adminshadowfilter.DefaultPreventApFanout
		_c.mutation.SetPreventApFanout(v)
	}
	if _, ok := _c.mutation.PreventNewDms(); !ok {
		v := adminshadowfilter.DefaultPreventNewDms
		_c.mutation.SetPreventNewDms(v)
	}
	if _, ok := _c.mutation.IgnoreReports(); !ok {
		v := adminshadowfilter.DefaultIgnoreReports
		_c.mutation.SetIgnoreReports(v)
	}
	if _, ok := _c.mutation.IgnoreMentions(); !ok {
		v := adminshadowfilter.DefaultIgnoreMentions
		_c.mutation.SetIgnoreMentions(v)
	}
	if _, ok := _c.mutation.IgnoreLinks(); !ok {
		v := adminshadowfilter.DefaultIgnoreLinks
		_c.mutation.SetIgnoreLinks(v)
	}
	if _, ok := _c.mutation.IgnoreHashtags(); !ok {
		v := adminshadowfilter.DefaultIgnoreHashtags
		_c.mutation.SetIgnoreHashtags(v)
	}
	if _, ok := _c.mutation.HideFromPublicFeeds(); !ok {
		v := adminshadowfilter.DefaultHideFromPublicFeeds
		_c.mutation.SetHideFromPublicFeeds(v)
	}
	if _, ok := _c.mutation.HideFromTagFeeds(); !ok {
		v := adminshadowfilter.DefaultHideFromTagFeeds
		_c.mutation.SetHideFromTagFeeds(v)
	}
	if _, ok := _c.mutation.HideEmbeds(); !ok {
		v := adminshadowfilter.DefaultHideEmbeds
		_c.mutation.SetHideEmbeds(v)
	}
	if _, ok := _c.mutation.HideFromStoryCarousel(); !ok {
		v := adminshadowfilter.DefaultHideFromStoryCarousel
		_c.mutation.SetHideFromStoryCarousel(v)
	}
	if _, ok := _c.mutation.HideFromSearchAutocomplete(); !ok {
		v := adminshadowfilter.DefaultHideFromSearchAutocomplete
		_c.mutation.SetHideFromSearchAutocomplete(v)
	}
	if _, ok := _c.mutation.HideFromSearch(); !ok {
		v := adminshadowfilter.DefaultHideFromSearch
		_c.mutation.SetHideFromSearch(v)
	}
	if _, ok := _c.mutation.RequiresLogin(); !ok {
		v := adminshadowfilter.DefaultRequiresLogin
		_c.mutation.SetRequiresLogin(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := adminshadowfilter.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := adminshadowfilter.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdminShadowFilterCreate) check() error {
	if _, ok := _c.mutation.ItemType(); !ok {
		return &ValidationError{Name: "item_type", err: errors.New(`ent: missing required field "AdminShadowFilter.item_type"`)}
	}
	if _, ok := _c.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item_id", err: errors.New(`ent: missing required field "AdminShadowFilter.item_id"`)}
	}
	if _, ok := _c.mutation.IsLocal(); !ok {
		return &ValidationError{Name: "is_local", err: errors.New(`ent: missing required field "AdminShadowFilter.is_local"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "AdminShadowFilter.active"`)}
	}
	if _, ok := _c.mutation.PreventApFanout(); !ok {
		return &ValidationError{Name: "prevent_ap_fanout", err: errors.New(`ent: missing required field "AdminShadowFilter.prevent_ap_fanout"`)}
	}
	if _, ok := _c.mutation.PreventNewDms(); !ok {
		return &ValidationError{Name: "prevent_new_dms", err: errors.New(`ent: missing required field "AdminShadowFilter.prevent_new_dms"`)}
	}
	if _, ok := _c.mutation.IgnoreReports(); !ok {
		return &ValidationError{Name: "ignore_reports", err: errors.New(`ent: missing required field "AdminShadowFilter.ignore_reports"`)}
	}
	if _, ok := _c.mutation.IgnoreMentions(); !ok {
		return &ValidationError{Name: "ignore_mentions", err: errors.New(`ent: missing required field "AdminShadowFilter.ignore_mentions"`)}
	}
	if _, ok := _c.mutation.IgnoreLinks(); !ok {
		return &ValidationError{Name: "ignore_links", err: errors.New(`ent: missing required field "AdminShadowFilter.ignore_links"`)}
	}
	if _, ok := _c.mutation.IgnoreHashtags(); !ok {
		return &ValidationError{Name: "ignore_hashtags", err: errors.New(`ent: missing required field "AdminShadowFilter.ignore_hashtags"`)}
	}
	if _, ok := _c.mutation.HideFromPublicFeeds(); !ok {
		return &ValidationError{Name: "hide_from_public_feeds", err: errors.New(`ent: missing required field "AdminShadowFilter.hide_from_public_feeds"`)}
	}
	if _, ok := _c.mutation.HideFromTagFeeds(); !ok {
		return &ValidationError{Name: "hide_from_tag_feeds", err: errors.New(`ent: missing required field "AdminShadowFilter.hide_from_tag_feeds"`)}
	}
	if _, ok := _c.mutation.HideEmbeds(); !ok {
		return &ValidationError{Name: "hide_embeds", err: errors.New(`ent: missing required field "AdminShadowFilter.hide_embeds"`)}
	}
	if _, ok := _c.mutation.HideFromStoryCarousel(); !ok {
		return &ValidationError{Name: "hide_from_story_carousel", err: errors.New(`ent: missing required field "AdminShadowFilter.hide_from_story_carousel"`)}
	}
	if _, ok := _c.mutation.HideFromSearchAutocomplete(); !ok {
		return &ValidationError{Name: "hide_from_search_autocomplete", err: errors.New(`ent: missing required field "AdminShadowFilter.hide_from_search_autocomplete"`)}
	}
	if _, ok := _c.mutation.HideFromSearch(); !ok {
		return &ValidationError{Name: "hide_from_search", err: errors.New(`ent: missing required field "AdminShadowFilter.hide_from_search"`)}
	}
	if _, ok := _c.mutation.RequiresLogin(); !ok {
		return &ValidationError{Name: "requires_login", err: errors.New(`ent: missing required field "AdminShadowFilter.requires_login"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminShadowFilter.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AdminShadowFilter.updated_at"`)}
	}
	return nil
}

func (_c *AdminShadowFilterCreate) sqlSave(ctx context.Context) (*AdminShadowFilter, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdminShadowFilterCreate) createSpec() (*AdminShadowFilter, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminShadowFilter{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adminshadowfilter.Table, sqlgraph.NewFieldSpec(adminshadowfilter.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AdminID(); ok {
		_spec.SetField(adminshadowfilter.FieldAdminID, field.TypeUint64, value)
		_node.AdminID = value
	}
	if value, ok := _c.mutation.ItemType(); ok {
		_spec.SetField(adminshadowfilter.FieldItemType, field.TypeString, value)
		_node.ItemType = value
	}
	if value, ok := _c.mutation.ItemID(); ok {
		_spec.SetField(adminshadowfilter.FieldItemID, field.TypeUint64, value)
		_node.ItemID = value
	}
	if value, ok := _c.mutation.IsLocal(); ok {
		_spec.SetField(adminshadowfilter.FieldIsLocal, field.TypeBool, value)
		_node.IsLocal = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(adminshadowfilter.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(adminshadowfilter.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.History(); ok {
		_spec.SetField(adminshadowfilter.FieldHistory, field.TypeJSON, value)
		_node.History = value
	}
	if value, ok := _c.mutation.Ruleset(); ok {
		_spec.SetField(adminshadowfilter.FieldRuleset, field.TypeJSON, value)
		_node.Ruleset = value
	}
	if value, ok := _c.mutation.PreventApFanout(); ok {
		_spec.SetField(adminshadowfilter.FieldPreventApFanout, field.TypeBool, value)
		_node.PreventApFanout = value
	}
	if value, ok := _c.mutation.PreventNewDms(); ok {
		_spec.SetField(adminshadowfilter.FieldPreventNewDms, field.TypeBool, value)
		_node.PreventNewDms = value
	}
	if value, ok := _c.mutation.IgnoreReports(); ok {
		_spec.SetField(adminshadowfilter.FieldIgnoreReports, field.TypeBool, value)
		_node.IgnoreReports = value
	}
	if value, ok := _c.mutation.IgnoreMentions(); ok {
		_spec.SetField(adminshadowfilter.FieldIgnoreMentions, field.TypeBool, value)
		_node.IgnoreMentions = value
	}
	if value, ok := _c.mutation.IgnoreLinks(); ok {
		_spec.SetField(adminshadowfilter.FieldIgnoreLinks, field.TypeBool, value)
		_node.IgnoreLinks = value
	}
	if value, ok := _c.mutation.IgnoreHashtags(); ok {
		_spec.SetField(adminshadowfilter.FieldIgnoreHashtags, field.TypeBool, value)
		_node.IgnoreHashtags = value
	}
	if value, ok := _c.mutation.HideFromPublicFeeds(); ok {
		_spec.SetField(adminshadowfilter.FieldHideFromPublicFeeds, field.TypeBool, value)
		_node.HideFromPublicFeeds = value
	}
	if value, ok := _c.mutation.HideFromTagFeeds(); ok {
		_spec.SetField(adminshadowfilter.FieldHideFromTagFeeds, field.TypeBool, value)
		_node.HideFromTagFeeds = value
	}
	if value, ok := _c.mutation.HideEmbeds(); ok {
		_spec.SetField(adminshadowfilter.FieldHideEmbeds, field.TypeBool, value)
		_node.HideEmbeds = value
	}
	if value, ok := _c.mutation.HideFromStoryCarousel(); ok {
		_spec.SetField(adminshadowfilter.FieldHideFromStoryCarousel, field.TypeBool, value)
		_node.HideFromStoryCarousel = value
	}
	if value, ok := _c.mutation.HideFromSearchAutocomplete(); ok {
		_spec.SetField(adminshadowfilter.FieldHideFromSearchAutocomplete, field.TypeBool, value)
		_node.HideFromSearchAutocomplete = value
	}
	if value, ok := _c.mutation.HideFromSearch(); ok {
		_spec.SetField(adminshadowfilter.FieldHideFromSearch, field.TypeBool, value)
		_node.HideFromSearch = value
	}
	if value, ok := _c.mutation.RequiresLogin(); ok {
		_spec.SetField(adminshadowfilter.FieldRequiresLogin, field.TypeBool, value)
		_node.RequiresLogin = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adminshadowfilter.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(adminshadowfilter.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AdminShadowFilterCreateBulk is the builder for creating many AdminShadowFilter entities in bulk.
type AdminShadowFilterCreateBulk struct {
	config
	err      error
	builders []*AdminShadowFilterCreate
}

// Save creates the AdminShadowFilter entities in the database.
func (_c *AdminShadowFilterCreateBulk) Save(ctx context.Context) ([]*AdminShadowFilter, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdminShadowFilter, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminShadowFilterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdminShadowFilterCreateBulk) SaveX(ctx context.Context) []*AdminShadowFilter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminShadowFilterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminShadowFilterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
