// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/adminshadowfilter"
	"glintfed.org/ent/predicate"
)

// AdminShadowFilterUpdate is the builder for updating AdminShadowFilter entities.
type AdminShadowFilterUpdate struct {
	config
	hooks    []Hook
	mutation *AdminShadowFilterMutation
}

// Where appends a list predicates to the AdminShadowFilterUpdate builder.
func (_u *AdminShadowFilterUpdate) Where(ps ...predicate.AdminShadowFilter) *AdminShadowFilterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAdminID sets the "admin_id" field.
func (_u *AdminShadowFilterUpdate) SetAdminID(v uint64) *AdminShadowFilterUpdate {
	_u.mutation.ResetAdminID()
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableAdminID(v *uint64) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// AddAdminID adds value to the "admin_id" field.
func (_u *AdminShadowFilterUpdate) AddAdminID(v int64) *AdminShadowFilterUpdate {
	_u.mutation.AddAdminID(v)
	return _u
}

// ClearAdminID clears the value of the "admin_id" field.
func (_u *AdminShadowFilterUpdate) ClearAdminID() *AdminShadowFilterUpdate {
	_u.mutation.ClearAdminID()
	return _u
}

// SetItemType sets the "item_type" field.
func (_u *AdminShadowFilterUpdate) SetItemType(v string) *AdminShadowFilterUpdate {
	_u.mutation.SetItemType(v)
	return _u
}

// SetNillableItemType sets the "item_type" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableItemType(v *string) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetItemType(*v)
	}
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *AdminShadowFilterUpdate) SetItemID(v uint64) *AdminShadowFilterUpdate {
	_u.mutation.ResetItemID()
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableItemID(v *uint64) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// AddItemID adds value to the "item_id" field.
func (_u *AdminShadowFilterUpdate) AddItemID(v int64) *AdminShadowFilterUpdate {
	_u.mutation.AddItemID(v)
	return _u
}

// SetIsLocal sets the "is_local" field.
func (_u *AdminShadowFilterUpdate) SetIsLocal(v bool) *AdminShadowFilterUpdate {
	_u.mutation.SetIsLocal(v)
	return _u
}

// SetNillableIsLocal sets the "is_local" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableIsLocal(v *bool) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetIsLocal(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *AdminShadowFilterUpdate) SetNote(v string) *AdminShadowFilterUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableNote(v *string) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *AdminShadowFilterUpdate) ClearNote() *AdminShadowFilterUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetActive sets the "active" field.
func (_u *AdminShadowFilterUpdate) SetActive(v bool) *AdminShadowFilterUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableActive(v *bool) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetHistory sets the "history" field.
func (_u *AdminShadowFilterUpdate) SetHistory(v []interface{}) *AdminShadowFilterUpdate {
	_u.mutation.SetHistory(v)
	return _u
}

// AppendHistory appends value to the "history" field.
func (_u *AdminShadowFilterUpdate) AppendHistory(v []interface{}) *AdminShadowFilterUpdate {
	_u.mutation.AppendHistory(v)
	return _u
}

// ClearHistory clears the value of the "history" field.
func (_u *AdminShadowFilterUpdate) ClearHistory() *AdminShadowFilterUpdate {
	_u.mutation.ClearHistory()
	return _u
}

// SetRuleset sets the "ruleset" field.
func (_u *AdminShadowFilterUpdate) SetRuleset(v map[string]interface{}) *AdminShadowFilterUpdate {
	_u.mutation.SetRuleset(v)
	return _u
}

// ClearRuleset clears the value of the "ruleset" field.
func (_u *AdminShadowFilterUpdate) ClearRuleset() *AdminShadowFilterUpdate {
	_u.mutation.ClearRuleset()
	return _u
}

// SetPreventApFanout sets the "prevent_ap_fanout" field.
func (_u *AdminShadowFilterUpdate) SetPreventApFanout(v bool) *AdminShadowFilterUpdate {
	_u.mutation.SetPreventApFanout(v)
	return _u
}

// SetNillablePreventApFanout sets the "prevent_ap_fanout" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillablePreventApFanout(v *bool) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetPreventApFanout(*v)
	}
	return _u
}

// SetPreventNewDms sets the "prevent_new_dms" field.
func (_u *AdminShadowFilterUpdate) SetPreventNewDms(v bool) *AdminShadowFilterUpdate {
	_u.mutation.SetPreventNewDms(v)
	return _u
}

// SetNillablePreventNewDms sets the "prevent_new_dms" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillablePreventNewDms(v *bool) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetPreventNewDms(*v)
	}
	return _u
}

// SetIgnoreReports sets the "ignore_reports" field.
func (_u *AdminShadowFilterUpdate) SetIgnoreReports(v bool) *AdminShadowFilterUpdate {
	_u.mutation.SetIgnoreReports(v)
	return _u
}

// SetNillableIgnoreReports sets the "ignore_reports" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableIgnoreReports(v *bool) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetIgnoreReports(*v)
	}
	return _u
}

// SetIgnoreMentions sets the "ignore_mentions" field.
func (_u *AdminShadowFilterUpdate) SetIgnoreMentions(v bool) *AdminShadowFilterUpdate {
	_u.mutation.SetIgnoreMentions(v)
	return _u
}

// SetNillableIgnoreMentions sets the "ignore_mentions" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableIgnoreMentions(v *bool) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetIgnoreMentions(*v)
	}
	return _u
}

// SetIgnoreLinks sets the "ignore_links" field.
func (_u *AdminShadowFilterUpdate) SetIgnoreLinks(v bool) *AdminShadowFilterUpdate {
	_u.mutation.SetIgnoreLinks(v)
	return _u
}

// SetNillableIgnoreLinks sets the "ignore_links" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableIgnoreLinks(v *bool) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetIgnoreLinks(*v)
	}
	return _u
}

// SetIgnoreHashtags sets the "ignore_hashtags" field.
func (_u *AdminShadowFilterUpdate) SetIgnoreHashtags(v bool) *AdminShadowFilterUpdate {
	_u.mutation.SetIgnoreHashtags(v)
	return _u
}

// SetNillableIgnoreHashtags sets the "ignore_hashtags" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableIgnoreHashtags(v *bool) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetIgnoreHashtags(*v)
	}
	return _u
}

// SetHideFromPublicFeeds sets the "hide_from_public_feeds" field.
func (_u *AdminShadowFilterUpdate) SetHideFromPublicFeeds(v bool) *AdminShadowFilterUpdate {
	_u.mutation.SetHideFromPublicFeeds(v)
	return _u
}

// SetNillableHideFromPublicFeeds sets the "hide_from_public_feeds" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableHideFromPublicFeeds(v *bool) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetHideFromPublicFeeds(*v)
	}
	return _u
}

// SetHideFromTagFeeds sets the "hide_from_tag_feeds" field.
func (_u *AdminShadowFilterUpdate) SetHideFromTagFeeds(v bool) *AdminShadowFilterUpdate {
	_u.mutation.SetHideFromTagFeeds(v)
	return _u
}

// SetNillableHideFromTagFeeds sets the "hide_from_tag_feeds" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableHideFromTagFeeds(v *bool) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetHideFromTagFeeds(*v)
	}
	return _u
}

// SetHideEmbeds sets the "hide_embeds" field.
func (_u *AdminShadowFilterUpdate) SetHideEmbeds(v bool) *AdminShadowFilterUpdate {
	_u.mutation.SetHideEmbeds(v)
	return _u
}

// SetNillableHideEmbeds sets the "hide_embeds" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableHideEmbeds(v *bool) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetHideEmbeds(*v)
	}
	return _u
}

// SetHideFromStoryCarousel sets the "hide_from_story_carousel" field.
func (_u *AdminShadowFilterUpdate) SetHideFromStoryCarousel(v bool) *AdminShadowFilterUpdate {
	_u.mutation.SetHideFromStoryCarousel(v)
	return _u
}

// SetNillableHideFromStoryCarousel sets the "hide_from_story_carousel" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableHideFromStoryCarousel(v *bool) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetHideFromStoryCarousel(*v)
	}
	return _u
}

// SetHideFromSearchAutocomplete sets the "hide_from_search_autocomplete" field.
func (_u *AdminShadowFilterUpdate) SetHideFromSearchAutocomplete(v bool) *AdminShadowFilterUpdate {
	_u.mutation.SetHideFromSearchAutocomplete(v)
	return _u
}

// SetNillableHideFromSearchAutocomplete sets the "hide_from_search_autocomplete" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableHideFromSearchAutocomplete(v *bool) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetHideFromSearchAutocomplete(*v)
	}
	return _u
}

// SetHideFromSearch sets the "hide_from_search" field.
func (_u *AdminShadowFilterUpdate) SetHideFromSearch(v bool) *AdminShadowFilterUpdate {
	_u.mutation.SetHideFromSearch(v)
	return _u
}

// SetNillableHideFromSearch sets the "hide_from_search" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableHideFromSearch(v *bool) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetHideFromSearch(*v)
	}
	return _u
}

// SetRequiresLogin sets the "requires_login" field.
func (_u *AdminShadowFilterUpdate) SetRequiresLogin(v bool) *AdminShadowFilterUpdate {
	_u.mutation.SetRequiresLogin(v)
	return _u
}

// SetNillableRequiresLogin sets the "requires_login" field if the given value is not nil.
func (_u *AdminShadowFilterUpdate) SetNillableRequiresLogin(v *bool) *AdminShadowFilterUpdate {
	if v != nil {
		_u.SetRequiresLogin(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminShadowFilterUpdate) SetUpdatedAt(v time.Time) *AdminShadowFilterUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdminShadowFilterMutation object of the builder.
func (_u *AdminShadowFilterUpdate) Mutation() *AdminShadowFilterMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminShadowFilterUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminShadowFilterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminShadowFilterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminShadowFilterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminShadowFilterUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminshadowfilter.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AdminShadowFilterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(adminshadowfilter.Table, adminshadowfilter.Columns, sqlgraph.NewFieldSpec(adminshadowfilter.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AdminID(); ok {
		_spec.SetField(adminshadowfilter.FieldAdminID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAdminID(); ok {
		_spec.AddField(adminshadowfilter.FieldAdminID, field.TypeUint64, value)
	}
	if _u.mutation.AdminIDCleared() {
		_spec.ClearField(adminshadowfilter.FieldAdminID, field.TypeUint64)
	}
	if value, ok := _u.mutation.ItemType(); ok {
		_spec.SetField(adminshadowfilter.FieldItemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ItemID(); ok {
		_spec.SetField(adminshadowfilter.FieldItemID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedItemID(); ok {
		_spec.AddField(adminshadowfilter.FieldItemID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.IsLocal(); ok {
		_spec.SetField(adminshadowfilter.FieldIsLocal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(adminshadowfilter.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(adminshadowfilter.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(adminshadowfilter.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.History(); ok {
		_spec.SetField(adminshadowfilter.FieldHistory, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedHistory(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, adminshadowfilter.FieldHistory, value)
		})
	}
	if _u.mutation.HistoryCleared() {
		_spec.ClearField(adminshadowfilter.FieldHistory, field.TypeJSON)
	}
	if value, ok := _u.mutation.Ruleset(); ok {
		_spec.SetField(adminshadowfilter.FieldRuleset, field.TypeJSON, value)
	}
	if _u.mutation.RulesetCleared() {
		_spec.ClearField(adminshadowfilter.FieldRuleset, field.TypeJSON)
	}
	if value, ok := _u.mutation.PreventApFanout(); ok {
		_spec.SetField(adminshadowfilter.FieldPreventApFanout, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PreventNewDms(); ok {
		_spec.SetField(adminshadowfilter.FieldPreventNewDms, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IgnoreReports(); ok {
		_spec.SetField(adminshadowfilter.FieldIgnoreReports, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IgnoreMentions(); ok {
		_spec.SetField(adminshadowfilter.FieldIgnoreMentions, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IgnoreLinks(); ok {
		_spec.SetField(adminshadowfilter.FieldIgnoreLinks, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IgnoreHashtags(); ok {
		_spec.SetField(adminshadowfilter.FieldIgnoreHashtags, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HideFromPublicFeeds(); ok {
		_spec.SetField(adminshadowfilter.FieldHideFromPublicFeeds, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HideFromTagFeeds(); ok {
		_spec.SetField(adminshadowfilter.FieldHideFromTagFeeds, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HideEmbeds(); ok {
		_spec.SetField(adminshadowfilter.FieldHideEmbeds, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HideFromStoryCarousel(); ok {
		_spec.SetField(adminshadowfilter.FieldHideFromStoryCarousel, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HideFromSearchAutocomplete(); ok {
		_spec.SetField(adminshadowfilter.FieldHideFromSearchAutocomplete, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HideFromSearch(); ok {
		_spec.SetField(adminshadowfilter.FieldHideFromSearch, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequiresLogin(); ok {
		_spec.SetField(adminshadowfilter.FieldRequiresLogin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminshadowfilter.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminshadowfilter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminShadowFilterUpdateOne is the builder for updating a single AdminShadowFilter entity.
type AdminShadowFilterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminShadowFilterMutation
}

// SetAdminID sets the "admin_id" field.
func (_u *AdminShadowFilterUpdateOne) SetAdminID(v uint64) *AdminShadowFilterUpdateOne {
	_u.mutation.ResetAdminID()
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableAdminID(v *uint64) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// AddAdminID adds value to the "admin_id" field.
func (_u *AdminShadowFilterUpdateOne) AddAdminID(v int64) *AdminShadowFilterUpdateOne {
	_u.mutation.AddAdminID(v)
	return _u
}

// ClearAdminID clears the value of the "admin_id" field.
func (_u *AdminShadowFilterUpdateOne) ClearAdminID() *AdminShadowFilterUpdateOne {
	_u.mutation.ClearAdminID()
	return _u
}

// SetItemType sets the "item_type" field.
func (_u *AdminShadowFilterUpdateOne) SetItemType(v string) *AdminShadowFilterUpdateOne {
	_u.mutation.SetItemType(v)
	return _u
}

// SetNillableItemType sets the "item_type" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableItemType(v *string) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetItemType(*v)
	}
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *AdminShadowFilterUpdateOne) SetItemID(v uint64) *AdminShadowFilterUpdateOne {
	_u.mutation.ResetItemID()
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableItemID(v *uint64) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// AddItemID adds value to the "item_id" field.
func (_u *AdminShadowFilterUpdateOne) AddItemID(v int64) *AdminShadowFilterUpdateOne {
	_u.mutation.AddItemID(v)
	return _u
}

// SetIsLocal sets the "is_local" field.
func (_u *AdminShadowFilterUpdateOne) SetIsLocal(v bool) *AdminShadowFilterUpdateOne {
	_u.mutation.SetIsLocal(v)
	return _u
}

// SetNillableIsLocal sets the "is_local" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableIsLocal(v *bool) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetIsLocal(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *AdminShadowFilterUpdateOne) SetNote(v string) *AdminShadowFilterUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableNote(v *string) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *AdminShadowFilterUpdateOne) ClearNote() *AdminShadowFilterUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetActive sets the "active" field.
func (_u *AdminShadowFilterUpdateOne) SetActive(v bool) *AdminShadowFilterUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableActive(v *bool) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetHistory sets the "history" field.
func (_u *AdminShadowFilterUpdateOne) SetHistory(v []interface{}) *AdminShadowFilterUpdateOne {
	_u.mutation.SetHistory(v)
	return _u
}

// AppendHistory appends value to the "history" field.
func (_u *AdminShadowFilterUpdateOne) AppendHistory(v []interface{}) *AdminShadowFilterUpdateOne {
	_u.mutation.AppendHistory(v)
	return _u
}

// ClearHistory clears the value of the "history" field.
func (_u *AdminShadowFilterUpdateOne) ClearHistory() *AdminShadowFilterUpdateOne {
	_u.mutation.ClearHistory()
	return _u
}

// SetRuleset sets the "ruleset" field.
func (_u *AdminShadowFilterUpdateOne) SetRuleset(v map[string]interface{}) *AdminShadowFilterUpdateOne {
	_u.mutation.SetRuleset(v)
	return _u
}

// ClearRuleset clears the value of the "ruleset" field.
func (_u *AdminShadowFilterUpdateOne) ClearRuleset() *AdminShadowFilterUpdateOne {
	_u.mutation.ClearRuleset()
	return _u
}

// SetPreventApFanout sets the "prevent_ap_fanout" field.
func (_u *AdminShadowFilterUpdateOne) SetPreventApFanout(v bool) *AdminShadowFilterUpdateOne {
	_u.mutation.SetPreventApFanout(v)
	return _u
}

// SetNillablePreventApFanout sets the "prevent_ap_fanout" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillablePreventApFanout(v *bool) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetPreventApFanout(*v)
	}
	return _u
}

// SetPreventNewDms sets the "prevent_new_dms" field.
func (_u *AdminShadowFilterUpdateOne) SetPreventNewDms(v bool) *AdminShadowFilterUpdateOne {
	_u.mutation.SetPreventNewDms(v)
	return _u
}

// SetNillablePreventNewDms sets the "prevent_new_dms" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillablePreventNewDms(v *bool) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetPreventNewDms(*v)
	}
	return _u
}

// SetIgnoreReports sets the "ignore_reports" field.
func (_u *AdminShadowFilterUpdateOne) SetIgnoreReports(v bool) *AdminShadowFilterUpdateOne {
	_u.mutation.SetIgnoreReports(v)
	return _u
}

// SetNillableIgnoreReports sets the "ignore_reports" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableIgnoreReports(v *bool) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetIgnoreReports(*v)
	}
	return _u
}

// SetIgnoreMentions sets the "ignore_mentions" field.
func (_u *AdminShadowFilterUpdateOne) SetIgnoreMentions(v bool) *AdminShadowFilterUpdateOne {
	_u.mutation.SetIgnoreMentions(v)
	return _u
}

// SetNillableIgnoreMentions sets the "ignore_mentions" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableIgnoreMentions(v *bool) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetIgnoreMentions(*v)
	}
	return _u
}

// SetIgnoreLinks sets the "ignore_links" field.
func (_u *AdminShadowFilterUpdateOne) SetIgnoreLinks(v bool) *AdminShadowFilterUpdateOne {
	_u.mutation.SetIgnoreLinks(v)
	return _u
}

// SetNillableIgnoreLinks sets the "ignore_links" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableIgnoreLinks(v *bool) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetIgnoreLinks(*v)
	}
	return _u
}

// SetIgnoreHashtags sets the "ignore_hashtags" field.
func (_u *AdminShadowFilterUpdateOne) SetIgnoreHashtags(v bool) *AdminShadowFilterUpdateOne {
	_u.mutation.SetIgnoreHashtags(v)
	return _u
}

// SetNillableIgnoreHashtags sets the "ignore_hashtags" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableIgnoreHashtags(v *bool) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetIgnoreHashtags(*v)
	}
	return _u
}

// SetHideFromPublicFeeds sets the "hide_from_public_feeds" field.
func (_u *AdminShadowFilterUpdateOne) SetHideFromPublicFeeds(v bool) *AdminShadowFilterUpdateOne {
	_u.mutation.SetHideFromPublicFeeds(v)
	return _u
}

// SetNillableHideFromPublicFeeds sets the "hide_from_public_feeds" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableHideFromPublicFeeds(v *bool) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetHideFromPublicFeeds(*v)
	}
	return _u
}

// SetHideFromTagFeeds sets the "hide_from_tag_feeds" field.
func (_u *AdminShadowFilterUpdateOne) SetHideFromTagFeeds(v bool) *AdminShadowFilterUpdateOne {
	_u.mutation.SetHideFromTagFeeds(v)
	return _u
}

// SetNillableHideFromTagFeeds sets the "hide_from_tag_feeds" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableHideFromTagFeeds(v *bool) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetHideFromTagFeeds(*v)
	}
	return _u
}

// SetHideEmbeds sets the "hide_embeds" field.
func (_u *AdminShadowFilterUpdateOne) SetHideEmbeds(v bool) *AdminShadowFilterUpdateOne {
	_u.mutation.SetHideEmbeds(v)
	return _u
}

// SetNillableHideEmbeds sets the "hide_embeds" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableHideEmbeds(v *bool) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetHideEmbeds(*v)
	}
	return _u
}

// SetHideFromStoryCarousel sets the "hide_from_story_carousel" field.
func (_u *AdminShadowFilterUpdateOne) SetHideFromStoryCarousel(v bool) *AdminShadowFilterUpdateOne {
	_u.mutation.SetHideFromStoryCarousel(v)
	return _u
}

// SetNillableHideFromStoryCarousel sets the "hide_from_story_carousel" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableHideFromStoryCarousel(v *bool) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetHideFromStoryCarousel(*v)
	}
	return _u
}

// SetHideFromSearchAutocomplete sets the "hide_from_search_autocomplete" field.
func (_u *AdminShadowFilterUpdateOne) SetHideFromSearchAutocomplete(v bool) *AdminShadowFilterUpdateOne {
	_u.mutation.SetHideFromSearchAutocomplete(v)
	return _u
}

// SetNillableHideFromSearchAutocomplete sets the "hide_from_search_autocomplete" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableHideFromSearchAutocomplete(v *bool) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetHideFromSearchAutocomplete(*v)
	}
	return _u
}

// SetHideFromSearch sets the "hide_from_search" field.
func (_u *AdminShadowFilterUpdateOne) SetHideFromSearch(v bool) *AdminShadowFilterUpdateOne {
	_u.mutation.SetHideFromSearch(v)
	return _u
}

// SetNillableHideFromSearch sets the "hide_from_search" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableHideFromSearch(v *bool) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetHideFromSearch(*v)
	}
	return _u
}

// SetRequiresLogin sets the "requires_login" field.
func (_u *AdminShadowFilterUpdateOne) SetRequiresLogin(v bool) *AdminShadowFilterUpdateOne {
	_u.mutation.SetRequiresLogin(v)
	return _u
}

// SetNillableRequiresLogin sets the "requires_login" field if the given value is not nil.
func (_u *AdminShadowFilterUpdateOne) SetNillableRequiresLogin(v *bool) *AdminShadowFilterUpdateOne {
	if v != nil {
		_u.SetRequiresLogin(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminShadowFilterUpdateOne) SetUpdatedAt(v time.Time) *AdminShadowFilterUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdminShadowFilterMutation object of the builder.
func (_u *AdminShadowFilterUpdateOne) Mutation() *AdminShadowFilterMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminShadowFilterUpdate builder.
func (_u *AdminShadowFilterUpdateOne) Where(ps ...predicate.AdminShadowFilter) *AdminShadowFilterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminShadowFilterUpdateOne) Select(field string, fields ...string) *AdminShadowFilterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminShadowFilter entity.
func (_u *AdminShadowFilterUpdateOne) Save(ctx context.Context) (*AdminShadowFilter, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminShadowFilterUpdateOne) SaveX(ctx context.Context) *AdminShadowFilter {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminShadowFilterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminShadowFilterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminShadowFilterUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminshadowfilter.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AdminShadowFilterUpdateOne) sqlSave(ctx context.Context) (_node *AdminShadowFilter, err error) {
	_spec := sqlgraph.NewUpdateSpec(adminshadowfilter.Table, adminshadowfilter.Columns, sqlgraph.NewFieldSpec(adminshadowfilter.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminShadowFilter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminshadowfilter.FieldID)
		for _, f := range fields {
			if !adminshadowfilter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminshadowfilter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AdminID(); ok {
		_spec.SetField(adminshadowfilter.FieldAdminID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAdminID(); ok {
		_spec.AddField(adminshadowfilter.FieldAdminID, field.TypeUint64, value)
	}
	if _u.mutation.AdminIDCleared() {
		_spec.ClearField(adminshadowfilter.FieldAdminID, field.TypeUint64)
	}
	if value, ok := _u.mutation.ItemType(); ok {
		_spec.SetField(adminshadowfilter.FieldItemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ItemID(); ok {
		_spec.SetField(adminshadowfilter.FieldItemID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedItemID(); ok {
		_spec.AddField(adminshadowfilter.FieldItemID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.IsLocal(); ok {
		_spec.SetField(adminshadowfilter.FieldIsLocal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(adminshadowfilter.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(adminshadowfilter.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(adminshadowfilter.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.History(); ok {
		_spec.SetField(adminshadowfilter.FieldHistory, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedHistory(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, adminshadowfilter.FieldHistory, value)
		})
	}
	if _u.mutation.HistoryCleared() {
		_spec.ClearField(adminshadowfilter.FieldHistory, field.TypeJSON)
	}
	if value, ok := _u.mutation.Ruleset(); ok {
		_spec.SetField(adminshadowfilter.FieldRuleset, field.TypeJSON, value)
	}
	if _u.mutation.RulesetCleared() {
		_spec.ClearField(adminshadowfilter.FieldRuleset, field.TypeJSON)
	}
	if value, ok := _u.mutation.PreventApFanout(); ok {
		_spec.SetField(adminshadowfilter.FieldPreventApFanout, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PreventNewDms(); ok {
		_spec.SetField(adminshadowfilter.FieldPreventNewDms, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IgnoreReports(); ok {
		_spec.SetField(adminshadowfilter.FieldIgnoreReports, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IgnoreMentions(); ok {
		_spec.SetField(adminshadowfilter.FieldIgnoreMentions, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IgnoreLinks(); ok {
		_spec.SetField(adminshadowfilter.FieldIgnoreLinks, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IgnoreHashtags(); ok {
		_spec.SetField(adminshadowfilter.FieldIgnoreHashtags, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HideFromPublicFeeds(); ok {
		_spec.SetField(adminshadowfilter.FieldHideFromPublicFeeds, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HideFromTagFeeds(); ok {
		_spec.SetField(adminshadowfilter.FieldHideFromTagFeeds, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HideEmbeds(); ok {
		_spec.SetField(adminshadowfilter.FieldHideEmbeds, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HideFromStoryCarousel(); ok {
		_spec.SetField(adminshadowfilter.FieldHideFromStoryCarousel, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HideFromSearchAutocomplete(); ok {
		_spec.SetField(adminshadowfilter.FieldHideFromSearchAutocomplete, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HideFromSearch(); ok {
		_spec.SetField(adminshadowfilter.FieldHideFromSearch, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequiresLogin(); ok {
		_spec.SetField(adminshadowfilter.FieldRequiresLogin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminshadowfilter.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AdminShadowFilter{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminshadowfilter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
