// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/autospamcustomtokens"
	"glintfed.org/ent/predicate"
)

// AutospamCustomTokensUpdate is the builder for updating AutospamCustomTokens entities.
type AutospamCustomTokensUpdate struct {
	config
	hooks    []Hook
	mutation *AutospamCustomTokensMutation
}

// Where appends a list predicates to the AutospamCustomTokensUpdate builder.
func (_u *AutospamCustomTokensUpdate) Where(ps ...predicate.AutospamCustomTokens) *AutospamCustomTokensUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetToken sets the "token" field.
func (_u *AutospamCustomTokensUpdate) SetToken(v string) *AutospamCustomTokensUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *AutospamCustomTokensUpdate) SetNillableToken(v *string) *AutospamCustomTokensUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *AutospamCustomTokensUpdate) SetWeight(v int) *AutospamCustomTokensUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *AutospamCustomTokensUpdate) SetNillableWeight(v *int) *AutospamCustomTokensUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *AutospamCustomTokensUpdate) AddWeight(v int) *AutospamCustomTokensUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// SetIsSpam sets the "is_spam" field.
func (_u *AutospamCustomTokensUpdate) SetIsSpam(v bool) *AutospamCustomTokensUpdate {
	_u.mutation.SetIsSpam(v)
	return _u
}

// SetNillableIsSpam sets the "is_spam" field if the given value is not nil.
func (_u *AutospamCustomTokensUpdate) SetNillableIsSpam(v *bool) *AutospamCustomTokensUpdate {
	if v != nil {
		_u.SetIsSpam(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *AutospamCustomTokensUpdate) SetNote(v string) *AutospamCustomTokensUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *AutospamCustomTokensUpdate) SetNillableNote(v *string) *AutospamCustomTokensUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *AutospamCustomTokensUpdate) ClearNote() *AutospamCustomTokensUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetCategory sets the "category" field.
func (_u *AutospamCustomTokensUpdate) SetCategory(v string) *AutospamCustomTokensUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *AutospamCustomTokensUpdate) SetNillableCategory(v *string) *AutospamCustomTokensUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *AutospamCustomTokensUpdate) ClearCategory() *AutospamCustomTokensUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetActive sets the "active" field.
func (_u *AutospamCustomTokensUpdate) SetActive(v bool) *AutospamCustomTokensUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *AutospamCustomTokensUpdate) SetNillableActive(v *bool) *AutospamCustomTokensUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AutospamCustomTokensUpdate) SetUpdatedAt(v time.Time) *AutospamCustomTokensUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AutospamCustomTokensMutation object of the builder.
func (_u *AutospamCustomTokensUpdate) Mutation() *AutospamCustomTokensMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AutospamCustomTokensUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AutospamCustomTokensUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AutospamCustomTokensUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AutospamCustomTokensUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AutospamCustomTokensUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := autospamcustomtokens.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AutospamCustomTokensUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(autospamcustomtokens.Table, autospamcustomtokens.Columns, sqlgraph.NewFieldSpec(autospamcustomtokens.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(autospamcustomtokens.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(autospamcustomtokens.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(autospamcustomtokens.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsSpam(); ok {
		_spec.SetField(autospamcustomtokens.FieldIsSpam, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(autospamcustomtokens.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(autospamcustomtokens.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(autospamcustomtokens.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(autospamcustomtokens.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(autospamcustomtokens.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(autospamcustomtokens.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{autospamcustomtokens.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AutospamCustomTokensUpdateOne is the builder for updating a single AutospamCustomTokens entity.
type AutospamCustomTokensUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AutospamCustomTokensMutation
}

// SetToken sets the "token" field.
func (_u *AutospamCustomTokensUpdateOne) SetToken(v string) *AutospamCustomTokensUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *AutospamCustomTokensUpdateOne) SetNillableToken(v *string) *AutospamCustomTokensUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *AutospamCustomTokensUpdateOne) SetWeight(v int) *AutospamCustomTokensUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *AutospamCustomTokensUpdateOne) SetNillableWeight(v *int) *AutospamCustomTokensUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *AutospamCustomTokensUpdateOne) AddWeight(v int) *AutospamCustomTokensUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// SetIsSpam sets the "is_spam" field.
func (_u *AutospamCustomTokensUpdateOne) SetIsSpam(v bool) *AutospamCustomTokensUpdateOne {
	_u.mutation.SetIsSpam(v)
	return _u
}

// SetNillableIsSpam sets the "is_spam" field if the given value is not nil.
func (_u *AutospamCustomTokensUpdateOne) SetNillableIsSpam(v *bool) *AutospamCustomTokensUpdateOne {
	if v != nil {
		_u.SetIsSpam(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *AutospamCustomTokensUpdateOne) SetNote(v string) *AutospamCustomTokensUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *AutospamCustomTokensUpdateOne) SetNillableNote(v *string) *AutospamCustomTokensUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *AutospamCustomTokensUpdateOne) ClearNote() *AutospamCustomTokensUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetCategory sets the "category" field.
func (_u *AutospamCustomTokensUpdateOne) SetCategory(v string) *AutospamCustomTokensUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *AutospamCustomTokensUpdateOne) SetNillableCategory(v *string) *AutospamCustomTokensUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *AutospamCustomTokensUpdateOne) ClearCategory() *AutospamCustomTokensUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetActive sets the "active" field.
func (_u *AutospamCustomTokensUpdateOne) SetActive(v bool) *AutospamCustomTokensUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *AutospamCustomTokensUpdateOne) SetNillableActive(v *bool) *AutospamCustomTokensUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AutospamCustomTokensUpdateOne) SetUpdatedAt(v time.Time) *AutospamCustomTokensUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AutospamCustomTokensMutation object of the builder.
func (_u *AutospamCustomTokensUpdateOne) Mutation() *AutospamCustomTokensMutation {
	return _u.mutation
}

// Where appends a list predicates to the AutospamCustomTokensUpdate builder.
func (_u *AutospamCustomTokensUpdateOne) Where(ps ...predicate.AutospamCustomTokens) *AutospamCustomTokensUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AutospamCustomTokensUpdateOne) Select(field string, fields ...string) *AutospamCustomTokensUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AutospamCustomTokens entity.
func (_u *AutospamCustomTokensUpdateOne) Save(ctx context.Context) (*AutospamCustomTokens, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AutospamCustomTokensUpdateOne) SaveX(ctx context.Context) *AutospamCustomTokens {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AutospamCustomTokensUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AutospamCustomTokensUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AutospamCustomTokensUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := autospamcustomtokens.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AutospamCustomTokensUpdateOne) sqlSave(ctx context.Context) (_node *AutospamCustomTokens, err error) {
	_spec := sqlgraph.NewUpdateSpec(autospamcustomtokens.Table, autospamcustomtokens.Columns, sqlgraph.NewFieldSpec(autospamcustomtokens.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AutospamCustomTokens.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, autospamcustomtokens.FieldID)
		for _, f := range fields {
			if !autospamcustomtokens.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != autospamcustomtokens.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(autospamcustomtokens.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(autospamcustomtokens.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(autospamcustomtokens.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsSpam(); ok {
		_spec.SetField(autospamcustomtokens.FieldIsSpam, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(autospamcustomtokens.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(autospamcustomtokens.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(autospamcustomtokens.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(autospamcustomtokens.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(autospamcustomtokens.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(autospamcustomtokens.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AutospamCustomTokens{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{autospamcustomtokens.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
