// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/autospamcustomtokens"
	"glintfed.org/ent/predicate"
)

// AutospamCustomTokensDelete is the builder for deleting a AutospamCustomTokens entity.
type AutospamCustomTokensDelete struct {
	config
	hooks    []Hook
	mutation *AutospamCustomTokensMutation
}

// Where appends a list predicates to the AutospamCustomTokensDelete builder.
func (_d *AutospamCustomTokensDelete) Where(ps ...predicate.AutospamCustomTokens) *AutospamCustomTokensDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AutospamCustomTokensDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AutospamCustomTokensDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AutospamCustomTokensDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(autospamcustomtokens.Table, sqlgraph.NewFieldSpec(autospamcustomtokens.FieldID, field.TypeUint64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AutospamCustomTokensDeleteOne is the builder for deleting a single AutospamCustomTokens entity.
type AutospamCustomTokensDeleteOne struct {
	_d *AutospamCustomTokensDelete
}

// Where appends a list predicates to the AutospamCustomTokensDelete builder.
func (_d *AutospamCustomTokensDeleteOne) Where(ps ...predicate.AutospamCustomTokens) *AutospamCustomTokensDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AutospamCustomTokensDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{autospamcustomtokens.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AutospamCustomTokensDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
