// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/circleprofile"
	"glintfed.org/ent/predicate"
)

// CircleProfileUpdate is the builder for updating CircleProfile entities.
type CircleProfileUpdate struct {
	config
	hooks    []Hook
	mutation *CircleProfileMutation
}

// Where appends a list predicates to the CircleProfileUpdate builder.
func (_u *CircleProfileUpdate) Where(ps ...predicate.CircleProfile) *CircleProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *CircleProfileUpdate) SetOwnerID(v uint64) *CircleProfileUpdate {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *CircleProfileUpdate) SetNillableOwnerID(v *uint64) *CircleProfileUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *CircleProfileUpdate) AddOwnerID(v int64) *CircleProfileUpdate {
	_u.mutation.AddOwnerID(v)
	return _u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (_u *CircleProfileUpdate) ClearOwnerID() *CircleProfileUpdate {
	_u.mutation.ClearOwnerID()
	return _u
}

// SetCircleID sets the "circle_id" field.
func (_u *CircleProfileUpdate) SetCircleID(v uint64) *CircleProfileUpdate {
	_u.mutation.ResetCircleID()
	_u.mutation.SetCircleID(v)
	return _u
}

// SetNillableCircleID sets the "circle_id" field if the given value is not nil.
func (_u *CircleProfileUpdate) SetNillableCircleID(v *uint64) *CircleProfileUpdate {
	if v != nil {
		_u.SetCircleID(*v)
	}
	return _u
}

// AddCircleID adds value to the "circle_id" field.
func (_u *CircleProfileUpdate) AddCircleID(v int64) *CircleProfileUpdate {
	_u.mutation.AddCircleID(v)
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *CircleProfileUpdate) SetProfileID(v uint64) *CircleProfileUpdate {
	_u.mutation.ResetProfileID()
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *CircleProfileUpdate) SetNillableProfileID(v *uint64) *CircleProfileUpdate {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// AddProfileID adds value to the "profile_id" field.
func (_u *CircleProfileUpdate) AddProfileID(v int64) *CircleProfileUpdate {
	_u.mutation.AddProfileID(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CircleProfileUpdate) SetUpdatedAt(v time.Time) *CircleProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CircleProfileMutation object of the builder.
func (_u *CircleProfileUpdate) Mutation() *CircleProfileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CircleProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CircleProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CircleProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CircleProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CircleProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := circleprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CircleProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(circleprofile.Table, circleprofile.Columns, sqlgraph.NewFieldSpec(circleprofile.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(circleprofile.FieldOwnerID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(circleprofile.FieldOwnerID, field.TypeUint64, value)
	}
	if _u.mutation.OwnerIDCleared() {
		_spec.ClearField(circleprofile.FieldOwnerID, field.TypeUint64)
	}
	if value, ok := _u.mutation.CircleID(); ok {
		_spec.SetField(circleprofile.FieldCircleID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCircleID(); ok {
		_spec.AddField(circleprofile.FieldCircleID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ProfileID(); ok {
		_spec.SetField(circleprofile.FieldProfileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedProfileID(); ok {
		_spec.AddField(circleprofile.FieldProfileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(circleprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{circleprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CircleProfileUpdateOne is the builder for updating a single CircleProfile entity.
type CircleProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CircleProfileMutation
}

// SetOwnerID sets the "owner_id" field.
func (_u *CircleProfileUpdateOne) SetOwnerID(v uint64) *CircleProfileUpdateOne {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *CircleProfileUpdateOne) SetNillableOwnerID(v *uint64) *CircleProfileUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *CircleProfileUpdateOne) AddOwnerID(v int64) *CircleProfileUpdateOne {
	_u.mutation.AddOwnerID(v)
	return _u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (_u *CircleProfileUpdateOne) ClearOwnerID() *CircleProfileUpdateOne {
	_u.mutation.ClearOwnerID()
	return _u
}

// SetCircleID sets the "circle_id" field.
func (_u *CircleProfileUpdateOne) SetCircleID(v uint64) *CircleProfileUpdateOne {
	_u.mutation.ResetCircleID()
	_u.mutation.SetCircleID(v)
	return _u
}

// SetNillableCircleID sets the "circle_id" field if the given value is not nil.
func (_u *CircleProfileUpdateOne) SetNillableCircleID(v *uint64) *CircleProfileUpdateOne {
	if v != nil {
		_u.SetCircleID(*v)
	}
	return _u
}

// AddCircleID adds value to the "circle_id" field.
func (_u *CircleProfileUpdateOne) AddCircleID(v int64) *CircleProfileUpdateOne {
	_u.mutation.AddCircleID(v)
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *CircleProfileUpdateOne) SetProfileID(v uint64) *CircleProfileUpdateOne {
	_u.mutation.ResetProfileID()
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *CircleProfileUpdateOne) SetNillableProfileID(v *uint64) *CircleProfileUpdateOne {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// AddProfileID adds value to the "profile_id" field.
func (_u *CircleProfileUpdateOne) AddProfileID(v int64) *CircleProfileUpdateOne {
	_u.mutation.AddProfileID(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CircleProfileUpdateOne) SetUpdatedAt(v time.Time) *CircleProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CircleProfileMutation object of the builder.
func (_u *CircleProfileUpdateOne) Mutation() *CircleProfileMutation {
	return _u.mutation
}

// Where appends a list predicates to the CircleProfileUpdate builder.
func (_u *CircleProfileUpdateOne) Where(ps ...predicate.CircleProfile) *CircleProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CircleProfileUpdateOne) Select(field string, fields ...string) *CircleProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CircleProfile entity.
func (_u *CircleProfileUpdateOne) Save(ctx context.Context) (*CircleProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CircleProfileUpdateOne) SaveX(ctx context.Context) *CircleProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CircleProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CircleProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CircleProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := circleprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CircleProfileUpdateOne) sqlSave(ctx context.Context) (_node *CircleProfile, err error) {
	_spec := sqlgraph.NewUpdateSpec(circleprofile.Table, circleprofile.Columns, sqlgraph.NewFieldSpec(circleprofile.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CircleProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, circleprofile.FieldID)
		for _, f := range fields {
			if !circleprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != circleprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(circleprofile.FieldOwnerID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(circleprofile.FieldOwnerID, field.TypeUint64, value)
	}
	if _u.mutation.OwnerIDCleared() {
		_spec.ClearField(circleprofile.FieldOwnerID, field.TypeUint64)
	}
	if value, ok := _u.mutation.CircleID(); ok {
		_spec.SetField(circleprofile.FieldCircleID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCircleID(); ok {
		_spec.AddField(circleprofile.FieldCircleID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ProfileID(); ok {
		_spec.SetField(circleprofile.FieldProfileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedProfileID(); ok {
		_spec.AddField(circleprofile.FieldProfileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(circleprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &CircleProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{circleprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
