// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/customfilter"
)

// CustomFilterCreate is the builder for creating a CustomFilter entity.
type CustomFilterCreate struct {
	config
	mutation *CustomFilterMutation
	hooks    []Hook
}

// SetProfileID sets the "profile_id" field.
func (_c *CustomFilterCreate) SetProfileID(v uint64) *CustomFilterCreate {
	_c.mutation.SetProfileID(v)
	return _c
}

// SetPhrase sets the "phrase" field.
func (_c *CustomFilterCreate) SetPhrase(v string) *CustomFilterCreate {
	_c.mutation.SetPhrase(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *CustomFilterCreate) SetAction(v int) *CustomFilterCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_c *CustomFilterCreate) SetNillableAction(v *int) *CustomFilterCreate {
	if v != nil {
		_c.SetAction(*v)
	}
	return _c
}

// SetContext sets the "context" field.
func (_c *CustomFilterCreate) SetContext(v []string) *CustomFilterCreate {
	_c.mutation.SetContext(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *CustomFilterCreate) SetExpiresAt(v time.Time) *CustomFilterCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *CustomFilterCreate) SetNillableExpiresAt(v *time.Time) *CustomFilterCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CustomFilterCreate) SetCreatedAt(v time.Time) *CustomFilterCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CustomFilterCreate) SetNillableCreatedAt(v *time.Time) *CustomFilterCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CustomFilterCreate) SetUpdatedAt(v time.Time) *CustomFilterCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CustomFilterCreate) SetNillableUpdatedAt(v *time.Time) *CustomFilterCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CustomFilterCreate) SetID(v uint64) *CustomFilterCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CustomFilterMutation object of the builder.
func (_c *CustomFilterCreate) Mutation() *CustomFilterMutation {
	return _c.mutation
}

// Save creates the CustomFilter in the database.
func (_c *CustomFilterCreate) Save(ctx context.Context) (*CustomFilter, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomFilterCreate) SaveX(ctx context.Context) *CustomFilter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomFilterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomFilterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CustomFilterCreate) defaults() {
	if _, ok := _c.mutation.Action(); !ok {
		v := customfilter.DefaultAction
		_c.mutation.SetAction(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := customfilter.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := customfilter.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomFilterCreate) check() error {
	if _, ok := _c.mutation.ProfileID(); !ok {
		return &ValidationError{Name: "profile_id", err: errors.New(`ent: missing required field "CustomFilter.profile_id"`)}
	}
	if _, ok := _c.mutation.Phrase(); !ok {
		return &ValidationError{Name: "phrase", err: errors.New(`ent: missing required field "CustomFilter.phrase"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "CustomFilter.action"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CustomFilter.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CustomFilter.updated_at"`)}
	}
	return nil
}

func (_c *CustomFilterCreate) sqlSave(ctx context.Context) (*CustomFilter, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CustomFilterCreate) createSpec() (*CustomFilter, *sqlgraph.CreateSpec) {
	var (
		_node = &CustomFilter{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(customfilter.Table, sqlgraph.NewFieldSpec(customfilter.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ProfileID(); ok {
		_spec.SetField(customfilter.FieldProfileID, field.TypeUint64, value)
		_node.ProfileID = value
	}
	if value, ok := _c.mutation.Phrase(); ok {
		_spec.SetField(customfilter.FieldPhrase, field.TypeString, value)
		_node.Phrase = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(customfilter.FieldAction, field.TypeInt, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Context(); ok {
		_spec.SetField(customfilter.FieldContext, field.TypeJSON, value)
		_node.Context = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(customfilter.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(customfilter.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(customfilter.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// CustomFilterCreateBulk is the builder for creating many CustomFilter entities in bulk.
type CustomFilterCreateBulk struct {
	config
	err      error
	builders []*CustomFilterCreate
}

// Save creates the CustomFilter entities in the database.
func (_c *CustomFilterCreateBulk) Save(ctx context.Context) ([]*CustomFilter, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CustomFilter, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomFilterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomFilterCreateBulk) SaveX(ctx context.Context) []*CustomFilter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomFilterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomFilterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
