// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/defaultdomainblock"
	"glintfed.org/ent/predicate"
)

// DefaultDomainBlockUpdate is the builder for updating DefaultDomainBlock entities.
type DefaultDomainBlockUpdate struct {
	config
	hooks    []Hook
	mutation *DefaultDomainBlockMutation
}

// Where appends a list predicates to the DefaultDomainBlockUpdate builder.
func (_u *DefaultDomainBlockUpdate) Where(ps ...predicate.DefaultDomainBlock) *DefaultDomainBlockUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDomain sets the "domain" field.
func (_u *DefaultDomainBlockUpdate) SetDomain(v string) *DefaultDomainBlockUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *DefaultDomainBlockUpdate) SetNillableDomain(v *string) *DefaultDomainBlockUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *DefaultDomainBlockUpdate) SetNote(v string) *DefaultDomainBlockUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *DefaultDomainBlockUpdate) SetNillableNote(v *string) *DefaultDomainBlockUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *DefaultDomainBlockUpdate) ClearNote() *DefaultDomainBlockUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DefaultDomainBlockUpdate) SetUpdatedAt(v time.Time) *DefaultDomainBlockUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DefaultDomainBlockMutation object of the builder.
func (_u *DefaultDomainBlockUpdate) Mutation() *DefaultDomainBlockMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DefaultDomainBlockUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DefaultDomainBlockUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DefaultDomainBlockUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DefaultDomainBlockUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DefaultDomainBlockUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := defaultdomainblock.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DefaultDomainBlockUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(defaultdomainblock.Table, defaultdomainblock.Columns, sqlgraph.NewFieldSpec(defaultdomainblock.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(defaultdomainblock.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(defaultdomainblock.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(defaultdomainblock.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(defaultdomainblock.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{defaultdomainblock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DefaultDomainBlockUpdateOne is the builder for updating a single DefaultDomainBlock entity.
type DefaultDomainBlockUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DefaultDomainBlockMutation
}

// SetDomain sets the "domain" field.
func (_u *DefaultDomainBlockUpdateOne) SetDomain(v string) *DefaultDomainBlockUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *DefaultDomainBlockUpdateOne) SetNillableDomain(v *string) *DefaultDomainBlockUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *DefaultDomainBlockUpdateOne) SetNote(v string) *DefaultDomainBlockUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *DefaultDomainBlockUpdateOne) SetNillableNote(v *string) *DefaultDomainBlockUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *DefaultDomainBlockUpdateOne) ClearNote() *DefaultDomainBlockUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DefaultDomainBlockUpdateOne) SetUpdatedAt(v time.Time) *DefaultDomainBlockUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DefaultDomainBlockMutation object of the builder.
func (_u *DefaultDomainBlockUpdateOne) Mutation() *DefaultDomainBlockMutation {
	return _u.mutation
}

// Where appends a list predicates to the DefaultDomainBlockUpdate builder.
func (_u *DefaultDomainBlockUpdateOne) Where(ps ...predicate.DefaultDomainBlock) *DefaultDomainBlockUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DefaultDomainBlockUpdateOne) Select(field string, fields ...string) *DefaultDomainBlockUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DefaultDomainBlock entity.
func (_u *DefaultDomainBlockUpdateOne) Save(ctx context.Context) (*DefaultDomainBlock, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DefaultDomainBlockUpdateOne) SaveX(ctx context.Context) *DefaultDomainBlock {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DefaultDomainBlockUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DefaultDomainBlockUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DefaultDomainBlockUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := defaultdomainblock.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DefaultDomainBlockUpdateOne) sqlSave(ctx context.Context) (_node *DefaultDomainBlock, err error) {
	_spec := sqlgraph.NewUpdateSpec(defaultdomainblock.Table, defaultdomainblock.Columns, sqlgraph.NewFieldSpec(defaultdomainblock.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DefaultDomainBlock.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, defaultdomainblock.FieldID)
		for _, f := range fields {
			if !defaultdomainblock.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != defaultdomainblock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(defaultdomainblock.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(defaultdomainblock.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(defaultdomainblock.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(defaultdomainblock.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &DefaultDomainBlock{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{defaultdomainblock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
