// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/discovercategory"
	"glintfed.org/ent/predicate"
)

// DiscoverCategoryDelete is the builder for deleting a DiscoverCategory entity.
type DiscoverCategoryDelete struct {
	config
	hooks    []Hook
	mutation *DiscoverCategoryMutation
}

// Where appends a list predicates to the DiscoverCategoryDelete builder.
func (_d *DiscoverCategoryDelete) Where(ps ...predicate.DiscoverCategory) *DiscoverCategoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DiscoverCategoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiscoverCategoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DiscoverCategoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(discovercategory.Table, sqlgraph.NewFieldSpec(discovercategory.FieldID, field.TypeUint64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DiscoverCategoryDeleteOne is the builder for deleting a single DiscoverCategory entity.
type DiscoverCategoryDeleteOne struct {
	_d *DiscoverCategoryDelete
}

// Where appends a list predicates to the DiscoverCategoryDelete builder.
func (_d *DiscoverCategoryDeleteOne) Where(ps ...predicate.DiscoverCategory) *DiscoverCategoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DiscoverCategoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{discovercategory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiscoverCategoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
