// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/follower"
	"glintfed.org/ent/predicate"
)

// FollowerUpdate is the builder for updating Follower entities.
type FollowerUpdate struct {
	config
	hooks    []Hook
	mutation *FollowerMutation
}

// Where appends a list predicates to the FollowerUpdate builder.
func (_u *FollowerUpdate) Where(ps ...predicate.Follower) *FollowerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *FollowerUpdate) SetProfileID(v uint64) *FollowerUpdate {
	_u.mutation.ResetProfileID()
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *FollowerUpdate) SetNillableProfileID(v *uint64) *FollowerUpdate {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// AddProfileID adds value to the "profile_id" field.
func (_u *FollowerUpdate) AddProfileID(v int64) *FollowerUpdate {
	_u.mutation.AddProfileID(v)
	return _u
}

// SetFollowingID sets the "following_id" field.
func (_u *FollowerUpdate) SetFollowingID(v uint64) *FollowerUpdate {
	_u.mutation.ResetFollowingID()
	_u.mutation.SetFollowingID(v)
	return _u
}

// SetNillableFollowingID sets the "following_id" field if the given value is not nil.
func (_u *FollowerUpdate) SetNillableFollowingID(v *uint64) *FollowerUpdate {
	if v != nil {
		_u.SetFollowingID(*v)
	}
	return _u
}

// AddFollowingID adds value to the "following_id" field.
func (_u *FollowerUpdate) AddFollowingID(v int64) *FollowerUpdate {
	_u.mutation.AddFollowingID(v)
	return _u
}

// SetLocalProfile sets the "local_profile" field.
func (_u *FollowerUpdate) SetLocalProfile(v bool) *FollowerUpdate {
	_u.mutation.SetLocalProfile(v)
	return _u
}

// SetNillableLocalProfile sets the "local_profile" field if the given value is not nil.
func (_u *FollowerUpdate) SetNillableLocalProfile(v *bool) *FollowerUpdate {
	if v != nil {
		_u.SetLocalProfile(*v)
	}
	return _u
}

// SetLocalFollowing sets the "local_following" field.
func (_u *FollowerUpdate) SetLocalFollowing(v bool) *FollowerUpdate {
	_u.mutation.SetLocalFollowing(v)
	return _u
}

// SetNillableLocalFollowing sets the "local_following" field if the given value is not nil.
func (_u *FollowerUpdate) SetNillableLocalFollowing(v *bool) *FollowerUpdate {
	if v != nil {
		_u.SetLocalFollowing(*v)
	}
	return _u
}

// SetShowReblogs sets the "show_reblogs" field.
func (_u *FollowerUpdate) SetShowReblogs(v bool) *FollowerUpdate {
	_u.mutation.SetShowReblogs(v)
	return _u
}

// SetNillableShowReblogs sets the "show_reblogs" field if the given value is not nil.
func (_u *FollowerUpdate) SetNillableShowReblogs(v *bool) *FollowerUpdate {
	if v != nil {
		_u.SetShowReblogs(*v)
	}
	return _u
}

// SetNotify sets the "notify" field.
func (_u *FollowerUpdate) SetNotify(v bool) *FollowerUpdate {
	_u.mutation.SetNotify(v)
	return _u
}

// SetNillableNotify sets the "notify" field if the given value is not nil.
func (_u *FollowerUpdate) SetNillableNotify(v *bool) *FollowerUpdate {
	if v != nil {
		_u.SetNotify(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FollowerUpdate) SetUpdatedAt(v time.Time) *FollowerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FollowerMutation object of the builder.
func (_u *FollowerUpdate) Mutation() *FollowerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FollowerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FollowerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FollowerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FollowerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FollowerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := follower.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *FollowerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(follower.Table, follower.Columns, sqlgraph.NewFieldSpec(follower.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProfileID(); ok {
		_spec.SetField(follower.FieldProfileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedProfileID(); ok {
		_spec.AddField(follower.FieldProfileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.FollowingID(); ok {
		_spec.SetField(follower.FieldFollowingID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFollowingID(); ok {
		_spec.AddField(follower.FieldFollowingID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.LocalProfile(); ok {
		_spec.SetField(follower.FieldLocalProfile, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LocalFollowing(); ok {
		_spec.SetField(follower.FieldLocalFollowing, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ShowReblogs(); ok {
		_spec.SetField(follower.FieldShowReblogs, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notify(); ok {
		_spec.SetField(follower.FieldNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(follower.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{follower.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FollowerUpdateOne is the builder for updating a single Follower entity.
type FollowerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FollowerMutation
}

// SetProfileID sets the "profile_id" field.
func (_u *FollowerUpdateOne) SetProfileID(v uint64) *FollowerUpdateOne {
	_u.mutation.ResetProfileID()
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *FollowerUpdateOne) SetNillableProfileID(v *uint64) *FollowerUpdateOne {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// AddProfileID adds value to the "profile_id" field.
func (_u *FollowerUpdateOne) AddProfileID(v int64) *FollowerUpdateOne {
	_u.mutation.AddProfileID(v)
	return _u
}

// SetFollowingID sets the "following_id" field.
func (_u *FollowerUpdateOne) SetFollowingID(v uint64) *FollowerUpdateOne {
	_u.mutation.ResetFollowingID()
	_u.mutation.SetFollowingID(v)
	return _u
}

// SetNillableFollowingID sets the "following_id" field if the given value is not nil.
func (_u *FollowerUpdateOne) SetNillableFollowingID(v *uint64) *FollowerUpdateOne {
	if v != nil {
		_u.SetFollowingID(*v)
	}
	return _u
}

// AddFollowingID adds value to the "following_id" field.
func (_u *FollowerUpdateOne) AddFollowingID(v int64) *FollowerUpdateOne {
	_u.mutation.AddFollowingID(v)
	return _u
}

// SetLocalProfile sets the "local_profile" field.
func (_u *FollowerUpdateOne) SetLocalProfile(v bool) *FollowerUpdateOne {
	_u.mutation.SetLocalProfile(v)
	return _u
}

// SetNillableLocalProfile sets the "local_profile" field if the given value is not nil.
func (_u *FollowerUpdateOne) SetNillableLocalProfile(v *bool) *FollowerUpdateOne {
	if v != nil {
		_u.SetLocalProfile(*v)
	}
	return _u
}

// SetLocalFollowing sets the "local_following" field.
func (_u *FollowerUpdateOne) SetLocalFollowing(v bool) *FollowerUpdateOne {
	_u.mutation.SetLocalFollowing(v)
	return _u
}

// SetNillableLocalFollowing sets the "local_following" field if the given value is not nil.
func (_u *FollowerUpdateOne) SetNillableLocalFollowing(v *bool) *FollowerUpdateOne {
	if v != nil {
		_u.SetLocalFollowing(*v)
	}
	return _u
}

// SetShowReblogs sets the "show_reblogs" field.
func (_u *FollowerUpdateOne) SetShowReblogs(v bool) *FollowerUpdateOne {
	_u.mutation.SetShowReblogs(v)
	return _u
}

// SetNillableShowReblogs sets the "show_reblogs" field if the given value is not nil.
func (_u *FollowerUpdateOne) SetNillableShowReblogs(v *bool) *FollowerUpdateOne {
	if v != nil {
		_u.SetShowReblogs(*v)
	}
	return _u
}

// SetNotify sets the "notify" field.
func (_u *FollowerUpdateOne) SetNotify(v bool) *FollowerUpdateOne {
	_u.mutation.SetNotify(v)
	return _u
}

// SetNillableNotify sets the "notify" field if the given value is not nil.
func (_u *FollowerUpdateOne) SetNillableNotify(v *bool) *FollowerUpdateOne {
	if v != nil {
		_u.SetNotify(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FollowerUpdateOne) SetUpdatedAt(v time.Time) *FollowerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FollowerMutation object of the builder.
func (_u *FollowerUpdateOne) Mutation() *FollowerMutation {
	return _u.mutation
}

// Where appends a list predicates to the FollowerUpdate builder.
func (_u *FollowerUpdateOne) Where(ps ...predicate.Follower) *FollowerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FollowerUpdateOne) Select(field string, fields ...string) *FollowerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Follower entity.
func (_u *FollowerUpdateOne) Save(ctx context.Context) (*Follower, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FollowerUpdateOne) SaveX(ctx context.Context) *Follower {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FollowerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FollowerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FollowerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := follower.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *FollowerUpdateOne) sqlSave(ctx context.Context) (_node *Follower, err error) {
	_spec := sqlgraph.NewUpdateSpec(follower.Table, follower.Columns, sqlgraph.NewFieldSpec(follower.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Follower.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, follower.FieldID)
		for _, f := range fields {
			if !follower.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != follower.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProfileID(); ok {
		_spec.SetField(follower.FieldProfileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedProfileID(); ok {
		_spec.AddField(follower.FieldProfileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.FollowingID(); ok {
		_spec.SetField(follower.FieldFollowingID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFollowingID(); ok {
		_spec.AddField(follower.FieldFollowingID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.LocalProfile(); ok {
		_spec.SetField(follower.FieldLocalProfile, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LocalFollowing(); ok {
		_spec.SetField(follower.FieldLocalFollowing, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ShowReblogs(); ok {
		_spec.SetField(follower.FieldShowReblogs, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notify(); ok {
		_spec.SetField(follower.FieldNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(follower.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Follower{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{follower.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
