// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"glintfed.org/ent/groupcomment"
)

// GroupComment is the model entity for the GroupComment schema.
type GroupComment struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID uint64 `json:"group_id,omitempty"`
	// ProfileID holds the value of the "profile_id" field.
	ProfileID uint64 `json:"profile_id,omitempty"`
	// StatusID holds the value of the "status_id" field.
	StatusID uint64 `json:"status_id,omitempty"`
	// InReplyToID holds the value of the "in_reply_to_id" field.
	InReplyToID uint64 `json:"in_reply_to_id,omitempty"`
	// RemoteURL holds the value of the "remote_url" field.
	RemoteURL string `json:"remote_url,omitempty"`
	// Caption holds the value of the "caption" field.
	Caption string `json:"caption,omitempty"`
	// IsNsfw holds the value of the "is_nsfw" field.
	IsNsfw bool `json:"is_nsfw,omitempty"`
	// Visibility holds the value of the "visibility" field.
	Visibility string `json:"visibility,omitempty"`
	// LikesCount holds the value of the "likes_count" field.
	LikesCount uint32 `json:"likes_count,omitempty"`
	// RepliesCount holds the value of the "replies_count" field.
	RepliesCount uint32 `json:"replies_count,omitempty"`
	// CwSummary holds the value of the "cw_summary" field.
	CwSummary string `json:"cw_summary,omitempty"`
	// MediaIds holds the value of the "media_ids" field.
	MediaIds []uint64 `json:"media_ids,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Local holds the value of the "local" field.
	Local bool `json:"local,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupComment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case groupcomment.FieldMediaIds, groupcomment.FieldMetadata:
			values[i] = new([]byte)
		case groupcomment.FieldIsNsfw, groupcomment.FieldLocal:
			values[i] = new(sql.NullBool)
		case groupcomment.FieldID, groupcomment.FieldGroupID, groupcomment.FieldProfileID, groupcomment.FieldStatusID, groupcomment.FieldInReplyToID, groupcomment.FieldLikesCount, groupcomment.FieldRepliesCount:
			values[i] = new(sql.NullInt64)
		case groupcomment.FieldRemoteURL, groupcomment.FieldCaption, groupcomment.FieldVisibility, groupcomment.FieldCwSummary, groupcomment.FieldStatus, groupcomment.FieldType:
			values[i] = new(sql.NullString)
		case groupcomment.FieldCreatedAt, groupcomment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupComment fields.
func (_m *GroupComment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case groupcomment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case groupcomment.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = uint64(value.Int64)
			}
		case groupcomment.FieldProfileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field profile_id", values[i])
			} else if value.Valid {
				_m.ProfileID = uint64(value.Int64)
			}
		case groupcomment.FieldStatusID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_id", values[i])
			} else if value.Valid {
				_m.StatusID = uint64(value.Int64)
			}
		case groupcomment.FieldInReplyToID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field in_reply_to_id", values[i])
			} else if value.Valid {
				_m.InReplyToID = uint64(value.Int64)
			}
		case groupcomment.FieldRemoteURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remote_url", values[i])
			} else if value.Valid {
				_m.RemoteURL = value.String
			}
		case groupcomment.FieldCaption:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field caption", values[i])
			} else if value.Valid {
				_m.Caption = value.String
			}
		case groupcomment.FieldIsNsfw:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_nsfw", values[i])
			} else if value.Valid {
				_m.IsNsfw = value.Bool
			}
		case groupcomment.FieldVisibility:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visibility", values[i])
			} else if value.Valid {
				_m.Visibility = value.String
			}
		case groupcomment.FieldLikesCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field likes_count", values[i])
			} else if value.Valid {
				_m.LikesCount = uint32(value.Int64)
			}
		case groupcomment.FieldRepliesCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field replies_count", values[i])
			} else if value.Valid {
				_m.RepliesCount = uint32(value.Int64)
			}
		case groupcomment.FieldCwSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cw_summary", values[i])
			} else if value.Valid {
				_m.CwSummary = value.String
			}
		case groupcomment.FieldMediaIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field media_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MediaIds); err != nil {
					return fmt.Errorf("unmarshal field media_ids: %w", err)
				}
			}
		case groupcomment.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case groupcomment.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case groupcomment.FieldLocal:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field local", values[i])
			} else if value.Valid {
				_m.Local = value.Bool
			}
		case groupcomment.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case groupcomment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case groupcomment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupComment.
// This includes values selected through modifiers, order, etc.
func (_m *GroupComment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GroupComment.
// Note that you need to call GroupComment.Unwrap() before calling this method if this GroupComment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupComment) Update() *GroupCommentUpdateOne {
	return NewGroupCommentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupComment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupComment) Unwrap() *GroupComment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupComment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupComment) String() string {
	var builder strings.Builder
	builder.WriteString("GroupComment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("profile_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProfileID))
	builder.WriteString(", ")
	builder.WriteString("status_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StatusID))
	builder.WriteString(", ")
	builder.WriteString("in_reply_to_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InReplyToID))
	builder.WriteString(", ")
	builder.WriteString("remote_url=")
	builder.WriteString(_m.RemoteURL)
	builder.WriteString(", ")
	builder.WriteString("caption=")
	builder.WriteString(_m.Caption)
	builder.WriteString(", ")
	builder.WriteString("is_nsfw=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsNsfw))
	builder.WriteString(", ")
	builder.WriteString("visibility=")
	builder.WriteString(_m.Visibility)
	builder.WriteString(", ")
	builder.WriteString("likes_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.LikesCount))
	builder.WriteString(", ")
	builder.WriteString("replies_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RepliesCount))
	builder.WriteString(", ")
	builder.WriteString("cw_summary=")
	builder.WriteString(_m.CwSummary)
	builder.WriteString(", ")
	builder.WriteString("media_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.MediaIds))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("local=")
	builder.WriteString(fmt.Sprintf("%v", _m.Local))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GroupComments is a parsable slice of GroupComment.
type GroupComments []*GroupComment
