// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/grouphashtag"
)

// GroupHashtagCreate is the builder for creating a GroupHashtag entity.
type GroupHashtagCreate struct {
	config
	mutation *GroupHashtagMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *GroupHashtagCreate) SetName(v string) *GroupHashtagCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetFormatted sets the "formatted" field.
func (_c *GroupHashtagCreate) SetFormatted(v string) *GroupHashtagCreate {
	_c.mutation.SetFormatted(v)
	return _c
}

// SetNillableFormatted sets the "formatted" field if the given value is not nil.
func (_c *GroupHashtagCreate) SetNillableFormatted(v *string) *GroupHashtagCreate {
	if v != nil {
		_c.SetFormatted(*v)
	}
	return _c
}

// SetRecommended sets the "recommended" field.
func (_c *GroupHashtagCreate) SetRecommended(v bool) *GroupHashtagCreate {
	_c.mutation.SetRecommended(v)
	return _c
}

// SetNillableRecommended sets the "recommended" field if the given value is not nil.
func (_c *GroupHashtagCreate) SetNillableRecommended(v *bool) *GroupHashtagCreate {
	if v != nil {
		_c.SetRecommended(*v)
	}
	return _c
}

// SetSensitive sets the "sensitive" field.
func (_c *GroupHashtagCreate) SetSensitive(v bool) *GroupHashtagCreate {
	_c.mutation.SetSensitive(v)
	return _c
}

// SetNillableSensitive sets the "sensitive" field if the given value is not nil.
func (_c *GroupHashtagCreate) SetNillableSensitive(v *bool) *GroupHashtagCreate {
	if v != nil {
		_c.SetSensitive(*v)
	}
	return _c
}

// SetBanned sets the "banned" field.
func (_c *GroupHashtagCreate) SetBanned(v bool) *GroupHashtagCreate {
	_c.mutation.SetBanned(v)
	return _c
}

// SetNillableBanned sets the "banned" field if the given value is not nil.
func (_c *GroupHashtagCreate) SetNillableBanned(v *bool) *GroupHashtagCreate {
	if v != nil {
		_c.SetBanned(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupHashtagCreate) SetCreatedAt(v time.Time) *GroupHashtagCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupHashtagCreate) SetNillableCreatedAt(v *time.Time) *GroupHashtagCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupHashtagCreate) SetUpdatedAt(v time.Time) *GroupHashtagCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupHashtagCreate) SetNillableUpdatedAt(v *time.Time) *GroupHashtagCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GroupHashtagCreate) SetID(v uint64) *GroupHashtagCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the GroupHashtagMutation object of the builder.
func (_c *GroupHashtagCreate) Mutation() *GroupHashtagMutation {
	return _c.mutation
}

// Save creates the GroupHashtag in the database.
func (_c *GroupHashtagCreate) Save(ctx context.Context) (*GroupHashtag, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupHashtagCreate) SaveX(ctx context.Context) *GroupHashtag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupHashtagCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupHashtagCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupHashtagCreate) defaults() {
	if _, ok := _c.mutation.Recommended(); !ok {
		v := grouphashtag.DefaultRecommended
		_c.mutation.SetRecommended(v)
	}
	if _, ok := _c.mutation.Sensitive(); !ok {
		v := grouphashtag.DefaultSensitive
		_c.mutation.SetSensitive(v)
	}
	if _, ok := _c.mutation.Banned(); !ok {
		v := grouphashtag.DefaultBanned
		_c.mutation.SetBanned(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := grouphashtag.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := grouphashtag.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupHashtagCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "GroupHashtag.name"`)}
	}
	if _, ok := _c.mutation.Recommended(); !ok {
		return &ValidationError{Name: "recommended", err: errors.New(`ent: missing required field "GroupHashtag.recommended"`)}
	}
	if _, ok := _c.mutation.Sensitive(); !ok {
		return &ValidationError{Name: "sensitive", err: errors.New(`ent: missing required field "GroupHashtag.sensitive"`)}
	}
	if _, ok := _c.mutation.Banned(); !ok {
		return &ValidationError{Name: "banned", err: errors.New(`ent: missing required field "GroupHashtag.banned"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupHashtag.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GroupHashtag.updated_at"`)}
	}
	return nil
}

func (_c *GroupHashtagCreate) sqlSave(ctx context.Context) (*GroupHashtag, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupHashtagCreate) createSpec() (*GroupHashtag, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupHashtag{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(grouphashtag.Table, sqlgraph.NewFieldSpec(grouphashtag.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(grouphashtag.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Formatted(); ok {
		_spec.SetField(grouphashtag.FieldFormatted, field.TypeString, value)
		_node.Formatted = value
	}
	if value, ok := _c.mutation.Recommended(); ok {
		_spec.SetField(grouphashtag.FieldRecommended, field.TypeBool, value)
		_node.Recommended = value
	}
	if value, ok := _c.mutation.Sensitive(); ok {
		_spec.SetField(grouphashtag.FieldSensitive, field.TypeBool, value)
		_node.Sensitive = value
	}
	if value, ok := _c.mutation.Banned(); ok {
		_spec.SetField(grouphashtag.FieldBanned, field.TypeBool, value)
		_node.Banned = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(grouphashtag.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(grouphashtag.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// GroupHashtagCreateBulk is the builder for creating many GroupHashtag entities in bulk.
type GroupHashtagCreateBulk struct {
	config
	err      error
	builders []*GroupHashtagCreate
}

// Save creates the GroupHashtag entities in the database.
func (_c *GroupHashtagCreateBulk) Save(ctx context.Context) ([]*GroupHashtag, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupHashtag, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupHashtagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupHashtagCreateBulk) SaveX(ctx context.Context) []*GroupHashtag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupHashtagCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupHashtagCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
