// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"glintfed.org/ent/importpost"
)

// ImportPost is the model entity for the ImportPost schema.
type ImportPost struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// ProfileID holds the value of the "profile_id" field.
	ProfileID uint64 `json:"profile_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uint64 `json:"user_id,omitempty"`
	// Service holds the value of the "service" field.
	Service string `json:"service,omitempty"`
	// PostHash holds the value of the "post_hash" field.
	PostHash string `json:"post_hash,omitempty"`
	// Filename holds the value of the "filename" field.
	Filename string `json:"filename,omitempty"`
	// MediaCount holds the value of the "media_count" field.
	MediaCount uint8 `json:"media_count,omitempty"`
	// PostType holds the value of the "post_type" field.
	PostType string `json:"post_type,omitempty"`
	// Caption holds the value of the "caption" field.
	Caption string `json:"caption,omitempty"`
	// Media holds the value of the "media" field.
	Media map[string]interface{} `json:"media,omitempty"`
	// CreationYear holds the value of the "creation_year" field.
	CreationYear uint8 `json:"creation_year,omitempty"`
	// CreationMonth holds the value of the "creation_month" field.
	CreationMonth uint8 `json:"creation_month,omitempty"`
	// CreationDay holds the value of the "creation_day" field.
	CreationDay uint8 `json:"creation_day,omitempty"`
	// CreationID holds the value of the "creation_id" field.
	CreationID uint8 `json:"creation_id,omitempty"`
	// StatusID holds the value of the "status_id" field.
	StatusID uint64 `json:"status_id,omitempty"`
	// CreationDate holds the value of the "creation_date" field.
	CreationDate time.Time `json:"creation_date,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// SkipMissingMedia holds the value of the "skip_missing_media" field.
	SkipMissingMedia bool `json:"skip_missing_media,omitempty"`
	// UploadedToS3 holds the value of the "uploaded_to_s3" field.
	UploadedToS3 bool `json:"uploaded_to_s3,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImportPost) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case importpost.FieldMedia, importpost.FieldMetadata:
			values[i] = new([]byte)
		case importpost.FieldSkipMissingMedia, importpost.FieldUploadedToS3:
			values[i] = new(sql.NullBool)
		case importpost.FieldID, importpost.FieldProfileID, importpost.FieldUserID, importpost.FieldMediaCount, importpost.FieldCreationYear, importpost.FieldCreationMonth, importpost.FieldCreationDay, importpost.FieldCreationID, importpost.FieldStatusID:
			values[i] = new(sql.NullInt64)
		case importpost.FieldService, importpost.FieldPostHash, importpost.FieldFilename, importpost.FieldPostType, importpost.FieldCaption:
			values[i] = new(sql.NullString)
		case importpost.FieldCreationDate, importpost.FieldCreatedAt, importpost.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImportPost fields.
func (_m *ImportPost) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case importpost.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case importpost.FieldProfileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field profile_id", values[i])
			} else if value.Valid {
				_m.ProfileID = uint64(value.Int64)
			}
		case importpost.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = uint64(value.Int64)
			}
		case importpost.FieldService:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service", values[i])
			} else if value.Valid {
				_m.Service = value.String
			}
		case importpost.FieldPostHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field post_hash", values[i])
			} else if value.Valid {
				_m.PostHash = value.String
			}
		case importpost.FieldFilename:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field filename", values[i])
			} else if value.Valid {
				_m.Filename = value.String
			}
		case importpost.FieldMediaCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field media_count", values[i])
			} else if value.Valid {
				_m.MediaCount = uint8(value.Int64)
			}
		case importpost.FieldPostType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field post_type", values[i])
			} else if value.Valid {
				_m.PostType = value.String
			}
		case importpost.FieldCaption:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field caption", values[i])
			} else if value.Valid {
				_m.Caption = value.String
			}
		case importpost.FieldMedia:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field media", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Media); err != nil {
					return fmt.Errorf("unmarshal field media: %w", err)
				}
			}
		case importpost.FieldCreationYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field creation_year", values[i])
			} else if value.Valid {
				_m.CreationYear = uint8(value.Int64)
			}
		case importpost.FieldCreationMonth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field creation_month", values[i])
			} else if value.Valid {
				_m.CreationMonth = uint8(value.Int64)
			}
		case importpost.FieldCreationDay:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field creation_day", values[i])
			} else if value.Valid {
				_m.CreationDay = uint8(value.Int64)
			}
		case importpost.FieldCreationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field creation_id", values[i])
			} else if value.Valid {
				_m.CreationID = uint8(value.Int64)
			}
		case importpost.FieldStatusID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_id", values[i])
			} else if value.Valid {
				_m.StatusID = uint64(value.Int64)
			}
		case importpost.FieldCreationDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field creation_date", values[i])
			} else if value.Valid {
				_m.CreationDate = value.Time
			}
		case importpost.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case importpost.FieldSkipMissingMedia:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field skip_missing_media", values[i])
			} else if value.Valid {
				_m.SkipMissingMedia = value.Bool
			}
		case importpost.FieldUploadedToS3:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field uploaded_to_s3", values[i])
			} else if value.Valid {
				_m.UploadedToS3 = value.Bool
			}
		case importpost.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case importpost.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImportPost.
// This includes values selected through modifiers, order, etc.
func (_m *ImportPost) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ImportPost.
// Note that you need to call ImportPost.Unwrap() before calling this method if this ImportPost
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImportPost) Update() *ImportPostUpdateOne {
	return NewImportPostClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImportPost entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImportPost) Unwrap() *ImportPost {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImportPost is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImportPost) String() string {
	var builder strings.Builder
	builder.WriteString("ImportPost(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("profile_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProfileID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("service=")
	builder.WriteString(_m.Service)
	builder.WriteString(", ")
	builder.WriteString("post_hash=")
	builder.WriteString(_m.PostHash)
	builder.WriteString(", ")
	builder.WriteString("filename=")
	builder.WriteString(_m.Filename)
	builder.WriteString(", ")
	builder.WriteString("media_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.MediaCount))
	builder.WriteString(", ")
	builder.WriteString("post_type=")
	builder.WriteString(_m.PostType)
	builder.WriteString(", ")
	builder.WriteString("caption=")
	builder.WriteString(_m.Caption)
	builder.WriteString(", ")
	builder.WriteString("media=")
	builder.WriteString(fmt.Sprintf("%v", _m.Media))
	builder.WriteString(", ")
	builder.WriteString("creation_year=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreationYear))
	builder.WriteString(", ")
	builder.WriteString("creation_month=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreationMonth))
	builder.WriteString(", ")
	builder.WriteString("creation_day=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreationDay))
	builder.WriteString(", ")
	builder.WriteString("creation_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreationID))
	builder.WriteString(", ")
	builder.WriteString("status_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StatusID))
	builder.WriteString(", ")
	builder.WriteString("creation_date=")
	builder.WriteString(_m.CreationDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("skip_missing_media=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkipMissingMedia))
	builder.WriteString(", ")
	builder.WriteString("uploaded_to_s3=")
	builder.WriteString(fmt.Sprintf("%v", _m.UploadedToS3))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ImportPosts is a parsable slice of ImportPost.
type ImportPosts []*ImportPost
