// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/newsroom"
)

// NewsroomCreate is the builder for creating a Newsroom entity.
type NewsroomCreate struct {
	config
	mutation *NewsroomMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *NewsroomCreate) SetUserID(v uint64) *NewsroomCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillableUserID(v *uint64) *NewsroomCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetHeaderPhotoURL sets the "header_photo_url" field.
func (_c *NewsroomCreate) SetHeaderPhotoURL(v string) *NewsroomCreate {
	_c.mutation.SetHeaderPhotoURL(v)
	return _c
}

// SetNillableHeaderPhotoURL sets the "header_photo_url" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillableHeaderPhotoURL(v *string) *NewsroomCreate {
	if v != nil {
		_c.SetHeaderPhotoURL(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *NewsroomCreate) SetTitle(v string) *NewsroomCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillableTitle(v *string) *NewsroomCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetSlug sets the "slug" field.
func (_c *NewsroomCreate) SetSlug(v string) *NewsroomCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillableSlug(v *string) *NewsroomCreate {
	if v != nil {
		_c.SetSlug(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *NewsroomCreate) SetCategory(v string) *NewsroomCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillableCategory(v *string) *NewsroomCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *NewsroomCreate) SetSummary(v string) *NewsroomCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillableSummary(v *string) *NewsroomCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetBody sets the "body" field.
func (_c *NewsroomCreate) SetBody(v string) *NewsroomCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillableBody(v *string) *NewsroomCreate {
	if v != nil {
		_c.SetBody(*v)
	}
	return _c
}

// SetBodyRendered sets the "body_rendered" field.
func (_c *NewsroomCreate) SetBodyRendered(v string) *NewsroomCreate {
	_c.mutation.SetBodyRendered(v)
	return _c
}

// SetNillableBodyRendered sets the "body_rendered" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillableBodyRendered(v *string) *NewsroomCreate {
	if v != nil {
		_c.SetBodyRendered(*v)
	}
	return _c
}

// SetLink sets the "link" field.
func (_c *NewsroomCreate) SetLink(v string) *NewsroomCreate {
	_c.mutation.SetLink(v)
	return _c
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillableLink(v *string) *NewsroomCreate {
	if v != nil {
		_c.SetLink(*v)
	}
	return _c
}

// SetForceModal sets the "force_modal" field.
func (_c *NewsroomCreate) SetForceModal(v bool) *NewsroomCreate {
	_c.mutation.SetForceModal(v)
	return _c
}

// SetNillableForceModal sets the "force_modal" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillableForceModal(v *bool) *NewsroomCreate {
	if v != nil {
		_c.SetForceModal(*v)
	}
	return _c
}

// SetShowTimeline sets the "show_timeline" field.
func (_c *NewsroomCreate) SetShowTimeline(v bool) *NewsroomCreate {
	_c.mutation.SetShowTimeline(v)
	return _c
}

// SetNillableShowTimeline sets the "show_timeline" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillableShowTimeline(v *bool) *NewsroomCreate {
	if v != nil {
		_c.SetShowTimeline(*v)
	}
	return _c
}

// SetShowLink sets the "show_link" field.
func (_c *NewsroomCreate) SetShowLink(v bool) *NewsroomCreate {
	_c.mutation.SetShowLink(v)
	return _c
}

// SetNillableShowLink sets the "show_link" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillableShowLink(v *bool) *NewsroomCreate {
	if v != nil {
		_c.SetShowLink(*v)
	}
	return _c
}

// SetAuthOnly sets the "auth_only" field.
func (_c *NewsroomCreate) SetAuthOnly(v bool) *NewsroomCreate {
	_c.mutation.SetAuthOnly(v)
	return _c
}

// SetNillableAuthOnly sets the "auth_only" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillableAuthOnly(v *bool) *NewsroomCreate {
	if v != nil {
		_c.SetAuthOnly(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *NewsroomCreate) SetPublishedAt(v time.Time) *NewsroomCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillablePublishedAt(v *time.Time) *NewsroomCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NewsroomCreate) SetCreatedAt(v time.Time) *NewsroomCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillableCreatedAt(v *time.Time) *NewsroomCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NewsroomCreate) SetUpdatedAt(v time.Time) *NewsroomCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NewsroomCreate) SetNillableUpdatedAt(v *time.Time) *NewsroomCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NewsroomCreate) SetID(v uint64) *NewsroomCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the NewsroomMutation object of the builder.
func (_c *NewsroomCreate) Mutation() *NewsroomMutation {
	return _c.mutation
}

// Save creates the Newsroom in the database.
func (_c *NewsroomCreate) Save(ctx context.Context) (*Newsroom, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NewsroomCreate) SaveX(ctx context.Context) *Newsroom {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NewsroomCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NewsroomCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NewsroomCreate) defaults() {
	if _, ok := _c.mutation.Category(); !ok {
		v := newsroom.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.ForceModal(); !ok {
		v := newsroom.DefaultForceModal
		_c.mutation.SetForceModal(v)
	}
	if _, ok := _c.mutation.ShowTimeline(); !ok {
		v := newsroom.DefaultShowTimeline
		_c.mutation.SetShowTimeline(v)
	}
	if _, ok := _c.mutation.ShowLink(); !ok {
		v := newsroom.DefaultShowLink
		_c.mutation.SetShowLink(v)
	}
	if _, ok := _c.mutation.AuthOnly(); !ok {
		v := newsroom.DefaultAuthOnly
		_c.mutation.SetAuthOnly(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := newsroom.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := newsroom.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NewsroomCreate) check() error {
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Newsroom.category"`)}
	}
	if _, ok := _c.mutation.ForceModal(); !ok {
		return &ValidationError{Name: "force_modal", err: errors.New(`ent: missing required field "Newsroom.force_modal"`)}
	}
	if _, ok := _c.mutation.ShowTimeline(); !ok {
		return &ValidationError{Name: "show_timeline", err: errors.New(`ent: missing required field "Newsroom.show_timeline"`)}
	}
	if _, ok := _c.mutation.ShowLink(); !ok {
		return &ValidationError{Name: "show_link", err: errors.New(`ent: missing required field "Newsroom.show_link"`)}
	}
	if _, ok := _c.mutation.AuthOnly(); !ok {
		return &ValidationError{Name: "auth_only", err: errors.New(`ent: missing required field "Newsroom.auth_only"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Newsroom.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Newsroom.updated_at"`)}
	}
	return nil
}

func (_c *NewsroomCreate) sqlSave(ctx context.Context) (*Newsroom, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NewsroomCreate) createSpec() (*Newsroom, *sqlgraph.CreateSpec) {
	var (
		_node = &Newsroom{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(newsroom.Table, sqlgraph.NewFieldSpec(newsroom.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(newsroom.FieldUserID, field.TypeUint64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.HeaderPhotoURL(); ok {
		_spec.SetField(newsroom.FieldHeaderPhotoURL, field.TypeString, value)
		_node.HeaderPhotoURL = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(newsroom.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(newsroom.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(newsroom.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(newsroom.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(newsroom.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.BodyRendered(); ok {
		_spec.SetField(newsroom.FieldBodyRendered, field.TypeString, value)
		_node.BodyRendered = value
	}
	if value, ok := _c.mutation.Link(); ok {
		_spec.SetField(newsroom.FieldLink, field.TypeString, value)
		_node.Link = value
	}
	if value, ok := _c.mutation.ForceModal(); ok {
		_spec.SetField(newsroom.FieldForceModal, field.TypeBool, value)
		_node.ForceModal = value
	}
	if value, ok := _c.mutation.ShowTimeline(); ok {
		_spec.SetField(newsroom.FieldShowTimeline, field.TypeBool, value)
		_node.ShowTimeline = value
	}
	if value, ok := _c.mutation.ShowLink(); ok {
		_spec.SetField(newsroom.FieldShowLink, field.TypeBool, value)
		_node.ShowLink = value
	}
	if value, ok := _c.mutation.AuthOnly(); ok {
		_spec.SetField(newsroom.FieldAuthOnly, field.TypeBool, value)
		_node.AuthOnly = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(newsroom.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(newsroom.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(newsroom.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// NewsroomCreateBulk is the builder for creating many Newsroom entities in bulk.
type NewsroomCreateBulk struct {
	config
	err      error
	builders []*NewsroomCreate
}

// Save creates the Newsroom entities in the database.
func (_c *NewsroomCreateBulk) Save(ctx context.Context) ([]*Newsroom, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Newsroom, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NewsroomMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NewsroomCreateBulk) SaveX(ctx context.Context) []*Newsroom {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NewsroomCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NewsroomCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
