// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/oauthauthorizationcode"
	"glintfed.org/ent/predicate"
)

// OauthAuthorizationCodeUpdate is the builder for updating OauthAuthorizationCode entities.
type OauthAuthorizationCodeUpdate struct {
	config
	hooks    []Hook
	mutation *OauthAuthorizationCodeMutation
}

// Where appends a list predicates to the OauthAuthorizationCodeUpdate builder.
func (_u *OauthAuthorizationCodeUpdate) Where(ps ...predicate.OauthAuthorizationCode) *OauthAuthorizationCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OauthAuthorizationCodeUpdate) SetUserID(v uint64) *OauthAuthorizationCodeUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OauthAuthorizationCodeUpdate) SetNillableUserID(v *uint64) *OauthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OauthAuthorizationCodeUpdate) AddUserID(v int64) *OauthAuthorizationCodeUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OauthAuthorizationCodeUpdate) SetClientID(v uint64) *OauthAuthorizationCodeUpdate {
	_u.mutation.ResetClientID()
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OauthAuthorizationCodeUpdate) SetNillableClientID(v *uint64) *OauthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// AddClientID adds value to the "client_id" field.
func (_u *OauthAuthorizationCodeUpdate) AddClientID(v int64) *OauthAuthorizationCodeUpdate {
	_u.mutation.AddClientID(v)
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OauthAuthorizationCodeUpdate) SetScopes(v string) *OauthAuthorizationCodeUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// SetNillableScopes sets the "scopes" field if the given value is not nil.
func (_u *OauthAuthorizationCodeUpdate) SetNillableScopes(v *string) *OauthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetScopes(*v)
	}
	return _u
}

// ClearScopes clears the value of the "scopes" field.
func (_u *OauthAuthorizationCodeUpdate) ClearScopes() *OauthAuthorizationCodeUpdate {
	_u.mutation.ClearScopes()
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *OauthAuthorizationCodeUpdate) SetRevoked(v bool) *OauthAuthorizationCodeUpdate {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *OauthAuthorizationCodeUpdate) SetNillableRevoked(v *bool) *OauthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OauthAuthorizationCodeUpdate) SetExpiresAt(v time.Time) *OauthAuthorizationCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OauthAuthorizationCodeUpdate) SetNillableExpiresAt(v *time.Time) *OauthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *OauthAuthorizationCodeUpdate) ClearExpiresAt() *OauthAuthorizationCodeUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the OauthAuthorizationCodeMutation object of the builder.
func (_u *OauthAuthorizationCodeUpdate) Mutation() *OauthAuthorizationCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OauthAuthorizationCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OauthAuthorizationCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OauthAuthorizationCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OauthAuthorizationCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OauthAuthorizationCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(oauthauthorizationcode.Table, oauthauthorizationcode.Columns, sqlgraph.NewFieldSpec(oauthauthorizationcode.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(oauthauthorizationcode.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldClientID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedClientID(); ok {
		_spec.AddField(oauthauthorizationcode.FieldClientID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthauthorizationcode.FieldScopes, field.TypeString, value)
	}
	if _u.mutation.ScopesCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldScopes, field.TypeString)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(oauthauthorizationcode.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthauthorizationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthauthorizationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OauthAuthorizationCodeUpdateOne is the builder for updating a single OauthAuthorizationCode entity.
type OauthAuthorizationCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OauthAuthorizationCodeMutation
}

// SetUserID sets the "user_id" field.
func (_u *OauthAuthorizationCodeUpdateOne) SetUserID(v uint64) *OauthAuthorizationCodeUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OauthAuthorizationCodeUpdateOne) SetNillableUserID(v *uint64) *OauthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OauthAuthorizationCodeUpdateOne) AddUserID(v int64) *OauthAuthorizationCodeUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OauthAuthorizationCodeUpdateOne) SetClientID(v uint64) *OauthAuthorizationCodeUpdateOne {
	_u.mutation.ResetClientID()
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OauthAuthorizationCodeUpdateOne) SetNillableClientID(v *uint64) *OauthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// AddClientID adds value to the "client_id" field.
func (_u *OauthAuthorizationCodeUpdateOne) AddClientID(v int64) *OauthAuthorizationCodeUpdateOne {
	_u.mutation.AddClientID(v)
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OauthAuthorizationCodeUpdateOne) SetScopes(v string) *OauthAuthorizationCodeUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// SetNillableScopes sets the "scopes" field if the given value is not nil.
func (_u *OauthAuthorizationCodeUpdateOne) SetNillableScopes(v *string) *OauthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetScopes(*v)
	}
	return _u
}

// ClearScopes clears the value of the "scopes" field.
func (_u *OauthAuthorizationCodeUpdateOne) ClearScopes() *OauthAuthorizationCodeUpdateOne {
	_u.mutation.ClearScopes()
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *OauthAuthorizationCodeUpdateOne) SetRevoked(v bool) *OauthAuthorizationCodeUpdateOne {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *OauthAuthorizationCodeUpdateOne) SetNillableRevoked(v *bool) *OauthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OauthAuthorizationCodeUpdateOne) SetExpiresAt(v time.Time) *OauthAuthorizationCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OauthAuthorizationCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *OauthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *OauthAuthorizationCodeUpdateOne) ClearExpiresAt() *OauthAuthorizationCodeUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the OauthAuthorizationCodeMutation object of the builder.
func (_u *OauthAuthorizationCodeUpdateOne) Mutation() *OauthAuthorizationCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the OauthAuthorizationCodeUpdate builder.
func (_u *OauthAuthorizationCodeUpdateOne) Where(ps ...predicate.OauthAuthorizationCode) *OauthAuthorizationCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OauthAuthorizationCodeUpdateOne) Select(field string, fields ...string) *OauthAuthorizationCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OauthAuthorizationCode entity.
func (_u *OauthAuthorizationCodeUpdateOne) Save(ctx context.Context) (*OauthAuthorizationCode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OauthAuthorizationCodeUpdateOne) SaveX(ctx context.Context) *OauthAuthorizationCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OauthAuthorizationCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OauthAuthorizationCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OauthAuthorizationCodeUpdateOne) sqlSave(ctx context.Context) (_node *OauthAuthorizationCode, err error) {
	_spec := sqlgraph.NewUpdateSpec(oauthauthorizationcode.Table, oauthauthorizationcode.Columns, sqlgraph.NewFieldSpec(oauthauthorizationcode.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OauthAuthorizationCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthauthorizationcode.FieldID)
		for _, f := range fields {
			if !oauthauthorizationcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthauthorizationcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(oauthauthorizationcode.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldClientID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedClientID(); ok {
		_spec.AddField(oauthauthorizationcode.FieldClientID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthauthorizationcode.FieldScopes, field.TypeString, value)
	}
	if _u.mutation.ScopesCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldScopes, field.TypeString)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(oauthauthorizationcode.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthauthorizationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldExpiresAt, field.TypeTime)
	}
	_node = &OauthAuthorizationCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthauthorizationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
