// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/portfolio"
)

// PortfolioCreate is the builder for creating a Portfolio entity.
type PortfolioCreate struct {
	config
	mutation *PortfolioMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *PortfolioCreate) SetUserID(v uint64) *PortfolioCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *PortfolioCreate) SetNillableUserID(v *uint64) *PortfolioCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetProfileID sets the "profile_id" field.
func (_c *PortfolioCreate) SetProfileID(v uint64) *PortfolioCreate {
	_c.mutation.SetProfileID(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *PortfolioCreate) SetActive(v bool) *PortfolioCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *PortfolioCreate) SetNillableActive(v *bool) *PortfolioCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetShowCaptions sets the "show_captions" field.
func (_c *PortfolioCreate) SetShowCaptions(v bool) *PortfolioCreate {
	_c.mutation.SetShowCaptions(v)
	return _c
}

// SetNillableShowCaptions sets the "show_captions" field if the given value is not nil.
func (_c *PortfolioCreate) SetNillableShowCaptions(v *bool) *PortfolioCreate {
	if v != nil {
		_c.SetShowCaptions(*v)
	}
	return _c
}

// SetShowLicense sets the "show_license" field.
func (_c *PortfolioCreate) SetShowLicense(v bool) *PortfolioCreate {
	_c.mutation.SetShowLicense(v)
	return _c
}

// SetNillableShowLicense sets the "show_license" field if the given value is not nil.
func (_c *PortfolioCreate) SetNillableShowLicense(v *bool) *PortfolioCreate {
	if v != nil {
		_c.SetShowLicense(*v)
	}
	return _c
}

// SetShowLocation sets the "show_location" field.
func (_c *PortfolioCreate) SetShowLocation(v bool) *PortfolioCreate {
	_c.mutation.SetShowLocation(v)
	return _c
}

// SetNillableShowLocation sets the "show_location" field if the given value is not nil.
func (_c *PortfolioCreate) SetNillableShowLocation(v *bool) *PortfolioCreate {
	if v != nil {
		_c.SetShowLocation(*v)
	}
	return _c
}

// SetShowTimestamp sets the "show_timestamp" field.
func (_c *PortfolioCreate) SetShowTimestamp(v bool) *PortfolioCreate {
	_c.mutation.SetShowTimestamp(v)
	return _c
}

// SetNillableShowTimestamp sets the "show_timestamp" field if the given value is not nil.
func (_c *PortfolioCreate) SetNillableShowTimestamp(v *bool) *PortfolioCreate {
	if v != nil {
		_c.SetShowTimestamp(*v)
	}
	return _c
}

// SetShowLink sets the "show_link" field.
func (_c *PortfolioCreate) SetShowLink(v bool) *PortfolioCreate {
	_c.mutation.SetShowLink(v)
	return _c
}

// SetNillableShowLink sets the "show_link" field if the given value is not nil.
func (_c *PortfolioCreate) SetNillableShowLink(v *bool) *PortfolioCreate {
	if v != nil {
		_c.SetShowLink(*v)
	}
	return _c
}

// SetProfileSource sets the "profile_source" field.
func (_c *PortfolioCreate) SetProfileSource(v string) *PortfolioCreate {
	_c.mutation.SetProfileSource(v)
	return _c
}

// SetNillableProfileSource sets the "profile_source" field if the given value is not nil.
func (_c *PortfolioCreate) SetNillableProfileSource(v *string) *PortfolioCreate {
	if v != nil {
		_c.SetProfileSource(*v)
	}
	return _c
}

// SetShowAvatar sets the "show_avatar" field.
func (_c *PortfolioCreate) SetShowAvatar(v bool) *PortfolioCreate {
	_c.mutation.SetShowAvatar(v)
	return _c
}

// SetNillableShowAvatar sets the "show_avatar" field if the given value is not nil.
func (_c *PortfolioCreate) SetNillableShowAvatar(v *bool) *PortfolioCreate {
	if v != nil {
		_c.SetShowAvatar(*v)
	}
	return _c
}

// SetShowBio sets the "show_bio" field.
func (_c *PortfolioCreate) SetShowBio(v bool) *PortfolioCreate {
	_c.mutation.SetShowBio(v)
	return _c
}

// SetNillableShowBio sets the "show_bio" field if the given value is not nil.
func (_c *PortfolioCreate) SetNillableShowBio(v *bool) *PortfolioCreate {
	if v != nil {
		_c.SetShowBio(*v)
	}
	return _c
}

// SetProfileLayout sets the "profile_layout" field.
func (_c *PortfolioCreate) SetProfileLayout(v string) *PortfolioCreate {
	_c.mutation.SetProfileLayout(v)
	return _c
}

// SetNillableProfileLayout sets the "profile_layout" field if the given value is not nil.
func (_c *PortfolioCreate) SetNillableProfileLayout(v *string) *PortfolioCreate {
	if v != nil {
		_c.SetProfileLayout(*v)
	}
	return _c
}

// SetProfileContainer sets the "profile_container" field.
func (_c *PortfolioCreate) SetProfileContainer(v string) *PortfolioCreate {
	_c.mutation.SetProfileContainer(v)
	return _c
}

// SetNillableProfileContainer sets the "profile_container" field if the given value is not nil.
func (_c *PortfolioCreate) SetNillableProfileContainer(v *string) *PortfolioCreate {
	if v != nil {
		_c.SetProfileContainer(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *PortfolioCreate) SetMetadata(v map[string]interface{}) *PortfolioCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PortfolioCreate) SetCreatedAt(v time.Time) *PortfolioCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PortfolioCreate) SetNillableCreatedAt(v *time.Time) *PortfolioCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PortfolioCreate) SetUpdatedAt(v time.Time) *PortfolioCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PortfolioCreate) SetNillableUpdatedAt(v *time.Time) *PortfolioCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PortfolioCreate) SetID(v uint64) *PortfolioCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PortfolioMutation object of the builder.
func (_c *PortfolioCreate) Mutation() *PortfolioMutation {
	return _c.mutation
}

// Save creates the Portfolio in the database.
func (_c *PortfolioCreate) Save(ctx context.Context) (*Portfolio, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PortfolioCreate) SaveX(ctx context.Context) *Portfolio {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PortfolioCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PortfolioCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PortfolioCreate) defaults() {
	if _, ok := _c.mutation.ShowCaptions(); !ok {
		v := portfolio.DefaultShowCaptions
		_c.mutation.SetShowCaptions(v)
	}
	if _, ok := _c.mutation.ShowLicense(); !ok {
		v := portfolio.DefaultShowLicense
		_c.mutation.SetShowLicense(v)
	}
	if _, ok := _c.mutation.ShowLocation(); !ok {
		v := portfolio.DefaultShowLocation
		_c.mutation.SetShowLocation(v)
	}
	if _, ok := _c.mutation.ShowTimestamp(); !ok {
		v := portfolio.DefaultShowTimestamp
		_c.mutation.SetShowTimestamp(v)
	}
	if _, ok := _c.mutation.ShowLink(); !ok {
		v := portfolio.DefaultShowLink
		_c.mutation.SetShowLink(v)
	}
	if _, ok := _c.mutation.ProfileSource(); !ok {
		v := portfolio.DefaultProfileSource
		_c.mutation.SetProfileSource(v)
	}
	if _, ok := _c.mutation.ShowAvatar(); !ok {
		v := portfolio.DefaultShowAvatar
		_c.mutation.SetShowAvatar(v)
	}
	if _, ok := _c.mutation.ShowBio(); !ok {
		v := portfolio.DefaultShowBio
		_c.mutation.SetShowBio(v)
	}
	if _, ok := _c.mutation.ProfileLayout(); !ok {
		v := portfolio.DefaultProfileLayout
		_c.mutation.SetProfileLayout(v)
	}
	if _, ok := _c.mutation.ProfileContainer(); !ok {
		v := portfolio.DefaultProfileContainer
		_c.mutation.SetProfileContainer(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := portfolio.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := portfolio.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PortfolioCreate) check() error {
	if _, ok := _c.mutation.ProfileID(); !ok {
		return &ValidationError{Name: "profile_id", err: errors.New(`ent: missing required field "Portfolio.profile_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Portfolio.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Portfolio.updated_at"`)}
	}
	return nil
}

func (_c *PortfolioCreate) sqlSave(ctx context.Context) (*Portfolio, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PortfolioCreate) createSpec() (*Portfolio, *sqlgraph.CreateSpec) {
	var (
		_node = &Portfolio{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(portfolio.Table, sqlgraph.NewFieldSpec(portfolio.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(portfolio.FieldUserID, field.TypeUint64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ProfileID(); ok {
		_spec.SetField(portfolio.FieldProfileID, field.TypeUint64, value)
		_node.ProfileID = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(portfolio.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.ShowCaptions(); ok {
		_spec.SetField(portfolio.FieldShowCaptions, field.TypeBool, value)
		_node.ShowCaptions = value
	}
	if value, ok := _c.mutation.ShowLicense(); ok {
		_spec.SetField(portfolio.FieldShowLicense, field.TypeBool, value)
		_node.ShowLicense = value
	}
	if value, ok := _c.mutation.ShowLocation(); ok {
		_spec.SetField(portfolio.FieldShowLocation, field.TypeBool, value)
		_node.ShowLocation = value
	}
	if value, ok := _c.mutation.ShowTimestamp(); ok {
		_spec.SetField(portfolio.FieldShowTimestamp, field.TypeBool, value)
		_node.ShowTimestamp = value
	}
	if value, ok := _c.mutation.ShowLink(); ok {
		_spec.SetField(portfolio.FieldShowLink, field.TypeBool, value)
		_node.ShowLink = value
	}
	if value, ok := _c.mutation.ProfileSource(); ok {
		_spec.SetField(portfolio.FieldProfileSource, field.TypeString, value)
		_node.ProfileSource = value
	}
	if value, ok := _c.mutation.ShowAvatar(); ok {
		_spec.SetField(portfolio.FieldShowAvatar, field.TypeBool, value)
		_node.ShowAvatar = value
	}
	if value, ok := _c.mutation.ShowBio(); ok {
		_spec.SetField(portfolio.FieldShowBio, field.TypeBool, value)
		_node.ShowBio = value
	}
	if value, ok := _c.mutation.ProfileLayout(); ok {
		_spec.SetField(portfolio.FieldProfileLayout, field.TypeString, value)
		_node.ProfileLayout = value
	}
	if value, ok := _c.mutation.ProfileContainer(); ok {
		_spec.SetField(portfolio.FieldProfileContainer, field.TypeString, value)
		_node.ProfileContainer = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(portfolio.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(portfolio.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(portfolio.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PortfolioCreateBulk is the builder for creating many Portfolio entities in bulk.
type PortfolioCreateBulk struct {
	config
	err      error
	builders []*PortfolioCreate
}

// Save creates the Portfolio entities in the database.
func (_c *PortfolioCreateBulk) Save(ctx context.Context) ([]*Portfolio, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Portfolio, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PortfolioMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PortfolioCreateBulk) SaveX(ctx context.Context) []*Portfolio {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PortfolioCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PortfolioCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
