// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/profile"
	"glintfed.org/ent/story"
)

// ProfileCreate is the builder for creating a Profile entity.
type ProfileCreate struct {
	config
	mutation *ProfileMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *ProfileCreate) SetUserID(v uint64) *ProfileCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableUserID(v *uint64) *ProfileCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetDomain sets the "domain" field.
func (_c *ProfileCreate) SetDomain(v string) *ProfileCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableDomain(v *string) *ProfileCreate {
	if v != nil {
		_c.SetDomain(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *ProfileCreate) SetUsername(v string) *ProfileCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableUsername(v *string) *ProfileCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProfileCreate) SetStatus(v string) *ProfileCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableStatus(v *string) *ProfileCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ProfileCreate) SetName(v string) *ProfileCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableName(v *string) *ProfileCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetBio sets the "bio" field.
func (_c *ProfileCreate) SetBio(v string) *ProfileCreate {
	_c.mutation.SetBio(v)
	return _c
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableBio(v *string) *ProfileCreate {
	if v != nil {
		_c.SetBio(*v)
	}
	return _c
}

// SetUnlisted sets the "unlisted" field.
func (_c *ProfileCreate) SetUnlisted(v bool) *ProfileCreate {
	_c.mutation.SetUnlisted(v)
	return _c
}

// SetNillableUnlisted sets the "unlisted" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableUnlisted(v *bool) *ProfileCreate {
	if v != nil {
		_c.SetUnlisted(*v)
	}
	return _c
}

// SetCw sets the "cw" field.
func (_c *ProfileCreate) SetCw(v bool) *ProfileCreate {
	_c.mutation.SetCw(v)
	return _c
}

// SetNillableCw sets the "cw" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableCw(v *bool) *ProfileCreate {
	if v != nil {
		_c.SetCw(*v)
	}
	return _c
}

// SetNoAutolink sets the "no_autolink" field.
func (_c *ProfileCreate) SetNoAutolink(v bool) *ProfileCreate {
	_c.mutation.SetNoAutolink(v)
	return _c
}

// SetNillableNoAutolink sets the "no_autolink" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableNoAutolink(v *bool) *ProfileCreate {
	if v != nil {
		_c.SetNoAutolink(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *ProfileCreate) SetLocation(v string) *ProfileCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableLocation(v *string) *ProfileCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetWebsite sets the "website" field.
func (_c *ProfileCreate) SetWebsite(v string) *ProfileCreate {
	_c.mutation.SetWebsite(v)
	return _c
}

// SetNillableWebsite sets the "website" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableWebsite(v *string) *ProfileCreate {
	if v != nil {
		_c.SetWebsite(*v)
	}
	return _c
}

// SetProfileLayout sets the "profile_layout" field.
func (_c *ProfileCreate) SetProfileLayout(v string) *ProfileCreate {
	_c.mutation.SetProfileLayout(v)
	return _c
}

// SetNillableProfileLayout sets the "profile_layout" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableProfileLayout(v *string) *ProfileCreate {
	if v != nil {
		_c.SetProfileLayout(*v)
	}
	return _c
}

// SetHeaderBg sets the "header_bg" field.
func (_c *ProfileCreate) SetHeaderBg(v string) *ProfileCreate {
	_c.mutation.SetHeaderBg(v)
	return _c
}

// SetNillableHeaderBg sets the "header_bg" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableHeaderBg(v *string) *ProfileCreate {
	if v != nil {
		_c.SetHeaderBg(*v)
	}
	return _c
}

// SetPostLayout sets the "post_layout" field.
func (_c *ProfileCreate) SetPostLayout(v string) *ProfileCreate {
	_c.mutation.SetPostLayout(v)
	return _c
}

// SetNillablePostLayout sets the "post_layout" field if the given value is not nil.
func (_c *ProfileCreate) SetNillablePostLayout(v *string) *ProfileCreate {
	if v != nil {
		_c.SetPostLayout(*v)
	}
	return _c
}

// SetIsPrivate sets the "is_private" field.
func (_c *ProfileCreate) SetIsPrivate(v bool) *ProfileCreate {
	_c.mutation.SetIsPrivate(v)
	return _c
}

// SetNillableIsPrivate sets the "is_private" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableIsPrivate(v *bool) *ProfileCreate {
	if v != nil {
		_c.SetIsPrivate(*v)
	}
	return _c
}

// SetSharedInbox sets the "shared_inbox" field.
func (_c *ProfileCreate) SetSharedInbox(v string) *ProfileCreate {
	_c.mutation.SetSharedInbox(v)
	return _c
}

// SetNillableSharedInbox sets the "shared_inbox" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableSharedInbox(v *string) *ProfileCreate {
	if v != nil {
		_c.SetSharedInbox(*v)
	}
	return _c
}

// SetInboxURL sets the "inbox_url" field.
func (_c *ProfileCreate) SetInboxURL(v string) *ProfileCreate {
	_c.mutation.SetInboxURL(v)
	return _c
}

// SetNillableInboxURL sets the "inbox_url" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableInboxURL(v *string) *ProfileCreate {
	if v != nil {
		_c.SetInboxURL(*v)
	}
	return _c
}

// SetOutboxURL sets the "outbox_url" field.
func (_c *ProfileCreate) SetOutboxURL(v string) *ProfileCreate {
	_c.mutation.SetOutboxURL(v)
	return _c
}

// SetNillableOutboxURL sets the "outbox_url" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableOutboxURL(v *string) *ProfileCreate {
	if v != nil {
		_c.SetOutboxURL(*v)
	}
	return _c
}

// SetKeyID sets the "key_id" field.
func (_c *ProfileCreate) SetKeyID(v string) *ProfileCreate {
	_c.mutation.SetKeyID(v)
	return _c
}

// SetNillableKeyID sets the "key_id" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableKeyID(v *string) *ProfileCreate {
	if v != nil {
		_c.SetKeyID(*v)
	}
	return _c
}

// SetFollowerURL sets the "follower_url" field.
func (_c *ProfileCreate) SetFollowerURL(v string) *ProfileCreate {
	_c.mutation.SetFollowerURL(v)
	return _c
}

// SetNillableFollowerURL sets the "follower_url" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableFollowerURL(v *string) *ProfileCreate {
	if v != nil {
		_c.SetFollowerURL(*v)
	}
	return _c
}

// SetFollowingURL sets the "following_url" field.
func (_c *ProfileCreate) SetFollowingURL(v string) *ProfileCreate {
	_c.mutation.SetFollowingURL(v)
	return _c
}

// SetNillableFollowingURL sets the "following_url" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableFollowingURL(v *string) *ProfileCreate {
	if v != nil {
		_c.SetFollowingURL(*v)
	}
	return _c
}

// SetPrivateKey sets the "private_key" field.
func (_c *ProfileCreate) SetPrivateKey(v string) *ProfileCreate {
	_c.mutation.SetPrivateKey(v)
	return _c
}

// SetNillablePrivateKey sets the "private_key" field if the given value is not nil.
func (_c *ProfileCreate) SetNillablePrivateKey(v *string) *ProfileCreate {
	if v != nil {
		_c.SetPrivateKey(*v)
	}
	return _c
}

// SetPublicKey sets the "public_key" field.
func (_c *ProfileCreate) SetPublicKey(v string) *ProfileCreate {
	_c.mutation.SetPublicKey(v)
	return _c
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_c *ProfileCreate) SetNillablePublicKey(v *string) *ProfileCreate {
	if v != nil {
		_c.SetPublicKey(*v)
	}
	return _c
}

// SetRemoteURL sets the "remote_url" field.
func (_c *ProfileCreate) SetRemoteURL(v string) *ProfileCreate {
	_c.mutation.SetRemoteURL(v)
	return _c
}

// SetNillableRemoteURL sets the "remote_url" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableRemoteURL(v *string) *ProfileCreate {
	if v != nil {
		_c.SetRemoteURL(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProfileCreate) SetCreatedAt(v time.Time) *ProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableCreatedAt(v *time.Time) *ProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProfileCreate) SetUpdatedAt(v time.Time) *ProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableUpdatedAt(v *time.Time) *ProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ProfileCreate) SetDeletedAt(v time.Time) *ProfileCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableDeletedAt(v *time.Time) *ProfileCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeleteAfter sets the "delete_after" field.
func (_c *ProfileCreate) SetDeleteAfter(v time.Time) *ProfileCreate {
	_c.mutation.SetDeleteAfter(v)
	return _c
}

// SetNillableDeleteAfter sets the "delete_after" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableDeleteAfter(v *time.Time) *ProfileCreate {
	if v != nil {
		_c.SetDeleteAfter(*v)
	}
	return _c
}

// SetIsSuggestable sets the "is_suggestable" field.
func (_c *ProfileCreate) SetIsSuggestable(v bool) *ProfileCreate {
	_c.mutation.SetIsSuggestable(v)
	return _c
}

// SetNillableIsSuggestable sets the "is_suggestable" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableIsSuggestable(v *bool) *ProfileCreate {
	if v != nil {
		_c.SetIsSuggestable(*v)
	}
	return _c
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (_c *ProfileCreate) SetLastFetchedAt(v time.Time) *ProfileCreate {
	_c.mutation.SetLastFetchedAt(v)
	return _c
}

// SetNillableLastFetchedAt sets the "last_fetched_at" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableLastFetchedAt(v *time.Time) *ProfileCreate {
	if v != nil {
		_c.SetLastFetchedAt(*v)
	}
	return _c
}

// SetStatusCount sets the "status_count" field.
func (_c *ProfileCreate) SetStatusCount(v uint32) *ProfileCreate {
	_c.mutation.SetStatusCount(v)
	return _c
}

// SetNillableStatusCount sets the "status_count" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableStatusCount(v *uint32) *ProfileCreate {
	if v != nil {
		_c.SetStatusCount(*v)
	}
	return _c
}

// SetFollowersCount sets the "followers_count" field.
func (_c *ProfileCreate) SetFollowersCount(v uint32) *ProfileCreate {
	_c.mutation.SetFollowersCount(v)
	return _c
}

// SetNillableFollowersCount sets the "followers_count" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableFollowersCount(v *uint32) *ProfileCreate {
	if v != nil {
		_c.SetFollowersCount(*v)
	}
	return _c
}

// SetFollowingCount sets the "following_count" field.
func (_c *ProfileCreate) SetFollowingCount(v uint32) *ProfileCreate {
	_c.mutation.SetFollowingCount(v)
	return _c
}

// SetNillableFollowingCount sets the "following_count" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableFollowingCount(v *uint32) *ProfileCreate {
	if v != nil {
		_c.SetFollowingCount(*v)
	}
	return _c
}

// SetWebfinger sets the "webfinger" field.
func (_c *ProfileCreate) SetWebfinger(v string) *ProfileCreate {
	_c.mutation.SetWebfinger(v)
	return _c
}

// SetNillableWebfinger sets the "webfinger" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableWebfinger(v *string) *ProfileCreate {
	if v != nil {
		_c.SetWebfinger(*v)
	}
	return _c
}

// SetAvatarURL sets the "avatar_url" field.
func (_c *ProfileCreate) SetAvatarURL(v string) *ProfileCreate {
	_c.mutation.SetAvatarURL(v)
	return _c
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableAvatarURL(v *string) *ProfileCreate {
	if v != nil {
		_c.SetAvatarURL(*v)
	}
	return _c
}

// SetLastStatusAt sets the "last_status_at" field.
func (_c *ProfileCreate) SetLastStatusAt(v time.Time) *ProfileCreate {
	_c.mutation.SetLastStatusAt(v)
	return _c
}

// SetNillableLastStatusAt sets the "last_status_at" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableLastStatusAt(v *time.Time) *ProfileCreate {
	if v != nil {
		_c.SetLastStatusAt(*v)
	}
	return _c
}

// SetMovedToProfileID sets the "moved_to_profile_id" field.
func (_c *ProfileCreate) SetMovedToProfileID(v uint64) *ProfileCreate {
	_c.mutation.SetMovedToProfileID(v)
	return _c
}

// SetNillableMovedToProfileID sets the "moved_to_profile_id" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableMovedToProfileID(v *uint64) *ProfileCreate {
	if v != nil {
		_c.SetMovedToProfileID(*v)
	}
	return _c
}

// SetIndexable sets the "indexable" field.
func (_c *ProfileCreate) SetIndexable(v bool) *ProfileCreate {
	_c.mutation.SetIndexable(v)
	return _c
}

// SetNillableIndexable sets the "indexable" field if the given value is not nil.
func (_c *ProfileCreate) SetNillableIndexable(v *bool) *ProfileCreate {
	if v != nil {
		_c.SetIndexable(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProfileCreate) SetID(v uint64) *ProfileCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddStoryIDs adds the "stories" edge to the Story entity by IDs.
func (_c *ProfileCreate) AddStoryIDs(ids ...uint64) *ProfileCreate {
	_c.mutation.AddStoryIDs(ids...)
	return _c
}

// AddStories adds the "stories" edges to the Story entity.
func (_c *ProfileCreate) AddStories(v ...*Story) *ProfileCreate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStoryIDs(ids...)
}

// Mutation returns the ProfileMutation object of the builder.
func (_c *ProfileCreate) Mutation() *ProfileMutation {
	return _c.mutation
}

// Save creates the Profile in the database.
func (_c *ProfileCreate) Save(ctx context.Context) (*Profile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProfileCreate) SaveX(ctx context.Context) *Profile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProfileCreate) defaults() {
	if _, ok := _c.mutation.Unlisted(); !ok {
		v := profile.DefaultUnlisted
		_c.mutation.SetUnlisted(v)
	}
	if _, ok := _c.mutation.Cw(); !ok {
		v := profile.DefaultCw
		_c.mutation.SetCw(v)
	}
	if _, ok := _c.mutation.NoAutolink(); !ok {
		v := profile.DefaultNoAutolink
		_c.mutation.SetNoAutolink(v)
	}
	if _, ok := _c.mutation.IsPrivate(); !ok {
		v := profile.DefaultIsPrivate
		_c.mutation.SetIsPrivate(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := profile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := profile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsSuggestable(); !ok {
		v := profile.DefaultIsSuggestable
		_c.mutation.SetIsSuggestable(v)
	}
	if _, ok := _c.mutation.StatusCount(); !ok {
		v := profile.DefaultStatusCount
		_c.mutation.SetStatusCount(v)
	}
	if _, ok := _c.mutation.FollowersCount(); !ok {
		v := profile.DefaultFollowersCount
		_c.mutation.SetFollowersCount(v)
	}
	if _, ok := _c.mutation.FollowingCount(); !ok {
		v := profile.DefaultFollowingCount
		_c.mutation.SetFollowingCount(v)
	}
	if _, ok := _c.mutation.Indexable(); !ok {
		v := profile.DefaultIndexable
		_c.mutation.SetIndexable(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProfileCreate) check() error {
	if _, ok := _c.mutation.Unlisted(); !ok {
		return &ValidationError{Name: "unlisted", err: errors.New(`ent: missing required field "Profile.unlisted"`)}
	}
	if _, ok := _c.mutation.Cw(); !ok {
		return &ValidationError{Name: "cw", err: errors.New(`ent: missing required field "Profile.cw"`)}
	}
	if _, ok := _c.mutation.NoAutolink(); !ok {
		return &ValidationError{Name: "no_autolink", err: errors.New(`ent: missing required field "Profile.no_autolink"`)}
	}
	if _, ok := _c.mutation.IsPrivate(); !ok {
		return &ValidationError{Name: "is_private", err: errors.New(`ent: missing required field "Profile.is_private"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Profile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Profile.updated_at"`)}
	}
	if _, ok := _c.mutation.IsSuggestable(); !ok {
		return &ValidationError{Name: "is_suggestable", err: errors.New(`ent: missing required field "Profile.is_suggestable"`)}
	}
	if _, ok := _c.mutation.Indexable(); !ok {
		return &ValidationError{Name: "indexable", err: errors.New(`ent: missing required field "Profile.indexable"`)}
	}
	return nil
}

func (_c *ProfileCreate) sqlSave(ctx context.Context) (*Profile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProfileCreate) createSpec() (*Profile, *sqlgraph.CreateSpec) {
	var (
		_node = &Profile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(profile.Table, sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(profile.FieldUserID, field.TypeUint64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(profile.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(profile.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(profile.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(profile.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Bio(); ok {
		_spec.SetField(profile.FieldBio, field.TypeString, value)
		_node.Bio = value
	}
	if value, ok := _c.mutation.Unlisted(); ok {
		_spec.SetField(profile.FieldUnlisted, field.TypeBool, value)
		_node.Unlisted = value
	}
	if value, ok := _c.mutation.Cw(); ok {
		_spec.SetField(profile.FieldCw, field.TypeBool, value)
		_node.Cw = value
	}
	if value, ok := _c.mutation.NoAutolink(); ok {
		_spec.SetField(profile.FieldNoAutolink, field.TypeBool, value)
		_node.NoAutolink = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(profile.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.Website(); ok {
		_spec.SetField(profile.FieldWebsite, field.TypeString, value)
		_node.Website = value
	}
	if value, ok := _c.mutation.ProfileLayout(); ok {
		_spec.SetField(profile.FieldProfileLayout, field.TypeString, value)
		_node.ProfileLayout = value
	}
	if value, ok := _c.mutation.HeaderBg(); ok {
		_spec.SetField(profile.FieldHeaderBg, field.TypeString, value)
		_node.HeaderBg = value
	}
	if value, ok := _c.mutation.PostLayout(); ok {
		_spec.SetField(profile.FieldPostLayout, field.TypeString, value)
		_node.PostLayout = value
	}
	if value, ok := _c.mutation.IsPrivate(); ok {
		_spec.SetField(profile.FieldIsPrivate, field.TypeBool, value)
		_node.IsPrivate = value
	}
	if value, ok := _c.mutation.SharedInbox(); ok {
		_spec.SetField(profile.FieldSharedInbox, field.TypeString, value)
		_node.SharedInbox = value
	}
	if value, ok := _c.mutation.InboxURL(); ok {
		_spec.SetField(profile.FieldInboxURL, field.TypeString, value)
		_node.InboxURL = value
	}
	if value, ok := _c.mutation.OutboxURL(); ok {
		_spec.SetField(profile.FieldOutboxURL, field.TypeString, value)
		_node.OutboxURL = value
	}
	if value, ok := _c.mutation.KeyID(); ok {
		_spec.SetField(profile.FieldKeyID, field.TypeString, value)
		_node.KeyID = value
	}
	if value, ok := _c.mutation.FollowerURL(); ok {
		_spec.SetField(profile.FieldFollowerURL, field.TypeString, value)
		_node.FollowerURL = value
	}
	if value, ok := _c.mutation.FollowingURL(); ok {
		_spec.SetField(profile.FieldFollowingURL, field.TypeString, value)
		_node.FollowingURL = value
	}
	if value, ok := _c.mutation.PrivateKey(); ok {
		_spec.SetField(profile.FieldPrivateKey, field.TypeString, value)
		_node.PrivateKey = value
	}
	if value, ok := _c.mutation.PublicKey(); ok {
		_spec.SetField(profile.FieldPublicKey, field.TypeString, value)
		_node.PublicKey = value
	}
	if value, ok := _c.mutation.RemoteURL(); ok {
		_spec.SetField(profile.FieldRemoteURL, field.TypeString, value)
		_node.RemoteURL = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(profile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(profile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(profile.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.DeleteAfter(); ok {
		_spec.SetField(profile.FieldDeleteAfter, field.TypeTime, value)
		_node.DeleteAfter = value
	}
	if value, ok := _c.mutation.IsSuggestable(); ok {
		_spec.SetField(profile.FieldIsSuggestable, field.TypeBool, value)
		_node.IsSuggestable = value
	}
	if value, ok := _c.mutation.LastFetchedAt(); ok {
		_spec.SetField(profile.FieldLastFetchedAt, field.TypeTime, value)
		_node.LastFetchedAt = value
	}
	if value, ok := _c.mutation.StatusCount(); ok {
		_spec.SetField(profile.FieldStatusCount, field.TypeUint32, value)
		_node.StatusCount = value
	}
	if value, ok := _c.mutation.FollowersCount(); ok {
		_spec.SetField(profile.FieldFollowersCount, field.TypeUint32, value)
		_node.FollowersCount = value
	}
	if value, ok := _c.mutation.FollowingCount(); ok {
		_spec.SetField(profile.FieldFollowingCount, field.TypeUint32, value)
		_node.FollowingCount = value
	}
	if value, ok := _c.mutation.Webfinger(); ok {
		_spec.SetField(profile.FieldWebfinger, field.TypeString, value)
		_node.Webfinger = value
	}
	if value, ok := _c.mutation.AvatarURL(); ok {
		_spec.SetField(profile.FieldAvatarURL, field.TypeString, value)
		_node.AvatarURL = value
	}
	if value, ok := _c.mutation.LastStatusAt(); ok {
		_spec.SetField(profile.FieldLastStatusAt, field.TypeTime, value)
		_node.LastStatusAt = value
	}
	if value, ok := _c.mutation.MovedToProfileID(); ok {
		_spec.SetField(profile.FieldMovedToProfileID, field.TypeUint64, value)
		_node.MovedToProfileID = value
	}
	if value, ok := _c.mutation.Indexable(); ok {
		_spec.SetField(profile.FieldIndexable, field.TypeBool, value)
		_node.Indexable = value
	}
	if nodes := _c.mutation.StoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.StoriesTable,
			Columns: []string{profile.StoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(story.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProfileCreateBulk is the builder for creating many Profile entities in bulk.
type ProfileCreateBulk struct {
	config
	err      error
	builders []*ProfileCreate
}

// Save creates the Profile entities in the database.
func (_c *ProfileCreateBulk) Save(ctx context.Context) ([]*Profile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Profile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProfileCreateBulk) SaveX(ctx context.Context) []*Profile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
