// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/remoteauthinstance"
)

// RemoteAuthInstanceCreate is the builder for creating a RemoteAuthInstance entity.
type RemoteAuthInstanceCreate struct {
	config
	mutation *RemoteAuthInstanceMutation
	hooks    []Hook
}

// SetDomain sets the "domain" field.
func (_c *RemoteAuthInstanceCreate) SetDomain(v string) *RemoteAuthInstanceCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_c *RemoteAuthInstanceCreate) SetNillableDomain(v *string) *RemoteAuthInstanceCreate {
	if v != nil {
		_c.SetDomain(*v)
	}
	return _c
}

// SetInstanceID sets the "instance_id" field.
func (_c *RemoteAuthInstanceCreate) SetInstanceID(v uint32) *RemoteAuthInstanceCreate {
	_c.mutation.SetInstanceID(v)
	return _c
}

// SetNillableInstanceID sets the "instance_id" field if the given value is not nil.
func (_c *RemoteAuthInstanceCreate) SetNillableInstanceID(v *uint32) *RemoteAuthInstanceCreate {
	if v != nil {
		_c.SetInstanceID(*v)
	}
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *RemoteAuthInstanceCreate) SetClientID(v string) *RemoteAuthInstanceCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_c *RemoteAuthInstanceCreate) SetNillableClientID(v *string) *RemoteAuthInstanceCreate {
	if v != nil {
		_c.SetClientID(*v)
	}
	return _c
}

// SetClientSecret sets the "client_secret" field.
func (_c *RemoteAuthInstanceCreate) SetClientSecret(v string) *RemoteAuthInstanceCreate {
	_c.mutation.SetClientSecret(v)
	return _c
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (_c *RemoteAuthInstanceCreate) SetNillableClientSecret(v *string) *RemoteAuthInstanceCreate {
	if v != nil {
		_c.SetClientSecret(*v)
	}
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *RemoteAuthInstanceCreate) SetRedirectURI(v string) *RemoteAuthInstanceCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_c *RemoteAuthInstanceCreate) SetNillableRedirectURI(v *string) *RemoteAuthInstanceCreate {
	if v != nil {
		_c.SetRedirectURI(*v)
	}
	return _c
}

// SetRootDomain sets the "root_domain" field.
func (_c *RemoteAuthInstanceCreate) SetRootDomain(v string) *RemoteAuthInstanceCreate {
	_c.mutation.SetRootDomain(v)
	return _c
}

// SetNillableRootDomain sets the "root_domain" field if the given value is not nil.
func (_c *RemoteAuthInstanceCreate) SetNillableRootDomain(v *string) *RemoteAuthInstanceCreate {
	if v != nil {
		_c.SetRootDomain(*v)
	}
	return _c
}

// SetAllowed sets the "allowed" field.
func (_c *RemoteAuthInstanceCreate) SetAllowed(v bool) *RemoteAuthInstanceCreate {
	_c.mutation.SetAllowed(v)
	return _c
}

// SetNillableAllowed sets the "allowed" field if the given value is not nil.
func (_c *RemoteAuthInstanceCreate) SetNillableAllowed(v *bool) *RemoteAuthInstanceCreate {
	if v != nil {
		_c.SetAllowed(*v)
	}
	return _c
}

// SetBanned sets the "banned" field.
func (_c *RemoteAuthInstanceCreate) SetBanned(v bool) *RemoteAuthInstanceCreate {
	_c.mutation.SetBanned(v)
	return _c
}

// SetNillableBanned sets the "banned" field if the given value is not nil.
func (_c *RemoteAuthInstanceCreate) SetNillableBanned(v *bool) *RemoteAuthInstanceCreate {
	if v != nil {
		_c.SetBanned(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *RemoteAuthInstanceCreate) SetActive(v bool) *RemoteAuthInstanceCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *RemoteAuthInstanceCreate) SetNillableActive(v *bool) *RemoteAuthInstanceCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetLastRefreshedAt sets the "last_refreshed_at" field.
func (_c *RemoteAuthInstanceCreate) SetLastRefreshedAt(v time.Time) *RemoteAuthInstanceCreate {
	_c.mutation.SetLastRefreshedAt(v)
	return _c
}

// SetNillableLastRefreshedAt sets the "last_refreshed_at" field if the given value is not nil.
func (_c *RemoteAuthInstanceCreate) SetNillableLastRefreshedAt(v *time.Time) *RemoteAuthInstanceCreate {
	if v != nil {
		_c.SetLastRefreshedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RemoteAuthInstanceCreate) SetCreatedAt(v time.Time) *RemoteAuthInstanceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RemoteAuthInstanceCreate) SetNillableCreatedAt(v *time.Time) *RemoteAuthInstanceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RemoteAuthInstanceCreate) SetUpdatedAt(v time.Time) *RemoteAuthInstanceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RemoteAuthInstanceCreate) SetNillableUpdatedAt(v *time.Time) *RemoteAuthInstanceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RemoteAuthInstanceCreate) SetID(v uint64) *RemoteAuthInstanceCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RemoteAuthInstanceMutation object of the builder.
func (_c *RemoteAuthInstanceCreate) Mutation() *RemoteAuthInstanceMutation {
	return _c.mutation
}

// Save creates the RemoteAuthInstance in the database.
func (_c *RemoteAuthInstanceCreate) Save(ctx context.Context) (*RemoteAuthInstance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RemoteAuthInstanceCreate) SaveX(ctx context.Context) *RemoteAuthInstance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RemoteAuthInstanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RemoteAuthInstanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RemoteAuthInstanceCreate) defaults() {
	if _, ok := _c.mutation.Banned(); !ok {
		v := remoteauthinstance.DefaultBanned
		_c.mutation.SetBanned(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := remoteauthinstance.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := remoteauthinstance.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := remoteauthinstance.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RemoteAuthInstanceCreate) check() error {
	if _, ok := _c.mutation.Banned(); !ok {
		return &ValidationError{Name: "banned", err: errors.New(`ent: missing required field "RemoteAuthInstance.banned"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "RemoteAuthInstance.active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RemoteAuthInstance.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RemoteAuthInstance.updated_at"`)}
	}
	return nil
}

func (_c *RemoteAuthInstanceCreate) sqlSave(ctx context.Context) (*RemoteAuthInstance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RemoteAuthInstanceCreate) createSpec() (*RemoteAuthInstance, *sqlgraph.CreateSpec) {
	var (
		_node = &RemoteAuthInstance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(remoteauthinstance.Table, sqlgraph.NewFieldSpec(remoteauthinstance.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(remoteauthinstance.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.InstanceID(); ok {
		_spec.SetField(remoteauthinstance.FieldInstanceID, field.TypeUint32, value)
		_node.InstanceID = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(remoteauthinstance.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientSecret(); ok {
		_spec.SetField(remoteauthinstance.FieldClientSecret, field.TypeString, value)
		_node.ClientSecret = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(remoteauthinstance.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.RootDomain(); ok {
		_spec.SetField(remoteauthinstance.FieldRootDomain, field.TypeString, value)
		_node.RootDomain = value
	}
	if value, ok := _c.mutation.Allowed(); ok {
		_spec.SetField(remoteauthinstance.FieldAllowed, field.TypeBool, value)
		_node.Allowed = value
	}
	if value, ok := _c.mutation.Banned(); ok {
		_spec.SetField(remoteauthinstance.FieldBanned, field.TypeBool, value)
		_node.Banned = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(remoteauthinstance.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.LastRefreshedAt(); ok {
		_spec.SetField(remoteauthinstance.FieldLastRefreshedAt, field.TypeTime, value)
		_node.LastRefreshedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(remoteauthinstance.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(remoteauthinstance.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// RemoteAuthInstanceCreateBulk is the builder for creating many RemoteAuthInstance entities in bulk.
type RemoteAuthInstanceCreateBulk struct {
	config
	err      error
	builders []*RemoteAuthInstanceCreate
}

// Save creates the RemoteAuthInstance entities in the database.
func (_c *RemoteAuthInstanceCreateBulk) Save(ctx context.Context) ([]*RemoteAuthInstance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RemoteAuthInstance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RemoteAuthInstanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RemoteAuthInstanceCreateBulk) SaveX(ctx context.Context) []*RemoteAuthInstance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RemoteAuthInstanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RemoteAuthInstanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
