// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/predicate"
	"glintfed.org/ent/remoteauth"
)

// RemoteAuthUpdate is the builder for updating RemoteAuth entities.
type RemoteAuthUpdate struct {
	config
	hooks    []Hook
	mutation *RemoteAuthMutation
}

// Where appends a list predicates to the RemoteAuthUpdate builder.
func (_u *RemoteAuthUpdate) Where(ps ...predicate.RemoteAuth) *RemoteAuthUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSoftware sets the "software" field.
func (_u *RemoteAuthUpdate) SetSoftware(v string) *RemoteAuthUpdate {
	_u.mutation.SetSoftware(v)
	return _u
}

// SetNillableSoftware sets the "software" field if the given value is not nil.
func (_u *RemoteAuthUpdate) SetNillableSoftware(v *string) *RemoteAuthUpdate {
	if v != nil {
		_u.SetSoftware(*v)
	}
	return _u
}

// ClearSoftware clears the value of the "software" field.
func (_u *RemoteAuthUpdate) ClearSoftware() *RemoteAuthUpdate {
	_u.mutation.ClearSoftware()
	return _u
}

// SetDomain sets the "domain" field.
func (_u *RemoteAuthUpdate) SetDomain(v string) *RemoteAuthUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *RemoteAuthUpdate) SetNillableDomain(v *string) *RemoteAuthUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *RemoteAuthUpdate) ClearDomain() *RemoteAuthUpdate {
	_u.mutation.ClearDomain()
	return _u
}

// SetWebfinger sets the "webfinger" field.
func (_u *RemoteAuthUpdate) SetWebfinger(v string) *RemoteAuthUpdate {
	_u.mutation.SetWebfinger(v)
	return _u
}

// SetNillableWebfinger sets the "webfinger" field if the given value is not nil.
func (_u *RemoteAuthUpdate) SetNillableWebfinger(v *string) *RemoteAuthUpdate {
	if v != nil {
		_u.SetWebfinger(*v)
	}
	return _u
}

// ClearWebfinger clears the value of the "webfinger" field.
func (_u *RemoteAuthUpdate) ClearWebfinger() *RemoteAuthUpdate {
	_u.mutation.ClearWebfinger()
	return _u
}

// SetInstanceID sets the "instance_id" field.
func (_u *RemoteAuthUpdate) SetInstanceID(v uint32) *RemoteAuthUpdate {
	_u.mutation.ResetInstanceID()
	_u.mutation.SetInstanceID(v)
	return _u
}

// SetNillableInstanceID sets the "instance_id" field if the given value is not nil.
func (_u *RemoteAuthUpdate) SetNillableInstanceID(v *uint32) *RemoteAuthUpdate {
	if v != nil {
		_u.SetInstanceID(*v)
	}
	return _u
}

// AddInstanceID adds value to the "instance_id" field.
func (_u *RemoteAuthUpdate) AddInstanceID(v int32) *RemoteAuthUpdate {
	_u.mutation.AddInstanceID(v)
	return _u
}

// ClearInstanceID clears the value of the "instance_id" field.
func (_u *RemoteAuthUpdate) ClearInstanceID() *RemoteAuthUpdate {
	_u.mutation.ClearInstanceID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RemoteAuthUpdate) SetUserID(v uint64) *RemoteAuthUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RemoteAuthUpdate) SetNillableUserID(v *uint64) *RemoteAuthUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RemoteAuthUpdate) AddUserID(v int64) *RemoteAuthUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *RemoteAuthUpdate) ClearUserID() *RemoteAuthUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *RemoteAuthUpdate) SetClientID(v uint32) *RemoteAuthUpdate {
	_u.mutation.ResetClientID()
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *RemoteAuthUpdate) SetNillableClientID(v *uint32) *RemoteAuthUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// AddClientID adds value to the "client_id" field.
func (_u *RemoteAuthUpdate) AddClientID(v int32) *RemoteAuthUpdate {
	_u.mutation.AddClientID(v)
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *RemoteAuthUpdate) ClearClientID() *RemoteAuthUpdate {
	_u.mutation.ClearClientID()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *RemoteAuthUpdate) SetIPAddress(v string) *RemoteAuthUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *RemoteAuthUpdate) SetNillableIPAddress(v *string) *RemoteAuthUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *RemoteAuthUpdate) ClearIPAddress() *RemoteAuthUpdate {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetBearerToken sets the "bearer_token" field.
func (_u *RemoteAuthUpdate) SetBearerToken(v string) *RemoteAuthUpdate {
	_u.mutation.SetBearerToken(v)
	return _u
}

// SetNillableBearerToken sets the "bearer_token" field if the given value is not nil.
func (_u *RemoteAuthUpdate) SetNillableBearerToken(v *string) *RemoteAuthUpdate {
	if v != nil {
		_u.SetBearerToken(*v)
	}
	return _u
}

// ClearBearerToken clears the value of the "bearer_token" field.
func (_u *RemoteAuthUpdate) ClearBearerToken() *RemoteAuthUpdate {
	_u.mutation.ClearBearerToken()
	return _u
}

// SetVerifyCredentials sets the "verify_credentials" field.
func (_u *RemoteAuthUpdate) SetVerifyCredentials(v map[string]interface{}) *RemoteAuthUpdate {
	_u.mutation.SetVerifyCredentials(v)
	return _u
}

// ClearVerifyCredentials clears the value of the "verify_credentials" field.
func (_u *RemoteAuthUpdate) ClearVerifyCredentials() *RemoteAuthUpdate {
	_u.mutation.ClearVerifyCredentials()
	return _u
}

// SetLastSuccessfulLoginAt sets the "last_successful_login_at" field.
func (_u *RemoteAuthUpdate) SetLastSuccessfulLoginAt(v time.Time) *RemoteAuthUpdate {
	_u.mutation.SetLastSuccessfulLoginAt(v)
	return _u
}

// SetNillableLastSuccessfulLoginAt sets the "last_successful_login_at" field if the given value is not nil.
func (_u *RemoteAuthUpdate) SetNillableLastSuccessfulLoginAt(v *time.Time) *RemoteAuthUpdate {
	if v != nil {
		_u.SetLastSuccessfulLoginAt(*v)
	}
	return _u
}

// ClearLastSuccessfulLoginAt clears the value of the "last_successful_login_at" field.
func (_u *RemoteAuthUpdate) ClearLastSuccessfulLoginAt() *RemoteAuthUpdate {
	_u.mutation.ClearLastSuccessfulLoginAt()
	return _u
}

// SetLastVerifyCredentialsAt sets the "last_verify_credentials_at" field.
func (_u *RemoteAuthUpdate) SetLastVerifyCredentialsAt(v time.Time) *RemoteAuthUpdate {
	_u.mutation.SetLastVerifyCredentialsAt(v)
	return _u
}

// SetNillableLastVerifyCredentialsAt sets the "last_verify_credentials_at" field if the given value is not nil.
func (_u *RemoteAuthUpdate) SetNillableLastVerifyCredentialsAt(v *time.Time) *RemoteAuthUpdate {
	if v != nil {
		_u.SetLastVerifyCredentialsAt(*v)
	}
	return _u
}

// ClearLastVerifyCredentialsAt clears the value of the "last_verify_credentials_at" field.
func (_u *RemoteAuthUpdate) ClearLastVerifyCredentialsAt() *RemoteAuthUpdate {
	_u.mutation.ClearLastVerifyCredentialsAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RemoteAuthUpdate) SetUpdatedAt(v time.Time) *RemoteAuthUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RemoteAuthMutation object of the builder.
func (_u *RemoteAuthUpdate) Mutation() *RemoteAuthMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RemoteAuthUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RemoteAuthUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RemoteAuthUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RemoteAuthUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RemoteAuthUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := remoteauth.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *RemoteAuthUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(remoteauth.Table, remoteauth.Columns, sqlgraph.NewFieldSpec(remoteauth.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Software(); ok {
		_spec.SetField(remoteauth.FieldSoftware, field.TypeString, value)
	}
	if _u.mutation.SoftwareCleared() {
		_spec.ClearField(remoteauth.FieldSoftware, field.TypeString)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(remoteauth.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(remoteauth.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.Webfinger(); ok {
		_spec.SetField(remoteauth.FieldWebfinger, field.TypeString, value)
	}
	if _u.mutation.WebfingerCleared() {
		_spec.ClearField(remoteauth.FieldWebfinger, field.TypeString)
	}
	if value, ok := _u.mutation.InstanceID(); ok {
		_spec.SetField(remoteauth.FieldInstanceID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedInstanceID(); ok {
		_spec.AddField(remoteauth.FieldInstanceID, field.TypeUint32, value)
	}
	if _u.mutation.InstanceIDCleared() {
		_spec.ClearField(remoteauth.FieldInstanceID, field.TypeUint32)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(remoteauth.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(remoteauth.FieldUserID, field.TypeUint64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(remoteauth.FieldUserID, field.TypeUint64)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(remoteauth.FieldClientID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedClientID(); ok {
		_spec.AddField(remoteauth.FieldClientID, field.TypeUint32, value)
	}
	if _u.mutation.ClientIDCleared() {
		_spec.ClearField(remoteauth.FieldClientID, field.TypeUint32)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(remoteauth.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(remoteauth.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.BearerToken(); ok {
		_spec.SetField(remoteauth.FieldBearerToken, field.TypeString, value)
	}
	if _u.mutation.BearerTokenCleared() {
		_spec.ClearField(remoteauth.FieldBearerToken, field.TypeString)
	}
	if value, ok := _u.mutation.VerifyCredentials(); ok {
		_spec.SetField(remoteauth.FieldVerifyCredentials, field.TypeJSON, value)
	}
	if _u.mutation.VerifyCredentialsCleared() {
		_spec.ClearField(remoteauth.FieldVerifyCredentials, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastSuccessfulLoginAt(); ok {
		_spec.SetField(remoteauth.FieldLastSuccessfulLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastSuccessfulLoginAtCleared() {
		_spec.ClearField(remoteauth.FieldLastSuccessfulLoginAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastVerifyCredentialsAt(); ok {
		_spec.SetField(remoteauth.FieldLastVerifyCredentialsAt, field.TypeTime, value)
	}
	if _u.mutation.LastVerifyCredentialsAtCleared() {
		_spec.ClearField(remoteauth.FieldLastVerifyCredentialsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(remoteauth.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{remoteauth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RemoteAuthUpdateOne is the builder for updating a single RemoteAuth entity.
type RemoteAuthUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RemoteAuthMutation
}

// SetSoftware sets the "software" field.
func (_u *RemoteAuthUpdateOne) SetSoftware(v string) *RemoteAuthUpdateOne {
	_u.mutation.SetSoftware(v)
	return _u
}

// SetNillableSoftware sets the "software" field if the given value is not nil.
func (_u *RemoteAuthUpdateOne) SetNillableSoftware(v *string) *RemoteAuthUpdateOne {
	if v != nil {
		_u.SetSoftware(*v)
	}
	return _u
}

// ClearSoftware clears the value of the "software" field.
func (_u *RemoteAuthUpdateOne) ClearSoftware() *RemoteAuthUpdateOne {
	_u.mutation.ClearSoftware()
	return _u
}

// SetDomain sets the "domain" field.
func (_u *RemoteAuthUpdateOne) SetDomain(v string) *RemoteAuthUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *RemoteAuthUpdateOne) SetNillableDomain(v *string) *RemoteAuthUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *RemoteAuthUpdateOne) ClearDomain() *RemoteAuthUpdateOne {
	_u.mutation.ClearDomain()
	return _u
}

// SetWebfinger sets the "webfinger" field.
func (_u *RemoteAuthUpdateOne) SetWebfinger(v string) *RemoteAuthUpdateOne {
	_u.mutation.SetWebfinger(v)
	return _u
}

// SetNillableWebfinger sets the "webfinger" field if the given value is not nil.
func (_u *RemoteAuthUpdateOne) SetNillableWebfinger(v *string) *RemoteAuthUpdateOne {
	if v != nil {
		_u.SetWebfinger(*v)
	}
	return _u
}

// ClearWebfinger clears the value of the "webfinger" field.
func (_u *RemoteAuthUpdateOne) ClearWebfinger() *RemoteAuthUpdateOne {
	_u.mutation.ClearWebfinger()
	return _u
}

// SetInstanceID sets the "instance_id" field.
func (_u *RemoteAuthUpdateOne) SetInstanceID(v uint32) *RemoteAuthUpdateOne {
	_u.mutation.ResetInstanceID()
	_u.mutation.SetInstanceID(v)
	return _u
}

// SetNillableInstanceID sets the "instance_id" field if the given value is not nil.
func (_u *RemoteAuthUpdateOne) SetNillableInstanceID(v *uint32) *RemoteAuthUpdateOne {
	if v != nil {
		_u.SetInstanceID(*v)
	}
	return _u
}

// AddInstanceID adds value to the "instance_id" field.
func (_u *RemoteAuthUpdateOne) AddInstanceID(v int32) *RemoteAuthUpdateOne {
	_u.mutation.AddInstanceID(v)
	return _u
}

// ClearInstanceID clears the value of the "instance_id" field.
func (_u *RemoteAuthUpdateOne) ClearInstanceID() *RemoteAuthUpdateOne {
	_u.mutation.ClearInstanceID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RemoteAuthUpdateOne) SetUserID(v uint64) *RemoteAuthUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RemoteAuthUpdateOne) SetNillableUserID(v *uint64) *RemoteAuthUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RemoteAuthUpdateOne) AddUserID(v int64) *RemoteAuthUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *RemoteAuthUpdateOne) ClearUserID() *RemoteAuthUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *RemoteAuthUpdateOne) SetClientID(v uint32) *RemoteAuthUpdateOne {
	_u.mutation.ResetClientID()
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *RemoteAuthUpdateOne) SetNillableClientID(v *uint32) *RemoteAuthUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// AddClientID adds value to the "client_id" field.
func (_u *RemoteAuthUpdateOne) AddClientID(v int32) *RemoteAuthUpdateOne {
	_u.mutation.AddClientID(v)
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *RemoteAuthUpdateOne) ClearClientID() *RemoteAuthUpdateOne {
	_u.mutation.ClearClientID()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *RemoteAuthUpdateOne) SetIPAddress(v string) *RemoteAuthUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *RemoteAuthUpdateOne) SetNillableIPAddress(v *string) *RemoteAuthUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *RemoteAuthUpdateOne) ClearIPAddress() *RemoteAuthUpdateOne {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetBearerToken sets the "bearer_token" field.
func (_u *RemoteAuthUpdateOne) SetBearerToken(v string) *RemoteAuthUpdateOne {
	_u.mutation.SetBearerToken(v)
	return _u
}

// SetNillableBearerToken sets the "bearer_token" field if the given value is not nil.
func (_u *RemoteAuthUpdateOne) SetNillableBearerToken(v *string) *RemoteAuthUpdateOne {
	if v != nil {
		_u.SetBearerToken(*v)
	}
	return _u
}

// ClearBearerToken clears the value of the "bearer_token" field.
func (_u *RemoteAuthUpdateOne) ClearBearerToken() *RemoteAuthUpdateOne {
	_u.mutation.ClearBearerToken()
	return _u
}

// SetVerifyCredentials sets the "verify_credentials" field.
func (_u *RemoteAuthUpdateOne) SetVerifyCredentials(v map[string]interface{}) *RemoteAuthUpdateOne {
	_u.mutation.SetVerifyCredentials(v)
	return _u
}

// ClearVerifyCredentials clears the value of the "verify_credentials" field.
func (_u *RemoteAuthUpdateOne) ClearVerifyCredentials() *RemoteAuthUpdateOne {
	_u.mutation.ClearVerifyCredentials()
	return _u
}

// SetLastSuccessfulLoginAt sets the "last_successful_login_at" field.
func (_u *RemoteAuthUpdateOne) SetLastSuccessfulLoginAt(v time.Time) *RemoteAuthUpdateOne {
	_u.mutation.SetLastSuccessfulLoginAt(v)
	return _u
}

// SetNillableLastSuccessfulLoginAt sets the "last_successful_login_at" field if the given value is not nil.
func (_u *RemoteAuthUpdateOne) SetNillableLastSuccessfulLoginAt(v *time.Time) *RemoteAuthUpdateOne {
	if v != nil {
		_u.SetLastSuccessfulLoginAt(*v)
	}
	return _u
}

// ClearLastSuccessfulLoginAt clears the value of the "last_successful_login_at" field.
func (_u *RemoteAuthUpdateOne) ClearLastSuccessfulLoginAt() *RemoteAuthUpdateOne {
	_u.mutation.ClearLastSuccessfulLoginAt()
	return _u
}

// SetLastVerifyCredentialsAt sets the "last_verify_credentials_at" field.
func (_u *RemoteAuthUpdateOne) SetLastVerifyCredentialsAt(v time.Time) *RemoteAuthUpdateOne {
	_u.mutation.SetLastVerifyCredentialsAt(v)
	return _u
}

// SetNillableLastVerifyCredentialsAt sets the "last_verify_credentials_at" field if the given value is not nil.
func (_u *RemoteAuthUpdateOne) SetNillableLastVerifyCredentialsAt(v *time.Time) *RemoteAuthUpdateOne {
	if v != nil {
		_u.SetLastVerifyCredentialsAt(*v)
	}
	return _u
}

// ClearLastVerifyCredentialsAt clears the value of the "last_verify_credentials_at" field.
func (_u *RemoteAuthUpdateOne) ClearLastVerifyCredentialsAt() *RemoteAuthUpdateOne {
	_u.mutation.ClearLastVerifyCredentialsAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RemoteAuthUpdateOne) SetUpdatedAt(v time.Time) *RemoteAuthUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RemoteAuthMutation object of the builder.
func (_u *RemoteAuthUpdateOne) Mutation() *RemoteAuthMutation {
	return _u.mutation
}

// Where appends a list predicates to the RemoteAuthUpdate builder.
func (_u *RemoteAuthUpdateOne) Where(ps ...predicate.RemoteAuth) *RemoteAuthUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RemoteAuthUpdateOne) Select(field string, fields ...string) *RemoteAuthUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RemoteAuth entity.
func (_u *RemoteAuthUpdateOne) Save(ctx context.Context) (*RemoteAuth, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RemoteAuthUpdateOne) SaveX(ctx context.Context) *RemoteAuth {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RemoteAuthUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RemoteAuthUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RemoteAuthUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := remoteauth.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *RemoteAuthUpdateOne) sqlSave(ctx context.Context) (_node *RemoteAuth, err error) {
	_spec := sqlgraph.NewUpdateSpec(remoteauth.Table, remoteauth.Columns, sqlgraph.NewFieldSpec(remoteauth.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RemoteAuth.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, remoteauth.FieldID)
		for _, f := range fields {
			if !remoteauth.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != remoteauth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Software(); ok {
		_spec.SetField(remoteauth.FieldSoftware, field.TypeString, value)
	}
	if _u.mutation.SoftwareCleared() {
		_spec.ClearField(remoteauth.FieldSoftware, field.TypeString)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(remoteauth.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(remoteauth.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.Webfinger(); ok {
		_spec.SetField(remoteauth.FieldWebfinger, field.TypeString, value)
	}
	if _u.mutation.WebfingerCleared() {
		_spec.ClearField(remoteauth.FieldWebfinger, field.TypeString)
	}
	if value, ok := _u.mutation.InstanceID(); ok {
		_spec.SetField(remoteauth.FieldInstanceID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedInstanceID(); ok {
		_spec.AddField(remoteauth.FieldInstanceID, field.TypeUint32, value)
	}
	if _u.mutation.InstanceIDCleared() {
		_spec.ClearField(remoteauth.FieldInstanceID, field.TypeUint32)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(remoteauth.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(remoteauth.FieldUserID, field.TypeUint64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(remoteauth.FieldUserID, field.TypeUint64)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(remoteauth.FieldClientID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedClientID(); ok {
		_spec.AddField(remoteauth.FieldClientID, field.TypeUint32, value)
	}
	if _u.mutation.ClientIDCleared() {
		_spec.ClearField(remoteauth.FieldClientID, field.TypeUint32)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(remoteauth.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(remoteauth.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.BearerToken(); ok {
		_spec.SetField(remoteauth.FieldBearerToken, field.TypeString, value)
	}
	if _u.mutation.BearerTokenCleared() {
		_spec.ClearField(remoteauth.FieldBearerToken, field.TypeString)
	}
	if value, ok := _u.mutation.VerifyCredentials(); ok {
		_spec.SetField(remoteauth.FieldVerifyCredentials, field.TypeJSON, value)
	}
	if _u.mutation.VerifyCredentialsCleared() {
		_spec.ClearField(remoteauth.FieldVerifyCredentials, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastSuccessfulLoginAt(); ok {
		_spec.SetField(remoteauth.FieldLastSuccessfulLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastSuccessfulLoginAtCleared() {
		_spec.ClearField(remoteauth.FieldLastSuccessfulLoginAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastVerifyCredentialsAt(); ok {
		_spec.SetField(remoteauth.FieldLastVerifyCredentialsAt, field.TypeTime, value)
	}
	if _u.mutation.LastVerifyCredentialsAtCleared() {
		_spec.ClearField(remoteauth.FieldLastVerifyCredentialsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(remoteauth.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &RemoteAuth{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{remoteauth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
