// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"glintfed.org/ent/remoteauth"
)

// RemoteAuth is the model entity for the RemoteAuth schema.
type RemoteAuth struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Software holds the value of the "software" field.
	Software string `json:"software,omitempty"`
	// Domain holds the value of the "domain" field.
	Domain string `json:"domain,omitempty"`
	// Webfinger holds the value of the "webfinger" field.
	Webfinger string `json:"webfinger,omitempty"`
	// InstanceID holds the value of the "instance_id" field.
	InstanceID uint32 `json:"instance_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uint64 `json:"user_id,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID uint32 `json:"client_id,omitempty"`
	// IPAddress holds the value of the "ip_address" field.
	IPAddress string `json:"ip_address,omitempty"`
	// BearerToken holds the value of the "bearer_token" field.
	BearerToken string `json:"bearer_token,omitempty"`
	// VerifyCredentials holds the value of the "verify_credentials" field.
	VerifyCredentials map[string]interface{} `json:"verify_credentials,omitempty"`
	// LastSuccessfulLoginAt holds the value of the "last_successful_login_at" field.
	LastSuccessfulLoginAt time.Time `json:"last_successful_login_at,omitempty"`
	// LastVerifyCredentialsAt holds the value of the "last_verify_credentials_at" field.
	LastVerifyCredentialsAt time.Time `json:"last_verify_credentials_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RemoteAuth) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case remoteauth.FieldVerifyCredentials:
			values[i] = new([]byte)
		case remoteauth.FieldID, remoteauth.FieldInstanceID, remoteauth.FieldUserID, remoteauth.FieldClientID:
			values[i] = new(sql.NullInt64)
		case remoteauth.FieldSoftware, remoteauth.FieldDomain, remoteauth.FieldWebfinger, remoteauth.FieldIPAddress, remoteauth.FieldBearerToken:
			values[i] = new(sql.NullString)
		case remoteauth.FieldLastSuccessfulLoginAt, remoteauth.FieldLastVerifyCredentialsAt, remoteauth.FieldCreatedAt, remoteauth.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RemoteAuth fields.
func (_m *RemoteAuth) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case remoteauth.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case remoteauth.FieldSoftware:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field software", values[i])
			} else if value.Valid {
				_m.Software = value.String
			}
		case remoteauth.FieldDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain", values[i])
			} else if value.Valid {
				_m.Domain = value.String
			}
		case remoteauth.FieldWebfinger:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field webfinger", values[i])
			} else if value.Valid {
				_m.Webfinger = value.String
			}
		case remoteauth.FieldInstanceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field instance_id", values[i])
			} else if value.Valid {
				_m.InstanceID = uint32(value.Int64)
			}
		case remoteauth.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = uint64(value.Int64)
			}
		case remoteauth.FieldClientID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = uint32(value.Int64)
			}
		case remoteauth.FieldIPAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_address", values[i])
			} else if value.Valid {
				_m.IPAddress = value.String
			}
		case remoteauth.FieldBearerToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bearer_token", values[i])
			} else if value.Valid {
				_m.BearerToken = value.String
			}
		case remoteauth.FieldVerifyCredentials:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field verify_credentials", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.VerifyCredentials); err != nil {
					return fmt.Errorf("unmarshal field verify_credentials: %w", err)
				}
			}
		case remoteauth.FieldLastSuccessfulLoginAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_successful_login_at", values[i])
			} else if value.Valid {
				_m.LastSuccessfulLoginAt = value.Time
			}
		case remoteauth.FieldLastVerifyCredentialsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_verify_credentials_at", values[i])
			} else if value.Valid {
				_m.LastVerifyCredentialsAt = value.Time
			}
		case remoteauth.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case remoteauth.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RemoteAuth.
// This includes values selected through modifiers, order, etc.
func (_m *RemoteAuth) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RemoteAuth.
// Note that you need to call RemoteAuth.Unwrap() before calling this method if this RemoteAuth
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RemoteAuth) Update() *RemoteAuthUpdateOne {
	return NewRemoteAuthClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RemoteAuth entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RemoteAuth) Unwrap() *RemoteAuth {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RemoteAuth is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RemoteAuth) String() string {
	var builder strings.Builder
	builder.WriteString("RemoteAuth(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("software=")
	builder.WriteString(_m.Software)
	builder.WriteString(", ")
	builder.WriteString("domain=")
	builder.WriteString(_m.Domain)
	builder.WriteString(", ")
	builder.WriteString("webfinger=")
	builder.WriteString(_m.Webfinger)
	builder.WriteString(", ")
	builder.WriteString("instance_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InstanceID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientID))
	builder.WriteString(", ")
	builder.WriteString("ip_address=")
	builder.WriteString(_m.IPAddress)
	builder.WriteString(", ")
	builder.WriteString("bearer_token=")
	builder.WriteString(_m.BearerToken)
	builder.WriteString(", ")
	builder.WriteString("verify_credentials=")
	builder.WriteString(fmt.Sprintf("%v", _m.VerifyCredentials))
	builder.WriteString(", ")
	builder.WriteString("last_successful_login_at=")
	builder.WriteString(_m.LastSuccessfulLoginAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_verify_credentials_at=")
	builder.WriteString(_m.LastVerifyCredentialsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RemoteAuths is a parsable slice of RemoteAuth.
type RemoteAuths []*RemoteAuth
