// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/predicate"
	"glintfed.org/ent/statusview"
)

// StatusViewUpdate is the builder for updating StatusView entities.
type StatusViewUpdate struct {
	config
	hooks    []Hook
	mutation *StatusViewMutation
}

// Where appends a list predicates to the StatusViewUpdate builder.
func (_u *StatusViewUpdate) Where(ps ...predicate.StatusView) *StatusViewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatusID sets the "status_id" field.
func (_u *StatusViewUpdate) SetStatusID(v uint64) *StatusViewUpdate {
	_u.mutation.ResetStatusID()
	_u.mutation.SetStatusID(v)
	return _u
}

// SetNillableStatusID sets the "status_id" field if the given value is not nil.
func (_u *StatusViewUpdate) SetNillableStatusID(v *uint64) *StatusViewUpdate {
	if v != nil {
		_u.SetStatusID(*v)
	}
	return _u
}

// AddStatusID adds value to the "status_id" field.
func (_u *StatusViewUpdate) AddStatusID(v int64) *StatusViewUpdate {
	_u.mutation.AddStatusID(v)
	return _u
}

// ClearStatusID clears the value of the "status_id" field.
func (_u *StatusViewUpdate) ClearStatusID() *StatusViewUpdate {
	_u.mutation.ClearStatusID()
	return _u
}

// SetStatusProfileID sets the "status_profile_id" field.
func (_u *StatusViewUpdate) SetStatusProfileID(v uint64) *StatusViewUpdate {
	_u.mutation.ResetStatusProfileID()
	_u.mutation.SetStatusProfileID(v)
	return _u
}

// SetNillableStatusProfileID sets the "status_profile_id" field if the given value is not nil.
func (_u *StatusViewUpdate) SetNillableStatusProfileID(v *uint64) *StatusViewUpdate {
	if v != nil {
		_u.SetStatusProfileID(*v)
	}
	return _u
}

// AddStatusProfileID adds value to the "status_profile_id" field.
func (_u *StatusViewUpdate) AddStatusProfileID(v int64) *StatusViewUpdate {
	_u.mutation.AddStatusProfileID(v)
	return _u
}

// ClearStatusProfileID clears the value of the "status_profile_id" field.
func (_u *StatusViewUpdate) ClearStatusProfileID() *StatusViewUpdate {
	_u.mutation.ClearStatusProfileID()
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *StatusViewUpdate) SetProfileID(v uint64) *StatusViewUpdate {
	_u.mutation.ResetProfileID()
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *StatusViewUpdate) SetNillableProfileID(v *uint64) *StatusViewUpdate {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// AddProfileID adds value to the "profile_id" field.
func (_u *StatusViewUpdate) AddProfileID(v int64) *StatusViewUpdate {
	_u.mutation.AddProfileID(v)
	return _u
}

// ClearProfileID clears the value of the "profile_id" field.
func (_u *StatusViewUpdate) ClearProfileID() *StatusViewUpdate {
	_u.mutation.ClearProfileID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StatusViewUpdate) SetUpdatedAt(v time.Time) *StatusViewUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the StatusViewMutation object of the builder.
func (_u *StatusViewUpdate) Mutation() *StatusViewMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StatusViewUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StatusViewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StatusViewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StatusViewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StatusViewUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := statusview.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *StatusViewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(statusview.Table, statusview.Columns, sqlgraph.NewFieldSpec(statusview.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StatusID(); ok {
		_spec.SetField(statusview.FieldStatusID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedStatusID(); ok {
		_spec.AddField(statusview.FieldStatusID, field.TypeUint64, value)
	}
	if _u.mutation.StatusIDCleared() {
		_spec.ClearField(statusview.FieldStatusID, field.TypeUint64)
	}
	if value, ok := _u.mutation.StatusProfileID(); ok {
		_spec.SetField(statusview.FieldStatusProfileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedStatusProfileID(); ok {
		_spec.AddField(statusview.FieldStatusProfileID, field.TypeUint64, value)
	}
	if _u.mutation.StatusProfileIDCleared() {
		_spec.ClearField(statusview.FieldStatusProfileID, field.TypeUint64)
	}
	if value, ok := _u.mutation.ProfileID(); ok {
		_spec.SetField(statusview.FieldProfileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedProfileID(); ok {
		_spec.AddField(statusview.FieldProfileID, field.TypeUint64, value)
	}
	if _u.mutation.ProfileIDCleared() {
		_spec.ClearField(statusview.FieldProfileID, field.TypeUint64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(statusview.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statusview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StatusViewUpdateOne is the builder for updating a single StatusView entity.
type StatusViewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StatusViewMutation
}

// SetStatusID sets the "status_id" field.
func (_u *StatusViewUpdateOne) SetStatusID(v uint64) *StatusViewUpdateOne {
	_u.mutation.ResetStatusID()
	_u.mutation.SetStatusID(v)
	return _u
}

// SetNillableStatusID sets the "status_id" field if the given value is not nil.
func (_u *StatusViewUpdateOne) SetNillableStatusID(v *uint64) *StatusViewUpdateOne {
	if v != nil {
		_u.SetStatusID(*v)
	}
	return _u
}

// AddStatusID adds value to the "status_id" field.
func (_u *StatusViewUpdateOne) AddStatusID(v int64) *StatusViewUpdateOne {
	_u.mutation.AddStatusID(v)
	return _u
}

// ClearStatusID clears the value of the "status_id" field.
func (_u *StatusViewUpdateOne) ClearStatusID() *StatusViewUpdateOne {
	_u.mutation.ClearStatusID()
	return _u
}

// SetStatusProfileID sets the "status_profile_id" field.
func (_u *StatusViewUpdateOne) SetStatusProfileID(v uint64) *StatusViewUpdateOne {
	_u.mutation.ResetStatusProfileID()
	_u.mutation.SetStatusProfileID(v)
	return _u
}

// SetNillableStatusProfileID sets the "status_profile_id" field if the given value is not nil.
func (_u *StatusViewUpdateOne) SetNillableStatusProfileID(v *uint64) *StatusViewUpdateOne {
	if v != nil {
		_u.SetStatusProfileID(*v)
	}
	return _u
}

// AddStatusProfileID adds value to the "status_profile_id" field.
func (_u *StatusViewUpdateOne) AddStatusProfileID(v int64) *StatusViewUpdateOne {
	_u.mutation.AddStatusProfileID(v)
	return _u
}

// ClearStatusProfileID clears the value of the "status_profile_id" field.
func (_u *StatusViewUpdateOne) ClearStatusProfileID() *StatusViewUpdateOne {
	_u.mutation.ClearStatusProfileID()
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *StatusViewUpdateOne) SetProfileID(v uint64) *StatusViewUpdateOne {
	_u.mutation.ResetProfileID()
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *StatusViewUpdateOne) SetNillableProfileID(v *uint64) *StatusViewUpdateOne {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// AddProfileID adds value to the "profile_id" field.
func (_u *StatusViewUpdateOne) AddProfileID(v int64) *StatusViewUpdateOne {
	_u.mutation.AddProfileID(v)
	return _u
}

// ClearProfileID clears the value of the "profile_id" field.
func (_u *StatusViewUpdateOne) ClearProfileID() *StatusViewUpdateOne {
	_u.mutation.ClearProfileID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StatusViewUpdateOne) SetUpdatedAt(v time.Time) *StatusViewUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the StatusViewMutation object of the builder.
func (_u *StatusViewUpdateOne) Mutation() *StatusViewMutation {
	return _u.mutation
}

// Where appends a list predicates to the StatusViewUpdate builder.
func (_u *StatusViewUpdateOne) Where(ps ...predicate.StatusView) *StatusViewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StatusViewUpdateOne) Select(field string, fields ...string) *StatusViewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StatusView entity.
func (_u *StatusViewUpdateOne) Save(ctx context.Context) (*StatusView, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StatusViewUpdateOne) SaveX(ctx context.Context) *StatusView {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StatusViewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StatusViewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StatusViewUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := statusview.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *StatusViewUpdateOne) sqlSave(ctx context.Context) (_node *StatusView, err error) {
	_spec := sqlgraph.NewUpdateSpec(statusview.Table, statusview.Columns, sqlgraph.NewFieldSpec(statusview.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StatusView.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, statusview.FieldID)
		for _, f := range fields {
			if !statusview.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != statusview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StatusID(); ok {
		_spec.SetField(statusview.FieldStatusID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedStatusID(); ok {
		_spec.AddField(statusview.FieldStatusID, field.TypeUint64, value)
	}
	if _u.mutation.StatusIDCleared() {
		_spec.ClearField(statusview.FieldStatusID, field.TypeUint64)
	}
	if value, ok := _u.mutation.StatusProfileID(); ok {
		_spec.SetField(statusview.FieldStatusProfileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedStatusProfileID(); ok {
		_spec.AddField(statusview.FieldStatusProfileID, field.TypeUint64, value)
	}
	if _u.mutation.StatusProfileIDCleared() {
		_spec.ClearField(statusview.FieldStatusProfileID, field.TypeUint64)
	}
	if value, ok := _u.mutation.ProfileID(); ok {
		_spec.SetField(statusview.FieldProfileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedProfileID(); ok {
		_spec.AddField(statusview.FieldProfileID, field.TypeUint64, value)
	}
	if _u.mutation.ProfileIDCleared() {
		_spec.ClearField(statusview.FieldProfileID, field.TypeUint64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(statusview.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &StatusView{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statusview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
