// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"glintfed.org/ent/userpronoun"
)

// UserPronounCreate is the builder for creating a UserPronoun entity.
type UserPronounCreate struct {
	config
	mutation *UserPronounMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *UserPronounCreate) SetUserID(v uint64) *UserPronounCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *UserPronounCreate) SetNillableUserID(v *uint64) *UserPronounCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetProfileID sets the "profile_id" field.
func (_c *UserPronounCreate) SetProfileID(v uint64) *UserPronounCreate {
	_c.mutation.SetProfileID(v)
	return _c
}

// SetPronouns sets the "pronouns" field.
func (_c *UserPronounCreate) SetPronouns(v []string) *UserPronounCreate {
	_c.mutation.SetPronouns(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserPronounCreate) SetCreatedAt(v time.Time) *UserPronounCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserPronounCreate) SetNillableCreatedAt(v *time.Time) *UserPronounCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserPronounCreate) SetUpdatedAt(v time.Time) *UserPronounCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserPronounCreate) SetNillableUpdatedAt(v *time.Time) *UserPronounCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserPronounCreate) SetID(v uint64) *UserPronounCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UserPronounMutation object of the builder.
func (_c *UserPronounCreate) Mutation() *UserPronounMutation {
	return _c.mutation
}

// Save creates the UserPronoun in the database.
func (_c *UserPronounCreate) Save(ctx context.Context) (*UserPronoun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserPronounCreate) SaveX(ctx context.Context) *UserPronoun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPronounCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPronounCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserPronounCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userpronoun.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userpronoun.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserPronounCreate) check() error {
	if _, ok := _c.mutation.ProfileID(); !ok {
		return &ValidationError{Name: "profile_id", err: errors.New(`ent: missing required field "UserPronoun.profile_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserPronoun.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserPronoun.updated_at"`)}
	}
	return nil
}

func (_c *UserPronounCreate) sqlSave(ctx context.Context) (*UserPronoun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserPronounCreate) createSpec() (*UserPronoun, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPronoun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userpronoun.Table, sqlgraph.NewFieldSpec(userpronoun.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userpronoun.FieldUserID, field.TypeUint64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ProfileID(); ok {
		_spec.SetField(userpronoun.FieldProfileID, field.TypeUint64, value)
		_node.ProfileID = value
	}
	if value, ok := _c.mutation.Pronouns(); ok {
		_spec.SetField(userpronoun.FieldPronouns, field.TypeJSON, value)
		_node.Pronouns = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userpronoun.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userpronoun.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// UserPronounCreateBulk is the builder for creating many UserPronoun entities in bulk.
type UserPronounCreateBulk struct {
	config
	err      error
	builders []*UserPronounCreate
}

// Save creates the UserPronoun entities in the database.
func (_c *UserPronounCreateBulk) Save(ctx context.Context) ([]*UserPronoun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserPronoun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPronounMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserPronounCreateBulk) SaveX(ctx context.Context) []*UserPronoun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPronounCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPronounCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
